### ISSUE TITLE
1.16.5: CCR busts CMI database

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1007]
After updating the CCR to 10.4.1 CMI database got broken and every player name is empty in the output of that plugin. This might not directly affect the CMI, but some other data which is later stored in CMI db. For example, Discord SRV also outputs empty player names when **list** command is used.

How I found it out:

1. Deleted CCR.
2. Restored cmi.sqlite.db file from the backup.
3. Logged in.
4. Player names are visible.
5. Bring CCR back in.
6. Logged in.
7. Player names are not visible.
8. Deleted CCR.
9. Player names are still not visible.
10. Resotred DB from backup again.
11. Player names are still not visible.

Outcome: CCR breaks CMI database directly or indirectly.

What can cause this? Probably this:
`Fix | Solved ChatControl Red not properly saving nicknames to Essentials' player database (saving as & not § instead).`

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by x1p** [comment]
I noticed this behavior on my test server too.

According to my tests, the damage is irreversible.
ChatcontrolRed gives the player an empty nickname. You can observe this when you have the CMI database in a mysql server.
The displayname will not be restored when Chatcontrol is removed from the server, or reverted back to a working version.
So when you run CMI in a local storage file, you're pretty much screwed.
I suggest you re-open the CMI issue to let him investigate how this can be undone automatically, if even possible.

Somehow, my production servers are not having this, yet. I haven't figured out what change I've made that is responsible for this.
Edit: it's the Tag function. `Apply_On: [] ` It gives everyone a Nickname `''` (empty), instead of *Null*

If you want to test too keep in mind to perform this on a test server only.
When you want to redo the test: shut down the server, delete the database file from CMI and start again. This because once the damage is done, it can't be reversed.

(Edited with the latest insights)

**Comment by radiant-ai** [comment]
> I noticed this behavior on my test server too.
> 
> According to my tests, the damage is irreversible.
> ChatcontrolRed gives the player an empty nickname. You can observe this when you have the CMI database in a mysql server.
> The displayname will not be restored when Chatcontrol is removed from the server, or reverted back to a working version.
> So when you run CMI in a local storage file, you're pretty much screwed.
> I suggest you re-open the CMI issue to let him investigate how this can be undone automatically, if even possible.
> 
> Somehow, my production servers are not having this, yet. I haven't figured out what change I've made that is responsible for this.
> Edit: it's the Tag function. `Apply_On: [] ` It gives everyone a Nickname `''` (empty), instead of _Null_
> 
> If you want to test too keep in mind to perform this on a test server only.
> When you want to redo the test: shut down the server, delete the database file from CMI and start again. This because once the damage is done, it can't be reversed.
> 
> (Edited with the latest insights)

This was a super fast and easy fix without even shutting down the server.
I downgraded the CCR and restored the database with a simple SQL query: `UPDATE users SET nickname=NULL, DisplayName=username`

P.S. And no, local storage is not screwed at all, it is an ordinary SQLITE db file that can be read and modified by any sqlite driver. You can even VACUUM it to save some storage.

**Comment by radiant-ai** [comment]
A comment for the reference for those, who have their database affected and they need to fix it:

1. Backup your CCR config folder.
2. Backup you MySQL database or `cmi.sqlite.db` file from CMI folder.
3. Stop server.
4. Downgrade CCR to 8.4.3.8
5. If you run MySQL execute `UPDATE users SET nickname=NULL, DisplayName=username` to fix your users table.
If you use `cmi.sqlite.db` file (local storage) use any SQLITE editor or online editor https://sqliteonline.com/ open your `cmi.sqlite.db` in it and run query `UPDATE users SET nickname=NULL, DisplayName=username`
![image](https://user-images.githubusercontent.com/43506080/118757018-ca303f80-b831-11eb-8b2f-2638ff75b980.png) After that save the file and put it back into CMI folder.
6. Start the server.

**Comment by kangarko** [comment]
Thanks for reporting, I thought they handle empty nicknames properly, I will mitigate this on our end

**Comment by kangarko** [comment]
Fixed, the next ChatControl Red will store empty or color-only nicknames as null for EssentialsX and CMI.

Thanks guys and I do apology. Was not aware of how these third parties handle empty nicknames, thought they simply treated them as nulls.
