### ISSUE TITLE
16.5 Rules not working

### ISSUE THREAD

**Issue by Parthurax** [kangarko/ChatControl#1011]
Hi, for some reason rules are not working.
Do i have to enable them somehow ?
chat.rs stuff dont respond.
I have protocol lib installed, tested without it still not working

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

**Comment by ElBananaa** [comment]
> Hi, for some reason rules are not working.
> Do i have to enable them somehow ?
> chat.rs stuff dont respond.
> I have protocol lib installed, tested without it still not working
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: false

Hey.
You must enable the channel system to use the rules.

**Comment by Parthurax** [comment]
> > Hi, for some reason rules are not working.
> > Do i have to enable them somehow ?
> > chat.rs stuff dont respond.
> > I have protocol lib installed, tested without it still not working
> > Minecraft Version: 1.16.5
> > MySQL: true
> > BungeeCord: false
> 
> Hey.
> You must enable the channel system to use the rules.

Hi it is enabled ^^ and things like :yay: or whatever dont work it happens nothing

**Comment by ElBananaa** [comment]
> > > Hi, for some reason rules are not working.
> > > Do i have to enable them somehow ?
> > > chat.rs stuff dont respond.
> > > I have protocol lib installed, tested without it still not working
> > > Minecraft Version: 1.16.5
> > > MySQL: true
> > > BungeeCord: false
> > 
> > 
> > Hey.
> > You must enable the channel system to use the rules.
> 
> Hi it is enabled ^^ and things like :yay: or whatever dont work it happens nothing


Weird, I don't have a such issue.
Could you please provide us your `/chc debug` output file?

**Comment by Parthurax** [comment]
https://ufile.io/muyp7kqj

thank you, it is not much changed in there, nearly nothing ^^

**Comment by TheIntolerant** [comment]
@Parthurax to enable a rule you must remove the hashtags, the hashtags turn that specific bit of the file into a comment, so the plugin doesn't read it. Useful for explaining parts of the code etc which is why there are hashtags at the start all over the files.

So just change
```
#match \:yay\:
#then replace \( ﾟヮﾟ)/
```
to 
```
match \:yay\:
then replace \( ﾟヮﾟ)/
```
and repeat that for every other rule you wish to enable. 

-----------------------------------------------------------

Just make sure to not remove the hashtags for actual "comments".
For example, say I wanted to enable this rue
```
# Tell people how to do basic things on your server.
#match ^how (do|can) (I|you) (build|claim)(| a) (land|residence)
#then warn {prefix_info}Use &9/help land &7to learn about claiming land!
#then deny
```
I'd just change it to this,
```
# Tell people how to do basic things on your server.
match ^how (do|can) (I|you) (build|claim)(| a) (land|residence)
then warn {prefix_info}Use &9/help land &7to learn about claiming land!
then deny
```
Since the comment here is just telling me what this specific rule does. I hope this helps you understand the usage of hashtags in the chatcontrol files and how they can also be useful. :)

**Comment by kangarko** [comment]
Thanks to gone-incognito for all the help! You're a champ <3
