### ISSUE TITLE
1.16.5 How to turn off Console tells you "you killed a player / mob".

### ISSUE THREAD

**Issue by hasantahahd** [kangarko/ChatControl#1027]
How can i turn off this? 
Console messages you telling you you killed a player / mob.
No need for /chc debug. Just a question.
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> How can i turn off this?
> Console messages you telling you you killed a player / mob.
> No need for /chc debug. Just a question.
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
Try disabling the `Show_Tips` part in the settings file, it should disable some console messages, probavly including death messages in the console (that's not sure tho)

**Comment by kangarko** [comment]
Thanks to Banana!

And you can also have a look at messages/death.rs to find the one and remove the operator responsible for this or the entire message

**Comment by hasantahahd** [comment]
Hi! Show_Tips is set to false and deaths.rs is empty (i deleted everything in that file) and it still shows that message.

**Comment by ElBananaa** [comment]
> Hi! Show_Tips is set to false and deaths.rs is empty (i deleted everything in that file) and it still shows that message.

If the death.rs file is empty, it means it uses the vanilla death messages, so I guess this isn't something on our end, but on yours.

**Comment by JasmeowTheCat** [comment]
Hasan is my head dev, so I will be popping into this as well.

It's not any other plugin causing this, since if I disable chat control red, nothing occurs. I can provide my plugin list below: 
<Removed Now, No Longer Needed>
If you could suggest what's causing it, that would be great.

To backup his claim, these are the two files:
![image](https://user-images.githubusercontent.com/81937080/120088060-017dd680-c0e5-11eb-872a-1c0f58271f1d.png)
![image](https://user-images.githubusercontent.com/81937080/120088069-0c386b80-c0e5-11eb-939d-fc4203ca9b0d.png)

**Comment by hasantahahd** [comment]
Hi! I never informed you about the message that we are trying to remome. This is the message: 
![image](https://user-images.githubusercontent.com/76966448/120105595-4136d380-c162-11eb-86cf-761e32ab1ffd.png)

**Comment by kangarko** [comment]
Got it, if the issue goes away after removing ChatControl, then it's either someone typing this message from the console to the player or something invoking it. Any other plugin can call /tell {player} and then ChatControl hooks into this... Or, search ChatControlRed/ folder for "Good job!" string to see if any files contain it and remove it.

**Comment by JasmeowTheCat** [comment]
Hi Matej,

We found it! Turns out it wasn't Chat Control Red! It was CombatLogX. Downloaded all the plugins files and searched them all with Notepad ++. Turns out it's a reward based thing, between 50% and 100%. If you ever come across it, it's in expansions/rewards/rewards.yml at the bottom. Might want to keep this thread around as someone might google for the same issue, and when I did, I found nothing. 

I really do appreciate your time on this issue, and Hasan can now close this ticket.
