### ISSUE TITLE
1.7.10 Mohist (Cauldron fork): Hoverable and clickable elements do not respond

### ISSUE THREAD

**Issue by funnykeyboardsymbols** [kangarko/ChatControl#1043]
All hoverable and clickable elements do nothing. I checked, and Minecraft 1.7.10 supports json, and I tested the command `/tellraw @a {"text":"Click this!","clickEvent":{"action":"run_command","value":"/say Hello!"}}` and it worked perfectly. I did the same with a comparable hover command, and it also worked.

Is this feature broken in CHCR for 1.7.10? Or is there an additional step somewhere that I need to do?

Minecraft Version: 1.7.10 Mohist (cauldron fork)
MySQL: false
BungeeCord: false
ProtocolLib: 3.7.0

**Comment by kangarko** [comment]
It will never work due to missing APIs

**Comment by funnykeyboardsymbols** [comment]
Can you clarify the specifics on which APIs are missing, and from which part of my application? Is this due to Cauldron? Minecraft version? ProtocolLib version? Something else? What are the APIs that are missing?

**Comment by kangarko** [comment]
I am sorry, yes, here's our source of the sendComponent method which has custom handling for 1.7.10, seems to me these classes are different under Cauldron, but since our library is open source anyone can contribute. I don't have enough time right now to add support for this quickly:

https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/remain/Remain.java#L2503
