### ISSUE TITLE
1.16.5: Permission to use the default chat format's delete feature?

### ISSUE THREAD

**Issue by CrispyDairy** [kangarko/ChatControl#1081]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Whats the permission to use the [X] feature? I can't find a permission that would give my moderators the permission to use it. its not chatcontrol.command.clear, and the permission given in the config only lets them see it
![image](https://user-images.githubusercontent.com/81482501/121788445-06a74f00-cbd6-11eb-9a77-1cc2dca78338.png)

**Comment by TheIntolerant** [comment]
I'll test this on a fresh install and see if I can reproduce this issue.

**Comment by CrispyDairy** [comment]
Alright, thank you.

**Comment by CrispyDairy** [comment]
Also, any idea on the perm? Like I said, the one in the config only lets people see the X in the message, not use it. And its not chatcontrol.clear either

**Comment by JustDriessen** [comment]
Hey @CrispyDairy 

This is the permission you will have to use: chatcontrol.removemessages 
Goodluck!

**Comment by TheIntolerant** [comment]
I tested using a fresh install of chatcontrol and only had these permissions
```
chatcontrol.channel.autojoin.standard.write
chatcontrol.channel.join
chatcontrol.channel.join.standard
chatcontrol.channel.join.standard.write
chatcontrol.removemessages
```
As I had no issues removing messages it seems that is something else stopping you from using the feature. 

As {label} in `` Run_Command: /{label} internal remove {message_uuid}``, would be the same if the command was ``/chc internal remove {message_uuid}``. 

You could try changing this:
`` Run_Command: /{label} internal remove {message_uuid}``

To: 
`` Run_Command: /chc internal remove {message_uuid}`` or 
`` Run_Command: /chatc internal remove {message_uuid}``
etc

Basically, try changing ``{label}`` for one of the command aliases for ChatControl-Red, found in ``settings.yml``
```yml
# -------------------------------------------------------------------------------------------------
# What commands should trigger the main plugin command?
#
# If you have ChestCommands or another plugin with same commands, simply remove or rename ours.
# * THE FIRST ALIAS IS THE MAIN LABEL, PLEASE DO NOT REMOVE IT. *
# -------------------------------------------------------------------------------------------------
Command_Aliases:
- 'chc'
- 'cpp'
- 'chatc'
```
As the issue, you are having could be due to conflicting commands, if that doesn't help, if you don't mind please upload your debug file, you can get this by doing ``/chc debug``

**Comment by TheIntolerant** [comment]
Another thing you could do is see if your staff can run the command ``/chatc internal`` etc. as I removed all my perms and was still able to run that command. Another thing you should do is double-check all dependencies and make sure they are up-to-date.

**Comment by CrispyDairy** [comment]
Alright, I'll run through the list. They don't even have permissions to run chatc internal. Are there any other dependencies than vault?

**Comment by TheIntolerant** [comment]
protocollib is the only other plugin chatcontrol uses i believe

**Comment by TheIntolerant** [comment]
As protocolLib is required to [remove messages](https://github.com/kangarko/ChatControl-Red/wiki/Channels#removing-messages), you will need that plugin.

**Comment by CrispyDairy** [comment]
Yeah we have both vault and protlib up to date.

**Comment by CrispyDairy** [comment]
I still can't switch channels even after doing a fresh install of red, and the permission doesn't work. I probaply have another plugin messin with stuff https://pastebin.com/suHCT8LE

**Comment by CrispyDairy** [comment]
This isn't that much of an issue, except that I can't use discordsrv staff chat. For some reason the messages ingame don't go to the channel, but messages from our staff minecraft channel come ingame. So I don't really need the channels if this can somehow be fixed.

**Comment by CrispyDairy** [comment]
![image](https://user-images.githubusercontent.com/81482501/121909462-982dd280-cd36-11eb-98f2-b0e72d3d8c1e.png)
This is what happens when I send a message INSIDE minecraft staff chat, it doesn't go through to the discord staff chat. But when I send a message on discord, it goes ingame

**Comment by ElBananaa** [comment]
> I still can't switch channels even after doing a fresh install of red, and the permission doesn't work. I probaply have another plugin messin with stuff https://pastebin.com/suHCT8LE

Hey!
This issue is caused by the latest version of the plugin, I believe. Since Kangarko is on vacations until the 2nd of july, please use a previous working version of the plugin until this issue gets fixed.
Regarding the 2nd issue, there must be a problem in your config. Make sure it's configured as described on the wiki : https://github.com/kangarko/ChatControl-Red/wiki/Discord

**Comment by CrispyDairy** [comment]
I don't really need channels anyways as long as I get staffchat passing to discord, I'll check through the config

**Comment by CrispyDairy** [comment]
I have it set up correctly, but I believe the issue is that chatcontrol doesn't detect discordsrv staffchat's "staff-chat"..?

**Comment by TheIntolerant** [comment]
Re: the delete message feature do you mind doing ``/chc debug`` so I can test your setup? And uploading that file here.

**Comment by CrispyDairy** [comment]
I'll do that as soon as I can

**Comment by CrispyDairy** [comment]
https://ufile.io/jp3onx5s Here you go

**Comment by broken1arrow** [comment]
> Also, any idea on the perm? Like I said, the one in the config only lets people see the X in the message, not use it. And its not chatcontrol.clear either

has you get it sorted out?

Is this part you can look on you should have chat.yml in formats folder. It not a "default perm" is a custom one (you can change it to something else too).

```
  delete-chat:
    Message: '&8[&4X&8] &f'
    Receiver_Permission: chatcontrol.removemessages
    Hover:
    - '&cRemove this message from chat for all players.'
    Run_Command: /{label} internal remove {message_uuid}
```

**Comment by radiant-ai** [comment]
`/lp verbose on PLAYERNAME & chatcontrol`
Learn how to use LuckPerms debug and you will save a ton of time.

**Comment by TheIntolerant** [comment]
Sorry about the delay, I tested your setup and found the ``[x]`` component of chat is working as intended.

For reference, this was my setup when testing:

**Permissions:**
``luckperms.*`` 
``chatcontrol.removemessages``

**Server info:**
```
Plugin: ChatControlRed v10.4.9
Server Version: Paper v1_16_R3
Java: 11.0.11 (Oracle Corporation/Ubuntu)
OS: Linux 4.4.0-176-generic
Players Online: 0
Plugins: LuckPerms v5.3.47, Vault v1.7.3-b131, ProtocolLib v4.6.0, ChatControlRed v10.4.9
```

------------------------

As I could not reproduce this issue, I believe this is being caused by a third-party plugin.

**Comment by kangarko** [comment]
Sorry for the delay, as gone-incognito mentioned, likely caused by a third party, please deinstall every other plugin for a test round to diagnoze and found out where this is coming from.
