### ISSUE TITLE
/ch (console) and /ch join (ingame) return an NPE

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl#1083]
https://github.com/kangarko/ChatControl-Red/issues/1058

when I updated to 10.4.6 or 10.4.7
player cannot using /ch join and /ch on console

error log: https://pastebin.com/YmedGjRD

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey,
I can confirm I could reproduce this issue on my end.
Unfortunately, Kangarko is on vacations until the 2nd of july, so you'll have to wait until then to get a fix.
I still suggest you send an email to matej@mineacademy.org with this issue link since it seems to be a pretty important issue.
In the meantime, consider using a previous working version of the plugin until this issue gets fixed.

**Comment by kangarko** [comment]
Thanks, will be patched asap
