### ISSUE TITLE
Rules w/ Receiver Permission

### ISSUE THREAD

**Issue by Alexz1008** [kangarko/ChatControl#1099]
Hi there, your plugin is absolutely wonderful and I'm in love with the fact that I can format my towny chat so that if a receiver has a permission, the town and nation tag doesn't show for them in the chat. I'm hoping since this functionality exists, it can apply to rules too. I am suggesting that you add a "require recperm [permission]" operator in your rules, which requires the receiver to have a permission (or the negation of a permission) in order for a rule to apply.

**How would it benefit others?**
This would singlehandedly make your chat plugin have one of my (and I believe many others) most sought after customization: allowing players to choose whether they want swear words filtered or not.

**How is my server being affected?**
Not much difference, people will just not be allowed to swear.

I'm aware that this is a large (and extremely well-made) plugin with a very small team. I do hope you consider the request, but I'm also aware that it's probably tricky to do receiver-based rules, I'm just hoping that it happens to be easy to implement given the chat formats have this implemented. After having made this suggestion, I realized just now that you'd have to make a completely new way for rules to apply on reception instead of on sending, which is probably a huge rewrite, but I'll leave the suggestion up anyway. Thanks for considering, and thanks for making me a very happy server owner!

Regards,
Alex Z (Neoblade298)

**Comment by ElBananaa** [comment]
> Hi there, your plugin is absolutely wonderful and I'm in love with the fact that I can format my towny chat so that if a receiver has a permission, the town and nation tag doesn't show for them in the chat. I'm hoping since this functionality exists, it can apply to rules too. I am suggesting that you add a "require recperm [permission]" operator in your rules, which requires the receiver to have a permission (or the negation of a permission) in order for a rule to apply.
> 
> **How would it benefit others?**
> This would singlehandedly make your chat plugin have one of my (and I believe many others) most sought after customization: allowing players to choose whether they want swear words filtered or not.
> 
> **How is my server being affected?**
> Not much difference, people will just not be allowed to swear.
> 
> I'm aware that this is a large (and extremely well-made) plugin with a very small team. I do hope you consider the request, but I'm also aware that it's probably tricky to do receiver-based rules, I'm just hoping that it happens to be easy to implement given the chat formats have this implemented. After having made this suggestion, I realized just now that you'd have to make a completely new way for rules to apply on reception instead of on sending, which is probably a huge rewrite, but I'll leave the suggestion up anyway. Thanks for considering, and thanks for making me a very happy server owner!
> 
> Regards,
> Alex Z (Neoblade298)

Hey!
Thanks for your kind message ♥ Yes, it's a very small team. To be completely honest, Kangarko is working alone on the plugin, so I'm sure he'll enjoy your message.
Regarding your suggestion, I believe this could potentially by achieved with the `ignore perm <permission>` operator. But not with the current state of the plugin unfortunately.
The issue here is that using the `ignore perm` operator will also allow them to swear because it'll cancel the entire rule.
I found a previous issue in which someone asked something pretty similar to what you'd like that wouldn't require a complete rewrite of the plugin (#443).

I truly think that adding a `require recperm` operator would be pretty useful for a lot of other things tho.

Let's wait for Kangarko to get back from vacations (Near the beginning of July) to take a look at your suggestion :)

**Comment by kangarko** [comment]
You can already use Receiver_Permission in your formatting/ folder to show different format (parts) for different receivers. We're currently not planning on expanding this onto rules.

**Comment by kangarko** [comment]
Thanks for your kind words thought!
