### ISSUE TITLE
Migration issues

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#110]
The MOTD has migrated, but it doesn't seem to parse the JSON.

![image](https://user-images.githubusercontent.com/5664135/99649936-194d1180-2a55-11eb-91e0-1c1476463c48.png)

My format doesn't seem to work in-game, I thought because I am not in a channel so I used the /channel command but it errors out. I am not completely sure if this is a migration issue or if I missed something in migration.log that I have to do.

Error: https://pastebin.com/BaL51N9t

All files attached: 
files redacted

**Comment by kangarko** [comment]
Thanks, I am on it.

**Comment by kangarko** [comment]
Please ZIP me your whole folder if possible, I can migrate it for you and ensure everything works. If you want to send it private, upload it to uploadfiles.io and send it to matej@mineacademy.org

**Comment by Sikatsu** [comment]
Hey, I already did that but I see the files are redacted. Uploading the new ones below:

-removed-

**Comment by Sikatsu** [comment]
Then again this is only one server, still have to migrate the others as well before using it on production.

**Comment by kangarko** [comment]
I redacted it because I noticed some information that may be sensitive but I downloaded it. However I asked for the original 8th generation files whereas those above were already migrated.

No worries, you can upload all servers you have and send to matej@mineacademy.org and I'll migrate everything for you and ensure it works.

**Comment by kangarko** [comment]
Well I can add JSON support but it's going to drain performance. You JSON is very ineffective and has many repetitive codes:

<img width="1386" alt="Screenshot 2020-11-19 at 15 52 59" src="https://user-images.githubusercontent.com/1918426/99682279-575f2b00-2a7f-11eb-9fc6-1a3ad12efc1a.png">

This is not your fault because previously, creating high-performance systems was not possible. I've added a primitive JSON to Format converter, but since this is only a machine translation, you'll have to cut down the repetition and add "\n" yourself. Here, I would just merge the "text" and the "color" and use & instead of color names such as "&7Welkom op &3VillagerCraft &7!" and it would have the same hover under it, just once. Of course, the image above is just JSON to YAML, our syntax is different.

This will come with the next version.

Still going through your other files though.

**Comment by Sikatsu** [comment]
Oh, I used a website to write this JSON. I'm not all too familiar with JSON and thought this was the right way to do so.

I am currently sending the files to the email provided, thanks a lot! ^^

**Comment by kangarko** [comment]
Alright thanks, I have improved the system and it migrated all of your files! A bit weird when testing, but I guess your permission system takes care of it: 
<img width="650" alt="Screenshot 2020-11-19 at 16 20 31" src="https://user-images.githubusercontent.com/1918426/99686722-28978380-2a84-11eb-8696-f810c280912d.png">

Caveact: You'd have to add empty `- ''` lines to Message keys for the migrated-motd format to make the multiline work again:
<img width="951" alt="Screenshot 2020-11-19 at 16 22 37" src="https://user-images.githubusercontent.com/1918426/99686735-2af9dd80-2a84-11eb-95c6-f9e20dd6a5ee.png">

**Comment by kangarko** [comment]
My best advice for you would be doing the migration, then copy paste messages/ and rules/ folders somewhere else, then remove ChatControlRed and let it regenerate again and then paste those two folders over. That way, you will only migrate messages.yml and rules/ folders and you'll have to start clean with everything else, which may be a little bit of work but I spent 9 months writing the new code so it will run much faster.

**Comment by Sikatsu** [comment]
Awesome! Yeah, the messages file is the most important file to migrate. The other settings I can do manually. If I have any further questions i'll let you know, but I think I can find my way with that! Planning to use it in production on monday/tuesday.

**Comment by kangarko** [comment]
Awesome <3
