### ISSUE TITLE
Suggestion: Custom Chc Color menu 

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl#1102]
Chatcontrol provides amazing features regarding chatcolors, we can use hexcolors and more, it would be great if the menu could also support adding custom hex chatcolors, which (just like all the other colors) would show up if you had the right permission. Maybe this could be done using a config file or an ingame editor. Right now, we need to make custom menus for our special colors, which makes it less organised. As a result, many people will benefit from a solution for this common problem and it would make the feature even more useful.

If it's not implemented, people need to use a custom menu plugin like commandpanels.

**Comment by TheIntolerant** [comment]
I believe it is not being added due to time constraints but may be added at a later date, #1034

**Comment by ElBananaa** [comment]
Hey!
This feature is already in the roadmap (which can be found here: https://github.com/kangarko/ChatControl-Red/issues/1), as it was suggested in #282 but as you can see there, this isn't a high priority for now (especially with mc 1.17 and the possible amount of fixes that will be needed to make the plugin stable on this version).

However, i'd suggest leaving your suggestion open so Kangarko could see that more people want to see this feature added to the plugin.

**Comment by kangarko** [comment]
I apologies but due to limited time we're not planning on adding this right now.

**Comment by 2SaucesLong** [comment]
Is this still on the roadmap? I’m running into the same issue. It's quite cumbersome to recreate the entire chat color menu just to support custom gradient colors. It would be much more intuitive and user-friendly if gradients could be added directly alongside the existing colors. Right now, using the /chc color command with a gradient isn’t very straightforward, especially since it doesn’t list available hex colors, even when an invalid one is entered. Having everything in one place would really streamline the experience.

**Comment by kangarko** [comment]
Would you like a settings.yml option to add custom gradients to the menu?
