### ISSUE TITLE
1.17: Unable to swap chat channels- "player not connected through bungeecord"

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#1109]
So it seems everyone, including admins are eternally stuck in whatever chat channel they last joined a few days ago and I'm not sure what caused it. They're still able to chat with others who also happen to be stuck in the same channel as them, and even receive/send discord messages. However running the 'ch j (channel)' command always returns "player is not connected through bungeecord", it doesn't produce any error logs.

EDIT: Also, sending private messages to other players returns "player is not on this server" even though they're online

Using chatcontrol 10.4.9/nashorn 1.1.0, and the latest version of Paper (#39) and the latest Waterfall.  

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6698643/debug.zip)

Minecraft Version: 1.17 
MySQL: true
BungeeCord: true

**Comment by ghost** [comment]
me too

**Comment by ElBananaa** [comment]
Hey!
Thanks for reporting this issue, and sorry for the delays.
Unfortunately, I have neither the time to try to reproduce your issue, nor the setup to do so, so I won't be able to help you with your issue.
However, it looks like this has been reported several times since chc v10.4.6, so my guess is that this is probably a plugin issue. Unfortunately, Kangarko is unable to take a look at it until the 2nd of july since he's on vacation, so if you both don't mind, I'd suggest waiting for him to get back from vacations so he could have a look at your issues.

**Comment by kangarko** [comment]
Have you connected through BungeeCord and not directly to your Spigot/Paper server? Also try switching UUID_Lookup in mysql.yml to true/false from what you have there already.

**Comment by ghost** [comment]
UUID_Lookup :true / false 
Still can't switch channels

**Comment by Squeej** [comment]
Yup nothin, regardless if set to true/false. Would CMIlib interfere in anyway?

I have been connecting through bungeecord yes, and not directly to the servers.

**Comment by kangarko** [comment]
CMILib may or may not, I don't know, you can try removing it.

Also there's an user having a similar problem who fixed it, can you please try following his steps first? https://github.com/kangarko/ChatControl-Red/issues/1066

**Comment by ghost** [comment]
delete all the Bungee folder and recreate it again The things is that this was solved.
thank!

**Comment by kangarko** [comment]
Cool, probably caused by an error in upgrading from an earlier version, I apology. @Squeej please follow the same.
