### ISSUE TITLE
1.16.5: Nickname question

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1114]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
Debug: https://ufile.io/xyyx9tkd

I have one player who's nickname keeps getting reset once he relogs. What could be a possible cause of this?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> Debug: https://ufile.io/xyyx9tkd
> 
> I have one player who's nickname keeps getting reset once he relogs. What could be a possible cause of this?

Hey. I noticed the same issue automatically joined channels on my side, idk if this is related tho, but it started happening since the latest releases, so I guess you could try to use a previous version as a temp fix.

**Comment by Sikatsu** [comment]
I think it might have to do with people changing their minecraft names. I can't really go back as that had issues with nashorn on java 16 :/

**Comment by ElBananaa** [comment]
> I think it might have to do with people changing their minecraft names. I can't really go back as that had issues with nashorn on java 16 :/

Well, the issue on my side is that I didn't change my username since something like 2017, so i'm not sure about it, but it's a possibility tho. Let's wait for kangarko to have a look at this issue once he gets back from vacation ^^

**Comment by mrcoffee1026** [comment]
This is happening for ALL of my users including myself: relogs cause nicks to reset.  Also have noticed that {nick} and {player_name} are never set to the nick name when it is set.  The only thing that seems to even work temporarily is using {cmi_user_display_name} in formats but this is also reset upon reconnect.

**Comment by ElBananaa** [comment]
> This is happening for ALL of my users including myself: relogs cause nicks to reset. Also have noticed that {nick} and {player_name} are never set to the nick name when it is set. The only thing that seems to even work temporarily is using {cmi_user_display_name} in formats but this is also reset upon reconnect.

Did you complete the `/chc tour`?
From what you're telling us, it looks like your files are all getting completely wiped after every restart, which, if I'm not wrong, only happens if you didn't complete the tour.

**Comment by mrcoffee1026** [comment]
I did complete the tour, thank you, and if you'd read more closely: I said the nicks are cleared from players whenever THEY relog, not when the server restarts. Furthermore, none of my files are being cleared nor reset.

**Comment by kangarko** [comment]
I assume your UUID_Lookup option in mysql.yml has been on true, please guys set this option to false and that should resolve it. We cannot rely on UUIDs when using BungeeCord since your server is set to regenerate them.

If you already did set this option and/or it still does not work please comment below.

**Comment by mrcoffee1026** [comment]
I can't find anything about this in settings.yml and am assuming this is a bungeecord only setting you're describing and so doesn't apply to my setup: I am not using bungee.   -- sorry just noticed you said in mysql.yml... I am also not using mysql.  I changed the value to false anyway but this had no effect.

**Comment by kangarko** [comment]
@mrcoffee1026 in this case please post me your /chc debug file because I was not able to reproduce this problem, assuming you have Tag.Apply_On set to contain "nick". You can also view player-uuid-nick combination as we see it in usermap.csv if you are not using MySQL.

**Comment by kangarko** [comment]
Also there should be a console message "UUID of player X is Y" when players relog. You can check if the Y which is their UUID stays the same or not.

**Comment by mrcoffee1026** [comment]
I am not using the "tag" feature at all, to my knowledge.

```
[15:08:08 INFO]: mr_coffee1026 has left Community Brew!
[15:08:12 INFO]: UUID of player mr_coffee1026 is e6ddad0f-a28e-4d4b-8415-4b5460e69f97
[15:08:12 INFO]: TIP: Joining player to his saved channel admin in mode read
[15:08:12 INFO]: TIP: Joining player to his saved channel standard in mode write
[15:08:12 INFO]: TIP: Player mr_coffee1026 is already in channel 'admin' in mode read, not adding.
[15:08:12 INFO]: mr_coffee1026[/68.39.192.23:2984] logged in with entity id 657142 at ([world]509.97906696522955, 56.0, 603.961188199413)
[15:08:12 INFO]: mr_coffee1026 has joined Community Brew!

```
debug.zip:
https://ufile.io/yon701rp

**Comment by mrcoffee1026** [comment]
ok wait... I don't know what the CAUSE of this, but this MIGHT be the reason this is a problem now: if I look up myself in this usermap.csv file I see this:
mr_coffee,c21973fc-9f75-4b76-8c96-042e85cbc3be
mr_coffee1026,e6ddad0f-a28e-4d4b-8415-4b5460e69f97
The first UUID is not one that has ever belonged to myself.  If somehoe during the generation of this file you have randomly assigned UUIDs to every nickname as it appeared on the server, there'd be no method for these users to obtain their proper nick names again, ever.  Also, I tried clearing this file and reloading and that had no effect.  I'll try reclearing it and restarting the server later to see if this resolves things.

Also, it's not entirely random since there is an actual "Mr_Coffee" user that exists with that first UUID, but they've never played this server, this would had to have had something to do with the "lookup" option which, since you'd already advised shutting off in the mysql.yml file, I did.  Since this breaks nicknames, I think you should change the documentation from "# If your server is cracked set this to false" to something like "# only set to true in the really bizarre case that you're NOT using bungee, NOT using mysql, and NOT needing nicknames to function." Since this appears to break things in every other situation and has absolutely nothing to do with having a legal server, which I do have.

**Comment by mrcoffee1026** [comment]
After a restart... and this is with the usermap.csv file reset to a 0 byte file... this issue persists.  No idea what else could be doing it at this point.

**Comment by mrcoffee1026** [comment]
I don't know if this helps sort out the root cause of the issue or not, but usernames and uuids are still being populated in the usermap.csv file even with the uuid option set to false in mysql.yml.  However, no nicknames are being stored in usermap.csv either so it seems that the data saved to usermap.csv is being used to reset every user on login.

**Comment by kangarko** [comment]
Sorry for the delay, I will be looking into this tomorrow or Monday morning. The UUID option from MySQL is only used in MySQL and is ignored if MySQL is disabled.

**Comment by mrcoffee1026** [comment]
Yeah alright, I don't know what could be causing it then, I appreciate the effort!

**Comment by NoobcoreNetwork** [comment]
Very possibly related, Using mysql, I have a double nickname on my account that I cannot get rid of and found 2 entries in the database, The top uuid i have never seen and it leads to no player.

('67da19cd-191c-34f9-b63d-b6d521691676', 'WeAreNoobs', 'Josh', '{"Channels":{"network":"write","admin":"read"}}', 1626820175647), < NOT MY UUID OR A VALID UUID

('6899ca7e-97e7-40de-8ac9-0939d4371c42', 'WeAreNoobs', 'Josh', '{"Channels":{"network":"write","admin":"read"},"Spying_Sectors":["anvil","mail","book","sign","private_message"],"Spying_Channels":["admin","network"]}', 1626820712087),

**Comment by ElBananaa** [comment]
Hi,
Thanks for reporting this. I'm reopening the issue since it looks like this isn't fixed yet.

**Comment by kangarko** [comment]
Oups, opened my desktop today to have come to this, I apology, I placed a sticky note to handle this fresh after sleep :)

**Comment by kangarko** [comment]
Okay so I did further testing and made the following changes

1. You can set Debug key to [usermap] in settings.yml to print values from usermap.csv when it is being cached in the plugin's memory, please try doing this and seeing if nicks are getting reset internally while they should not. **This only works without mysql since usermap.csv and data.db is ignored when mysql is enabled.**

2. For non-mysql using servers I have added an explicit call to save usermap when a player disconnects.

Please test the next version to see if the issue persists, I do apology for the delay again.

**Comment by mrcoffee1026** [comment]
Still a persistent issue for me.  Here is the latest.log from the point there I restarted with this debug setting.  I already had a nick set, rejoined, saw it was gone, set the nick again, rejoined, saw it was gone again.

https://pastebin.com/ykCD9KaY

**Comment by mrcoffee1026** [comment]
Might it have anything to do with THIS?
`# true = alter player's displayname (not used by us but other plugins can see this) and custom name`
displayname is what a nickname is.  Now my chat.yml in formats uses the "{player_displayname}" alias so your plugin SHOULD be able to see the display name... but if somehow set this to reset on reconnect of the user somehow, this could be the issue as well.

**Comment by kangarko** [comment]
I am sorry for the delay here, unfortunately I am running out of options. I can see you're running a bunch of plugins that use nicks such as Essentials and CMI, would you please do a test for me and create a copy of your server without these plugins installed to see if the problem persists? Or just copy ChatControl Red to a local test server with NO other plugins to see if the nick still gets reset...

**Comment by mrcoffee1026** [comment]
Without those plugins... there is no /nick command or ability to set a nick... so sure it keeps the users "username" always but only because there's no method of setting a displayname to anything else without those plugins.

**Comment by mrcoffee1026** [comment]
Further information:
CMI doesn't even use {player_displayname}, I have to switch to using the {cmi_user_nickname} to get the nickname set by cmi to display in format... and this gets reset on reconnect also.  Taking CMI off the server and running essentials instead, I can go back to using {player_displayname}... but it gets reset upon restart.  The common factor for both is ChatControlRed.  I've had all three plugins cooperate together nicely when it was the old ChatControl Pro.  Only major change since then has been ChatControlRed and if you look in the thread above, I'm not the only person experiencing this.

Also, shouldn't the usermap file be storing nicknames?

**Comment by mrcoffee1026** [comment]
```
Tag:
  Apply_On:
  - 'prefix'
#  - 'nick'
```
This fixes it (commenting - 'nick').
Thanks so much for the help on this!

**Comment by kangarko** [comment]
Sorry that this took that long! I have thought about this incompatibility and despite you having fixed this issue, I put a note and will sort this out internally in ChatControl. Will keep you updated.
