### ISSUE TITLE
Why `/chc inspect` should be removed (or atleast get limited to console only)

### ISSUE THREAD

**Issue by itaquito** [kangarko/ChatControl#1118]
Hey! I recently noticed this command's existence, while this is useful when debugging and developing a server/plugin. It is surely a big security risk.

Edit: Stripped out possible use cases of the `/chc inspect` command, to limit possible misuse in older versions of the plugin. We have added this feature years ago **due to requests from customers about wanting to debug their javascript placeholders**. This command has been removed from ChatControl Pro and ChatControl Red within a week of this report.

**Comment by MrDienns** [comment]
This "feature" should be removed entirely. It's probably the biggest security risk I've ever seen in a (non malicious) Minecraft plugin. I can't even begin to list the risks; if anyone gets this permission, one way or the other, they would get access to **everything** the server has access to, including database connections and confidential fields. Personal information of potentially millions of users (seeing how many people use this plugin) are at risk because of this ridiculous "feature", that likely nobody asked for.

**Comment by broken1arrow** [comment]
Has not use this before and only heard about this but newer use it.

And I agree, this tool feels like more like debug tool, an something some shall be part of released plugin. I has hard to see the use of this tool. I mean you cant edit files with it, only show files and classes in other plugins. You can block this command so no one can use it (but that not solve hole issue).

**Comment by UserDerezzed** [comment]
Wow. I never knew that this was implemented in ChatControl. This ABSOLUTELY needs to be removed.

**Comment by TheIntolerant** [comment]
Just a note is possible to make this command console only (regardless of OP status).
You just need to double-check the ``Command_Aliases`` in settings, so the command is 100% blocked, by covering all possibe aliases.

For Example, if my command aliases look like
``Command_Aliases: [chc, cpp, chatc]``

The rule to block such commands should look as follows:
```
match ^\/((chc|cpp|chatc) (inspect))\b
then warn &cThis command cannot be used in-game!
dont verbose
then deny
```
^^ just put that in your command.rs file and the command will soon become console only, regardless of the permissions a user has.

**Comment by ElBananaa** [comment]
Hey!
I completely agree with you, this feature currently represents a true security risk for servers, however, I believe if this feature is here, there's a reason. If this is the case, I believe removing it wouldn't be the best thing to do, so I have a suggestion instead. In the debug part of the settings file, adding an `inspector` section, which, if enabled, will enable the inspect feature. It would still allow the plugin to integrate this feature, while it would also prevent any security issue.

**Comment by kangarko** [comment]
This feature has been implemented years ago due to some requests regarding debugging on the fly when creating JavaScript variables. People use these variables to hook into our plugin's or another plugins' classes and call their methods, hence we added an easy way for people to discover what they can use without having to use a third party decompiler each time.

Having reviewed these security concerns, I made it disabled in the plugin's source code. Same goes for ChatControl Pro. Thanks for your feedback. If people still request it we can make it toggleable through settings.yml as Banana suggested.

**Comment by kangarko** [comment]
Just to clear up some misinformation, I was banned on Spigot for advertising ChatControl which we were not allowed to sell there and moved to MCMarket, NOT because of this security hole in the plugin. 

Hence we edited Overview pages to state that we abandoned the plugin, which I was unable to change after moving to MCMarket and getting banned overnight without notice.
