### ISSUE TITLE
1.16.5: About /chc reload and Discord Chat appear some problems

### ISSUE THREAD

**Issue by MusicTW** [kangarko/ChatControl#1119]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6720939/debug.zip)

![image](https://user-images.githubusercontent.com/52475422/123531066-eaf28b80-d733-11eb-8c0f-3158a5b91aa8.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6720939/debug.zip)
> 
> ![image](https://user-images.githubusercontent.com/52475422/123531066-eaf28b80-d733-11eb-8c0f-3158a5b91aa8.png)

Hey!
Thanks for reporting this, and sorry for the delay.
I believe this is due to the fact that CHC-Red gives each chat message a unique ID (which is useful for the remove feature). However, when reloading the plugin, the id is completely apparent in discord, because for a short amount of time, the plugin is reloading. I don't know if there's anything Kangarko could do about it, and tbho, I don't think so, but I'd suggest avoiding any reload (even a plugin reload) on a prod server.

I'll leave this issue open so Kangarko could review it as soon as he gets back, in a few days :)

**Comment by kangarko** [comment]
Unfortunately we're not able to fix this at the moment for technical reasons, this invisible tag gets uncovered on reload but it should never appear in the game. Probably DiscordSRV takes over a few seconds during our reload printing this, there's little I can do about it at the moment I apology.
