### ISSUE TITLE
1.16.5 Chatting through multiple messages

### ISSUE THREAD

**Issue by Cat956** [kangarko/ChatControl#1122]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Is it possible to "hold" messages with a particular suffix until the message is complete? 
For example, any message ending in a hyphen would not send immediately, but would wait until a message is sent without a hypen.

E.g 
This is the first message-
This is the second message-
This is the third message.

Once the third message is sent, all three would send at once. I was curious to know whether it is possible.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Is it possible to "hold" messages with a particular suffix until the message is complete?
> For example, any message ending in a hyphen would not send immediately, but would wait until a message is sent without a hypen.
> 
> E.g
> This is the first message-
> This is the second message-
> This is the third message.
> 
> Once the third message is sent, all three would send at once. I was curious to know whether it is possible.

Hey!
I don't think there's a such feature in the plugin right now. I guess this could be achieved using the rules system, however, I don't really have an idea about how you could make it work.
In my opinion, this can truly be useful, would definitely love to see a feature like this one (and I truly think this would be a pretty nice feature to add to the plugin's features list). However, If I could make a suggestion, if this ever gets added, I think people would need a specific permission to get this working (Because some ppl could abuse this feature to spam).

**Comment by kangarko** [comment]
I apology but due to limited time we're not planning on adding this right now.
