### ISSUE TITLE
1.16.5: /nick Alias for /tag nick doesn't respect chat colors

### ISSUE THREAD

**Issue by UserDerezzed** [kangarko/ChatControl#1137]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Running:
<img width="237" alt="Screen Shot 2021-07-05 at 8 57 38 PM" src="https://user-images.githubusercontent.com/25561419/124540140-a457fd80-ddd3-11eb-986d-88056b8483b4.png">
Results in:
<img width="212" alt="Screen Shot 2021-07-05 at 8 55 53 PM" src="https://user-images.githubusercontent.com/25561419/124540151-acb03880-ddd3-11eb-9c6c-1ba87ca0959f.png">

However, running the alias:
<img width="171" alt="Screen Shot 2021-07-05 at 8 57 11 PM" src="https://user-images.githubusercontent.com/25561419/124540172-b2a61980-ddd3-11eb-9a2b-898d6f3b09de.png">
Results in:
<img width="163" alt="Screen Shot 2021-07-05 at 8 56 00 PM" src="https://user-images.githubusercontent.com/25561419/124540183-b8036400-ddd3-11eb-879b-7274b03faef0.png">

This is using the default /nick command found in rules/command.rs:
```
# -----------------------------------------------------------------------------------------------
# Create a /nick command that executes a longer /tag nick command.
# -----------------------------------------------------------------------------------------------

# Create a simple alias for /tag nick to just type /nick instead, using two rules.
# This rule only sends the usage message, and the rule below actually forwards the command.
match ^\/nick$
require perm nick.set.own &cInsufficient permission ({permission}).
then warn &cDescription: Sets your own nickname.
then warn &cUsage: /nick <nick/off>
then deny

# An example used for /nick command alias with the help of group matching (see the $2), it will
# replace what players type in /nick - that is pulled from the (.*) part
match ^\/nick (.*)
require perm nick.set.own &cInsufficient permission ({permission}).
then command tag nick $1
then deny
```

**Comment by TheIntolerant** [comment]
This is intended behavior due to ``Rules.Strip_Colors`` inside the ``settings.yml`` file, is set to true meaning all colour codes are removed in rules. Thus why it does not work for the /nick rule

You have two solutions to this problem:

-------------------------

1) set ``Rules.Strip_Colors`` to false
Make sure to note this if you decide to set it to false
```
  # Remove colors from checked messages? Prevents bypasing filters by using colors: fu&cck.
  # [WARNING] This will remove all custom colors in the message in case it is filtered!
  # TURNING THIS OFF can break packet rules and make players able to bypass rules by using colors.
```
  
-------------------------

2) Use an alternative method of creating an alias.
You can do this by editing the ``commands.yml`` file, in the main directory of your server.
If you haven't edited this before it should look something like
```yml
command-block-overrides: []
ignore-vanilla-permissions: false
aliases:
  icanhasbukkit:
  - version $1-
```
to add ``/nick`` just edit the above so it looks like this:
```yml
command-block-overrides: []
ignore-vanilla-permissions: false
aliases:
  icanhasbukkit:
  - version $1-
  nick:
  - tag nick $1-
```

**Comment by UserDerezzed** [comment]
Ah, I see. Seems like the commands.yml alias is the best choice for me. Thanks!
