### ISSUE TITLE
Add an option to disable the spy bypass reminder

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl#116]
Hey!

I just noticed this message on my test server, and I must say that it can be a bit annoying.
```
[ChatControlRed] Note: Not sending ElBananaa's chat to spying players because he had 'chatcontrol.bypass.spy' permission. Player messages with such permission are not spied on. To disable that, give him this permission as negative (a false value if using LuckPerms). This message only shows once per 60 minutes.
```
It would be cool if there's an option to disable this message.

**Comment by c0wg0d** [comment]
I agree.  I'd prefer it not show at all.  It's useful when you are just setting up the plugin, but once you have it configured and know what you are doing, it's annoying to see it every time your moderators join the game.

**Comment by kangarko** [comment]
Thanks, will add a toggle for it. Remember we're a private beta so keeping additional logs was essentials, especially when dealing with issues. Next version comes with a toggle.

**Comment by tjrgg** [comment]
There should be a toggle or localization for similar messages as well.

e.g.
`TIP: Automatically joining tjrgg to channel 'standard' in write mode because he had 'chatcontrol.channel.autojoin.standard.write' permission. We will not join him again when he leaves that  channel manually. To stop automatically joining players into channels, give them negative 'chatcontrol.channel.autojoin.*' permission (a value of false when using LuckPerms). This message only shows once per 3 hours.`

**Comment by kangarko** [comment]
Not sure if the public version has it, but there is going to be "Show_Tips" option in settings.yml to hide these.
