### ISSUE TITLE
1.17.1 : Performance problem

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#1193]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

![image](https://user-images.githubusercontent.com/66686400/127707339-9dec998f-475a-4a7a-8fc3-47b3bb6af66b.png)
https://timings.aikar.co/?id=02eb0db18f794dadbcc7198e8cb10537#plugins

what can i do about it?

**Comment by ttt0** [comment]
![image](https://user-images.githubusercontent.com/66686400/127769504-340764c0-2f64-4a8f-b8c7-966175079fdc.png)
Why is no one helping??

**Comment by TheIntolerant** [comment]
Chances are the people who have seen this ticket are unsure of how they can assist you due to lack of knowledge. In which case you will need to wait for the plugin developer to respond to this issue.

**Comment by ElBananaa** [comment]
As gone-incognito said, we can't really do much about it. The only suggestion I could give you is enabling channels async mode `Channels.Async` and setting messages async mode `Messages.Async` to `Async: [join, quit, kick, death, timed]`. While this won't really help in your case since the performance issue you reported is apparently mainly caused tab completion (which are pretty heavy, no matter the plugin, afaik), it'll def help improve the plugin's performances.

Now, I can only suggest to wait for Kangarko.
Someone else also reported another performance issue regarding the onToolClick event on #1183, so make sure to keep an eye there until Kangarko gives you both an answer ^^

**Comment by kangarko** [comment]
Thanks to Banana for a reply. Please add the optimization tricks outlined here: https://github.com/kangarko/ChatControl-Red/wiki/Performance

Also the next version will have tools disabled by default which brings another performance boost.

**Comment by ttt0** [comment]
![image](https://user-images.githubusercontent.com/66686400/129890281-ab6eae4b-4d3b-419a-935f-bef076a72df8.png)
I did what you said but it's still like this
https://timings.aikar.co/?id=dadaf1ca3a914dba8139bc11b7027491#plugins
@kangarko @ElBananaa

**Comment by ElBananaa** [comment]
> ![image](https://user-images.githubusercontent.com/66686400/129890281-ab6eae4b-4d3b-419a-935f-bef076a72df8.png)
> I did what you said but it's still like this
> https://timings.aikar.co/?id=dadaf1ca3a914dba8139bc11b7027491#plugins
> @kangarko @ElBananaa

Hey!
According to your timings, the plugin "performance issue" is mainly related to tab-completion, however, the main issue here isn't the plugin, I guess:
![image](https://user-images.githubusercontent.com/53318613/130253892-3f916e57-51cb-4950-9d77-43dbcce7f45a.png)
I'd suggest following advices given in this guide to help improving the global performances : https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/

Also, could you provide us a spark profiler output? (https://www.spigotmc.org/resources/spark.57242/ & https://spark.lucko.me/docs/Command-Usage). I guess it'll be more helpful to find real performance issues with the plugin than a timings output.

Finally, I can only suggest upgrading your server/switching to a dedicated server (if that's not already done), especially with a high playercount like your server, because latest versions aren't known to be really well optimized.

**Comment by kangarko** [comment]
Thanks to Banana for replying! Or eventually you can set Tab_Complete.Enabled to false in settings.yml to completely disable our tab completing feature. 

Here are some causes of this performance drain:

- We need to find the player each time you tab complete, the more players the longer it takes
- If you use nicks, we also need to look up the players nick, which takes extra time
- We also ask Essentials or CMI if the player is vanished and remove if they are not, so it may also be the other vanish-management plugin
