### ISSUE TITLE
Minecraft Version: 1.17.1 Trying To Change /chc announce Headers

### ISSUE THREAD

**Issue by dbdevc** [kangarko/ChatControl#1200]
Hello,
When I use /chc announce chat MESSAGE, I get I (bungee ? 'NETWORK) + 'ANNOUNCEMENT' ! on top of the chat. I've tried to modify this Header under messages_en.yml. All I want is a simple text to stand there, eg &6Test Server Announcement. ı've tried modifying the ternary operator, modifying the text, and 10+ different variations. 
Thanks!

Minecraft Version: 1.X.Z
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> Hello,
> When I use /chc announce chat MESSAGE, I get I (bungee ? 'NETWORK) + 'ANNOUNCEMENT' ! on top of the chat. I've tried to modify this Header under messages_en.yml. All I want is a simple text to stand there, eg &6Test Server Announcement. ı've tried modifying the ternary operator, modifying the text, and 10+ different variations.
> Thanks!
> 
> Minecraft Version: 1.X.Z
> MySQL: false
> BungeeCord: false

Hey,
Please provide us your lang file or the entire `/chc debug` file.

**Comment by dbdevc** [comment]
Hey, thanks for your reply. Here is our debug file: https://ufile.io/c3xxur0t

**Comment by ElBananaa** [comment]
> Hey, thanks for your reply. Here is our debug file: https://ufile.io/c3xxur0t

Awesome, thanks!
So, it looks like you're using an outdated version of the plugin, please updated to the latest version available on mcmarket.
Also, since you are using java 16, you need to install NashornPlus (https://mineacademy.org/nashorn/).
Once both things said above are done, in your localization file, look for `Type: '(bungee ? ''NETWORK '' : '''') + ''ANNOUNCEMENT'''` (line 183), and simply replace it with `Type: '&6Test Server Announcement'` and everythign should work perfectly! :)

**Comment by dbdevc** [comment]
Thanks! Worked just as I needed!
