### ISSUE TITLE
1.17.1:How to disable advertising for general grammar without removing it from actual advertising 

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl#1207]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

https://i.imgur.com/2Tz7Soa.png
This image above is the issue i'm having , 
Whenever the , and or - are alone or mixed together it triggers the advertising filter. 

However removing , and - from the match for advertising is not ideal. Is there a way to allow players to use their grammar without having it affect the advertising filter ?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.17.1
> MySQL: true
> BungeeCord: true
> 
> https://i.imgur.com/2Tz7Soa.png
> This image above is the issue i'm having ,
> Whenever the , and or - are alone or mixed together it triggers the advertising filter.
> 
> However removing , and - from the match for advertising is not ideal. Is there a way to allow players to use their grammar without having it affect the advertising filter ?

Hey!
A such issue shouldn't happen with the default files. Could you please provide us your `/chc debug` file?

**Comment by TheIntolerant** [comment]
I can confirm this does indeed happen with the default files. This is relatively easy to fix however using a "negative lookbehide" in the RegEx for advertising.

![541515](https://user-images.githubusercontent.com/48093184/128591933-70015261-9e8f-4aef-8269-be4670bb32d4.JPG)

For me, I noticed I got most of the false positives from ``co`` or ``me`` domains, I edited the regex for those. Adding something like 
``(?<!, |-)``
which should stop this from happening

So, for example, say your original advertising rule looked like.
``[a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b``
and I wanted to stop it matching for 
``is, co-ords``
OR
``questions, me``

As this RegEx, thinks you are using a ``example.co`` and ``example.me`` domain, we just look at the part of the RegEx for those domains and add ``(?<!, |-)``, so that whenever a comma and/or a hyphen are alone or mixed together it no longer triggers the advertising filter.

In which case the above would look like this following those changes
``[a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|(?<!, |-)c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|(?<!, |-)m(| +)e|i(| +)o)\b``

-----

As shown here, this change means ``, `` or ``- `` no longer trigger the advertising filter only if  a ``co`` or ``me``
comes after the comma or hyphen, as I added a space after the comma in ``(?<!, |-)`` this also means the advertising filter still gets triggered if someone were to type ``example,me`` but if they typed ``example, me`` it won't get triggered.

![image](https://user-images.githubusercontent.com/48093184/128592785-e299ffc1-284e-47ae-8519-22d2dd13c5a1.png)

This should fix this issue!

**Comment by SecretarySami** [comment]
> I can confirm this does indeed happen with the default files. This is relatively easy to fix however using a "negative lookbehide" in the RegEx for advertising.
> 
> ![541515](https://user-images.githubusercontent.com/48093184/128591933-70015261-9e8f-4aef-8269-be4670bb32d4.JPG)
> 
> For me, I noticed I got most of the false positives from `co` or `me` domains, I edited the regex for those. Adding something like
> `(?<!, |-)`
> which should stop this from happening
> 
> So, for example, say your original advertising rule looked like.
> `[a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b`
> and I wanted to stop it matching for
> `is, co-ords`
> OR
> `questions, me`
> 
> As this RegEx, thinks you are using a `example.co` and `example.me` domain, we just look at the part of the RegEx for those domains and add `(?<!, |-)`, so that whenever a comma and/or a hyphen are alone or mixed together it no longer triggers the advertising filter.
> 
> In which case the above would look like this following those changes
> `[a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|(?<!, |-)c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|(?<!, |-)m(| +)e|i(| +)o)\b`
> 
> As shown here, this change means `, ` or `- ` no longer trigger the advertising filter only if a `co` or `me`
> comes after the comma or hyphen, as I added a space after the comma in `(?<!, |-)` this also means the advertising filter still gets triggered if someone were to type `example,me` but if they typed `example, me` it won't get triggered.
> 
> ![image](https://user-images.githubusercontent.com/48093184/128592785-e299ffc1-284e-47ae-8519-22d2dd13c5a1.png)
> 
> This should fix this issue!

im sorry its almost 2am for me, but this is in the global.rs config for the domain/url filter correct ?

**Comment by SecretarySami** [comment]
# Domain/URL filter.
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b

which would be this one ?

**Comment by TheIntolerant** [comment]
> **Domain/URL filter.**
> 
> match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b
> 
> which would be this one ?

Yes, that is the one. So basically just add ``(?<!, |-)`` into that for the "co" and "me" domains

**Comment by TheIntolerant** [comment]
I'm not at my computer right now, but it should be something like ``c(| +)o`` and ``m(| +)e`` and they just need to be edited so it looks like

``(?<!, |-)c(| +)o`` and ``(?<!, |-)m(| +)e``

Within that regex you posted above in the global.rs file

Just make sure your not applying these changes to the com domains etc

**Comment by TheIntolerant** [comment]
Unless you edited the original rule, it should be something like
```
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|(?<!, |-)c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|(?<!, |-)m(| +)e|i(| +)o)\b
```

**Comment by SecretarySami** [comment]
match [a-zA-Z0-9-.]+\s?(.|dot|(dot)|-|;|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|(?<!, |-)c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|(?<!, |-)m(| +)e|i(| +)o)\b

Okay so should look like the above^ ?

And yeah we removed : from the original I believe

**Comment by TheIntolerant** [comment]
Yeah that looks good

**Comment by SecretarySami** [comment]
> Yeah that looks good

thanks so much this seems to resolve it :) I really appreciate the awesome support !
this can be closed :)

**Comment by ElBananaa** [comment]
Hey!
Thanks gone-incognito for answering this issue!
I'm closing it, but feel free to open a new one if you need anything else! :)

**Comment by SecretarySami** [comment]
@ElBananaa @gone-incognito 

Apparently this started to filter a ton more false positives and caused a lot of our commands to be advertised

**Comment by TheIntolerant** [comment]
Could you provide more information? And possibly also do "/chc debug", thanks

**Comment by kangarko** [comment]
@SecretarySami you can just remove this letter from the filter:

![https://i.imgur.com/ZMrjslu.png](https://i.imgur.com/ZMrjslu.png)

This is the new filter you can use:

`match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b`

**Comment by SecretarySami** [comment]
sorry it took so long to look at this and give it a try, have been super busy, as i assume you guys are busy too ! 
However , when applying the above as the domain/URL filter match, it still catches commands like /home as an advert 
The command /home is an alias for is /cmi home 
if that helps at all >-<

https://youtu.be/LXM0cCjnC8M
I took a quick video, the first time trying it is with the current one i have -
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b

The second time trying it was with the one kangarko had provided

**Comment by TheIntolerant** [comment]
Use the rule I suggested in the recent update as shown in the change logs in
https://www.mc-market.org/resources/18217/updates

This is the rule
``match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|(?<! )c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|(?<! )m(| +)e|i(| +)o)\b``

if you don't want ``:`` then you should be able to remove that from the above without causing any issues.

---

**Explaining the issue**

Basically, the issue is being caused because of ``.`` in the ``(.|dot|(dot)|-|;|,)`` section of the rule. It should of been ``(\.|dot|(dot)|-|;|,)``

Because of the  ``.`` in the advertising rule and it not having a ``\`` in front of it, it matches any single character, in a way it is treating it as if you typed, ``h.me`` but since ``.`` matches any character the ``o`` triggers the match in this case when typing ``/home``.

Hopefully, that explains why this was happening and the rule change I suggested above should completely stop this from happening. Hope this helps.
