### ISSUE TITLE
1.16.5 Factions problem

### ISSUE THREAD

**Issue by DotDotas** [kangarko/ChatControl#1239]
Im having problems with chat format and factions. Factions tag doesn't appear next to the name in chat.
I tried to change Chat_Listener_Priority from Highest to Lowest but it didn't worked. Any solutions?
Also im getting no errors or warnings. And im using FactionsUUID.
Minecraft Version: 1.16.5 Paper 786 Build
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> Im having problems with chat format and factions. Factions tag doesn't appear next to the name in chat.
> I tried to change Chat_Listener_Priority from Highest to Lowest but it didn't worked. Any solutions?
> Also im getting no errors or warnings. And im using FactionsUUID.
> Minecraft Version: 1.16.5 Paper 786 Build
> MySQL: false
> BungeeCord: false

Hey!
In order to display a user's faction in the chat, you must use the faction placeholder in our format system.
According to FactionsUUID wiki page (https://factions.support/placeholderapi/), the PAPI placeholder for the faction name is `%factionsuuid_faction_name%` so try placing `{factionsuuid_faction_name}` in your format file, and it should work.

**Comment by DotDotas** [comment]
Yes, i tried this solution too but there's a problem. Somehow all faction tags stays white.
![image](https://user-images.githubusercontent.com/87330727/129496525-7ac1ee50-b0ed-4f69-92aa-d22773608bf6.png)

**Comment by ElBananaa** [comment]
> Yes, i tried this solution too but there's a problem. Somehow all faction tags stays white.
> ![image](https://user-images.githubusercontent.com/87330727/129496525-7ac1ee50-b0ed-4f69-92aa-d22773608bf6.png)

Well, I suggest taking a look at the link I provided in my previous message and then using one of their color placeholder before the `{factionsuuid_faction_name}` placeholder (so either `{rel_factionsuuid_relation_color}` or `{factionsuuid_faction_relation_color}`).
The 2nd one may be the right one, since, I think, we don't (fully) support relational placeholders

**Comment by DotDotas** [comment]
Okay, this one worked {factionsuuid_faction_relation_color} but now it doesn't show my faction rank in chat only my factions name.
![image](https://user-images.githubusercontent.com/87330727/129535109-15eebc22-e0d1-4439-bdc6-44e57ae1fb96.png)
It should be ***alt5

**Comment by ElBananaa** [comment]
> Okay, this one worked {factionsuuid_faction_relation_color} but now it doesn't show my faction rank in chat only my factions name.
> ![image](https://user-images.githubusercontent.com/87330727/129535109-15eebc22-e0d1-4439-bdc6-44e57ae1fb96.png)
> It should be ***alt5
Hey!
Once again, take a look at the page I provided, all you need can be found there.

**Comment by DotDotas** [comment]
ohh, sorry, I didn't saw {factionsuuid_player_role} at first. All good now.
