### ISSUE TITLE
Users can advertise usign signs

### ISSUE THREAD

**Issue by Alexre** [kangarko/ChatControl#125]
I configured the rules.txt because there are users in my server spamming servers, all was good, but now, they spam like this

New server server·com 

They use the sign "·" and the antiad doesn't detect it 

Thanks, I need to solve it :(

**Comment by EvilOlaf** [comment]
Just expand the adversiting rule with this symbol. Like this:

```
# IP filter. 
# (Notice the operator strip which removes specified characters BEFORE the message is checked.)
match \b[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|·|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}\b
id 1
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]
handle as advertisement
```

I added it after `-|;|:|,|`

**Comment by kangarko** [comment]
Quite frankly there is no such thing as an ultimate non-bypassable solution, because it's only a machine. You'll have to adjust the filters, for example as said above. I recommend to read the ad logs regularly because users tend to try to advertise in the correct format first, and after they find out that it's blocked, they keep changing the message's format, so you can improve the filters from there.
