### ISSUE TITLE
1.17.1: All nicknames have been reset

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#1272]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

After updating to the latest beta, it seems all nicknames have been reset..

[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/7037502/debug.1.zip)

**Comment by kangarko** [comment]
I am sorry, upgrader seems not to work, going to fix this asap in the next 24-48 hours

**Comment by kangarko** [comment]
Okay since you are using a mysql database this should not happen, but we removed the UUID_Lookup option from mysql.yml that may have caused this. Do you remember if you had this on true or false? If you had this on true it is now automatically set to false for offline mode servers (including under bungee) that may have caused this reset

**Comment by Sikatsu** [comment]
I am not entirely sure, it could very well be this was set to true..

**Comment by kangarko** [comment]
Okay, I will readd the option back so that you will be able to select whether to store mysql/data.db entries by username or UUID manually. I am a bit busy preparing some ad campaigns for Friday but I'll aim to find the time asap

**Comment by Sikatsu** [comment]
Alright, but I don't think I should toggle this as it will reset it again? Think it's better that everyone just sets his nickname again, but yeah..

**Comment by kangarko** [comment]
Great, sorry for the delay, okay just know that the next version will have UUID_Lookup option set to true which will reset it again since now it effectivelly was on false given your server is "offline". So when installing the next version I recommend you place "UUID_Lookup: false" line at the end of your settings.yml file before updating to ensure there is no data cleanup again. Best yet, just test this on a local test server.

**Comment by Sikatsu** [comment]
I added UUID_Lookup: false before I updated, yet some people still lost their nicknames and even their chat colors.

And in other plugins my nickname shows as this:
![image](https://user-images.githubusercontent.com/5664135/131405914-b7702659-f31f-4e3c-9612-96de36ead4ac.png)
While in adminchat: 
![image](https://user-images.githubusercontent.com/5664135/131405989-f2430d5e-dbba-4d74-9e9d-f15efd5877c4.png)

Was there anything changed other then this?

**Comment by kangarko** [comment]
I am not sure but we rewrote user data saving twice in the last recent two versions, the latest one is the most preferred one with the re-added option to select UUIDs/username storage method manually.

Likely the other plugin won't support HEX color tags. Try {#123456}, we do support that also.

**Comment by Sikatsu** [comment]
Apparently that issue solved itself.

However, with UUID_Lookup on true some players still seem to get reset now and then. This does not affect everyone.

Players that get reset do not only lose their nickname, but also lose all their other chatcontrol settings like the chatcolor.

Once you have some time, could you look into this specific issue?

**Comment by kangarko** [comment]
In this case it looks like the UUID has been changed. Since your server is offline, this will happen when the UUID change. I heard they generate random UUIDs for every player in offline mode, I am unsure how this mechanism works - how long the randomly generated ids are persistent. If they get reset, then the player will loose all of his data.

**Comment by Sikatsu** [comment]
Well, but I would like for this issue to be solved as it is a recent change in ChatControl or BungeeControl that is causing it..
We've been dealing with players being reset both their nickname and their chat color for the past weeks.
Today when I logged in (and also yesterday) I also lost my nickname and chat color again.

Could this be reopened, so we can investigate the issue further?

**Comment by kangarko** [comment]
I'm investigating this right now and will continue on #1292, apologies for the frustrations.
