### ISSUE TITLE
1.17.1: '&' colour code in json message not working anymore

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#1284]
Randomly with one of the previous updates, `&` colour codes in json messages just stopped working. There is a workaround for now with using the `§` so I'm temporarily using that until the & symbol is readded. 

`CHC 10.5.1` running on `Paper-196`

Minecraft Version: `1.17.1`

**Comment by kangarko** [comment]
Going to test tomorrow, please drop me an example of a broken JSON if you can and I will test with your setup.

**Comment by kangarko** [comment]
Found this. I now remember that we disabled colorizing JSON messages in files because they ignored the respective permissions players had (we use one method for sending JSON messages which is called also for permission-specific messages). In other words, just keep using § and it will continue to work.
