### ISSUE TITLE
[Feature Request] Chat replay on join 

### ISSUE THREAD

**Issue by MrMcyeet** [kangarko/ChatControl#1286]
1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
  It would give players joining your server an idea of what is going on

2. What would happen if we won't implement this feature? How's your server being affected?
  There would be no negative outcome from this not being added, but it is a cool feature idea.

My suggestion is this: Have the plugin save messages that are sent _(Which I think it already does, so that it can replay the messages after an admin removes one)_ then when a player joins, have the plugin send messages that that player would have been able to see _(i.e. messages from channels that they are in)_
This would allow the player to get a sense of what is going on in the server.
It should have the number of messages that it replays be configurable, and it should have a config option to replay all messages _(including system/plugin messages)_ or just player messages

**Comment by kangarko** [comment]
It is easier said than done, because there are dozens of conditions which messages the player may see/may not see, we are not able to calculate them while the player is offline (such as: can they see a ranged chat from a local channel? What about other channel settings?)

As such this is technically not feasible to do for a chat plugin of our size. For a simple chat plugin where everyone can see each others messages, yes, sure, but not here, sorry.
