### ISSUE TITLE
1.17.1 paper: Staff's messages are showing up as invisible

### ISSUE THREAD

**Issue by CrispyDairy** [kangarko/ChatControl#1300]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

Whenever one of my staff tries to send a message to staff chat, it just shows up as a blank like. It works just fine with my messages, and they can see my messages.

The blank lines in chat are them trying to speak.
![image](https://user-images.githubusercontent.com/81482501/131893862-da62c52e-0e84-4998-8598-91cf79fd7859.png)

**Comment by TheIntolerant** [comment]
Can you upload your ``/chc debug`` file here please, thanks.

**Comment by CrispyDairy** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7109777/debug.zip)

**Comment by TheIntolerant** [comment]
After looking through your debug file, I see this is most likely being caused by
``Sender_Permission: my.rank.ingame`` in ``plugins/ChatControlRed/formats/admin-chat.yml``

As shown here.
![image](https://user-images.githubusercontent.com/48093184/132114271-4f344297-5dcb-4356-8ed0-002cd0ff140b.png)
If the user is not sending a message from discord as well as lacking the permission ``my.rank.ingame``, when trying to send a message in the admin channel it will show up as a blank line, as they do not meet any of the conditions for any of the "parts" in the formatting file.

This can be fixed by either changing the **Sender_Permission: my.rank.ingame** to 

**Sender_Condition: {sender_is_player}**

or

just giving staff the permission "my.rank.ingame"

**Comment by CrispyDairy** [comment]
Oh thanks! That did it <3
