### ISSUE TITLE
1.17.1: mysql and cross message doesn't work

### ISSUE THREAD

**Issue by bcorleone** [kangarko/ChatControl#1303]
hi 

before i was with the version pay chatcontrol now im on the version chatcontrol red with this version i don't know why but the transfer messages with bungeecord doesn't work can you help me.

i have another problem with the join and quit message, i have the quit and join message every time when i switch server

maybe my configuration is not correct because chatcontrol won't create the data base on mysql

do you have some idea of my problem ?

![chatcontrole1](https://user-images.githubusercontent.com/75180208/132090313-87d82d5e-0f8e-404d-b7c7-55f41908de49.PNG)

my files: https://ufile.io/mh0axp2w
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey,
Please provide us the full latest.log file.

**Comment by bcorleone** [comment]
hy yes sure

[latest.log](https://github.com/kangarko/ChatControl-Red/files/7111561/latest.log)

**Comment by ElBananaa** [comment]
Hey,
Thanks!

So according to your log file, your mysql driver is outdated : 
```log
[14:17:50] [Server thread/INFO]: You need to update your MySQL provider driver. We switched to support unicode using 4 bits length because the previous system only supported 3 bits.
[14:17:50] [Server thread/INFO]: Some characters such as smiley or Chinese are stored in 4 bits so they would crash the 3-bit database leading to more problems. Most hosting providers have now widely adopted the utf8mb4_unicode_520_ci encoding you seem lacking. Disable MySQL connection or update your driver to fix this.
```

So, in order to fix your issue, as said in the message, you need to update the driver. To do, if you're using a host, contact their support and ask them to update their mysql/mariadb driver to the latest stable version available. If you're using a VPS or a dedicated server, then take a look at tutorials about how to update mysql according to your OS.
(I'd suggest taking a look at digitalocean's tutorials if you're using a linux-based os)

**Comment by bcorleone** [comment]
hy,

ok ok i ask my host and they update their mysqk the end of the year so i just need to wait thank you for your help

**Comment by ElBananaa** [comment]
Alright, thanks for the update!
I'm closing the issue, but feel free to open a new one if you need anything else.
