### ISSUE TITLE
1.17.1: Does Forward_From_Bungee only work when there's a player on the server with DiscordSRV installed?

### ISSUE THREAD

**Issue by n-aspen** [kangarko/ChatControl#1318]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

I'm trying to setup the DiscordSRV integration on a Bungee network with two linked servers but it seems like messages aren't forwarded from the server without DiscordSRV unless there is a player on the server with DiscordSRV installed. I'm not sure if this is a DiscordSRV limitation or a ChatControl limitation, but I did find what looks like the same issue in the DiscordSRV config for VentureChat.
```
VentureChatBungee: enables the VentureChat hook's BungeeCord functionality (messages are received from every server, requires atleast 1 player to be online)
```
The main cause for my confusion is that I don't see it mentioned anywhere in the ChatControl docs about discord.

**Comment by ElBananaa** [comment]
Hey!
I believe messages are only forwarded to servers with at least 1 online player.
I don't think this is a limitation on DiscordSRV side tho, but rather on the game itself, but I don't think it's an issue at all.

Is there anything else you'd like to know, or may I close this issue?

**Comment by n-aspen** [comment]
Ah got it, that's fair enough. Assuming there's no way to force the messages to make it to DiscordSRV on that server, that's all I needed to know <3

**Comment by ElBananaa** [comment]
Alright!
I'm closing this issue. Feel free to open a new one if you need anything else! 😃

**Comment by NoobcoreNetwork** [comment]
Might be a silly question but I have 8 servers, and have discordSRV installed on 1 with 
    Forward_From_Bungee: true
    
The server with discordSRV is my lobby server, However requires someone to be in the lobby at all times for it to work, This isn't really ideal, I could put it on my survival server which is more likely to have someone on, but still if theres people in creative and not in survival, I won't be able to talk to them from discord (Because nobodys in survival so it can't connect through it)

Is there anyway around this? I did have discordSRV on every server but struggled with messages repeating sometimes twice, sometimes 4 times, and sometimes it worked fine.

Thanks!

**Comment by ElBananaa** [comment]
> Might be a silly question but I have 8 servers, and have discordSRV installed on 1 with
> Forward_From_Bungee: true
> 
> The server with discordSRV is my lobby server, However requires someone to be in the lobby at all times for it to work, This isn't really ideal, I could put it on my survival server which is more likely to have someone on, but still if theres people in creative and not in survival, I won't be able to talk to them from discord (Because nobodys in survival so it can't connect through it)
> 
> Is there anyway around this? I did have discordSRV on every server but struggled with messages repeating sometimes twice, sometimes 4 times, and sometimes it worked fine.
> 
> Thanks!

Messages aren't supposed to be sent to servers with no players online, however, in this scenario, this isn't an intended behavior.
I'd suggest waiting for @kangarko to see if anything can be done here ^^

**Comment by NoobcoreNetwork** [comment]
Awesome thanks, I have tried putting discordSRV on all servers again but just have the doubling up of messages, even when Forward_From_Bungee: true is only set to true on 1 server like it suggests 
![Discord_9RfqydifUz](https://user-images.githubusercontent.com/62724418/134786389-8bbf27dc-b605-4db6-ac8b-17148d4e38e3.png)
![javaw_Awp1EuYOjS](https://user-images.githubusercontent.com/62724418/134786390-d6115f15-8b91-4f75-b51c-a5077782c2e9.png)

This is discordSRV installed on
Lobby/Survival/Creative/Skyblock/Prophunt/Bedwars/Spleef

But I get it coming through twice (Not all the time though) I'm wondering why twice? Why not 7 times (Number of servers) The config is identical (copy and paste) on the Discord related sections across all servers, apart from survival having Forward_From_Bungee: true I have tried all having Forward_From_Bungee: true and it's the same, and none having Forward_From_Bungee: true  and it's the same.

**Comment by NoobcoreNetwork** [comment]
So i have figured out, it shows twice if theres people on different servers aka im in lobby and they are in survival, if i go to survival, it will send once (and work correctly) because we are both in survival, 

![javaw_FlGyZEpEjO](https://user-images.githubusercontent.com/62724418/134786541-ed5d8760-703b-4a44-a2ff-edba53170045.png)
![Discord_oTPVPMGlzl](https://user-images.githubusercontent.com/62724418/134786542-aa08d1a4-ee43-447b-8c53-0ca09b8cb767.png)
![Discord_txOOtS5UsL](https://user-images.githubusercontent.com/62724418/134786543-de071e2d-9129-4689-80c2-9eab4f759076.png)
![javaw_Ev5qRnBGyE](https://user-images.githubusercontent.com/62724418/134786544-f1fb0c57-80cb-4633-8c20-3567933380ce.png)

But if there's someone on a third server it still shows twice. Not 3 times. Weird
