### ISSUE TITLE
player %player% is not online on this server.

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#1319]
player %player% is not online on this server.

![image](https://user-images.githubusercontent.com/66686400/133395913-203cea37-a9df-4b05-8eb8-a82a9c5d9e03.png)
it gives such an error even though the player is in the game
I want to remove it but I couldn't find it in settings

**Comment by ElBananaa** [comment]
> player %player% is not online on this server.
> 
> ![image](https://user-images.githubusercontent.com/66686400/133395913-203cea37-a9df-4b05-8eb8-a82a9c5d9e03.png)
> it gives such an error even though the player is in the game
> I want to remove it but I couldn't find it in settings

Hey!
Can you please provide us more informations about your setup, as requested in the default issue format?
Also please provide us your `/chc debug` file.

**Comment by ttt0** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7172860/debug.zip)

**Comment by ElBananaa** [comment]
Thanks!
It appears you are using a pretty old version of the plugin. Please update to the latest version available on mcmarket. Also remove NashornPlus since it's not needed anymore. Finally, once the plugin update is done, if your server accepts cracked players, make sure to turn `UUID_Lookup` to `false` in your settings file. If you only accept premium users, leave it to `true` It should solve your issue.

**Comment by kangarko** [comment]
If your issue persists even after you have updated, please continue at https://github.com/kangarko/ChatControl-Red/issues/1292
