### ISSUE TITLE
Placeholder ERROR

### ISSUE THREAD

**Issue by Arthuuurr** [kangarko/ChatControl#1325]
Hello, I come to ask how the placeholders are activated when you hover the mouse over the name of a person, I have tried to do it several times but it tells me that the placeholders are not enabled, can you help me?
Thanks!

**Comment by ElBananaa** [comment]
Hey,
I'm not aware of a such message in the plugin.
Could you please provide us more informations about your setup, as asked in the format (Server version, java version, plugin version, is MySQL enabled, is Bungeecord integration enabled etc)

Also, please provide us a screenshot of the message you have.

**Comment by Arthuuurr** [comment]
https://user-images.githubusercontent.com/90864573/133928240-a060e160-24de-4799-ac17-f785625aa852.png
https://user-images.githubusercontent.com/90864573/133928263-9094d824-c125-4236-8df1-2ad30a9f2517.png
https://user-images.githubusercontent.com/90864573/133928272-86f53b59-ac1a-4b05-af13-1744952cb28d.png

You didn't really understand the question I asked.
I have left some images so you can see what happens to me. What I want is that the api placeholder expansions appear, but it says that they cannot be enabled, let me know if I have expressed myself wrong

**Comment by TheIntolerant** [comment]
Personally I would suggest testing if PlaceholderAPI is working correctly, by running this command:

**/papi parse me %placeholder%**

This command may require you to use %% instead of {} which is normally used in chatcontrol.

If the above command did not work when testing the placeholder, you should check that MarriageMaster and PlaceholderAPI (and all other dependencies if there are any) are up to date.

**Comment by ElBananaa** [comment]
Hey,
I have the same thoughts than gone-incognito on this (Btw, thanks for answering 😃). It looks like for some reason, either the plugin doesn't correctly work with placeholders (which seems pretty unlikely since we've seen many people using this plugin's placeholders without isues), or placeholderapi isn't working properly.

Also, if what gone-incognito said doesn't help, would you mind providing us your `/chc debug` file and your latest.log file?

**Comment by kangarko** [comment]
Thanks to gone for answering, closing this. Let us know below if you still need more help!

**Comment by MithrandirCraft** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7225074/debug.zip)

Please reopen, I'll be taking care of this one. Arthur is one of my staff and he just left this ticket unattended.

All plugins are up to date, the placeholders simply don't work. I tested the PAPI command, it returns "Placeholder not found" when inputting ingame /papi parse me %marriagemaster_Heart%

Could this mean the placeholder doesn't exist? Maybe I should mention this to marriage master's dev.

**Comment by TheIntolerant** [comment]
I have edited the config for marriagemaster on my server but that shouldn't of changed how the placeholders works. Note, I haven't updated to 1.17 though. So unless Java 16 etc has something to do with this error, I am sort of confused as to why it isn't working.

![image](https://user-images.githubusercontent.com/48093184/134665482-627def54-d5db-497a-918c-f054110b1697.png)

It also shows up in chat via chatcontrol formating.

**Comment by ElBananaa** [comment]
Hey, the plugin also works perfectly fine for me too. (Tests were made on a fresh install with Paper 1.17 #278, Chc-red 10.6.4, PAPI 2.10.10 and MarriageMaster 2.4.2. This is a fresh install, no config changes were made.
Could you please remove NashornPlus (It's not needed anymore in your case, so you don't need it), and see if it helps. If it doesn't, I'd suggest reaching MarriageMaster's author since the error message you get is most likely not related to chc-red.
(Also, make sure you don't have errors in your latest.log, and make sure the plugin hooks correctly with placeholderapi. The messages should look like that : 
```
[18:53:21 INFO]: [PlaceholderAPI] Successfully registered expansion: marriagemaster
[18:53:21 INFO]: [MarriageMaster] PlaceholderAPI hook was successfully registered!
[18:53:21 INFO]: [MarriageMaster]  Marriage Master has been enabled!  :)
```

**Comment by MithrandirCraft** [comment]
Well aparently we were getting this warning:
![image](https://user-images.githubusercontent.com/6623704/134740393-948bb1cf-3056-4667-87aa-b690fbb5d264.png)

So we installed Nashorn because of it. Idk what those "javascript placeholders" are exactly, but I removed the plugin nevertheless.

As for plugin versions, I'm only one version behind on CHC RED, but 42 paper versions behind, so I updated all of that.

Everything running on java 16, MC 1.17.1

Anyone know if there's any relevant configs to placeholders which may affect this?

**Edit:** Updated everything, placeholders still show like this:
![imagen](https://user-images.githubusercontent.com/6623704/134743605-75762310-6ac3-4919-bf2b-26db0949695e.png)

**Comment by ElBananaa** [comment]
> Well aparently we were getting this warning:
> ![image](https://user-images.githubusercontent.com/6623704/134740393-948bb1cf-3056-4667-87aa-b690fbb5d264.png)
> 
> So we installed Nashorn because of it. Idk what those "javascript placeholders" are exactly, but I removed the plugin nevertheless.
> 
> As for plugin versions, I'm only one version behind on CHC RED, but 42 paper versions behind, so I updated all of that.
> 
> Everything running on java 16, MC 1.17.1
> 
> Anyone know if there's any relevant configs to placeholders which may affect this?
> 
> **Edit:** Updated everything, placeholders still show like this:
> ![imagen](https://user-images.githubusercontent.com/6623704/134743605-75762310-6ac3-4919-bf2b-26db0949695e.png)

That's weird. Could you please provide us your latest.log? In the meantime, try to reach MarriageMaster's author.

**Comment by MithrandirCraft** [comment]
[2021-09-24-3.log](https://github.com/kangarko/ChatControl-Red/files/7230346/2021-09-24-3.log)
Here's a log from yesterday including startup, since the one for today got cut off at 12.

It is kind of flooded with the same PAPI + Essentials errors. Not sure what PAPI has to do with them, but in any case they're there, and may have remotely something to do with this issue.

The server is in offline mode, which may be determining on why this happens.

I already contacted MarriageMaster, they obviously think this isn't their fault, which makes sense, since it worked for you.

**Comment by ElBananaa** [comment]
> [2021-09-24-3.log](https://github.com/kangarko/ChatControl-Red/files/7230346/2021-09-24-3.log)
> Here's a log from yesterday including startup, since the one for today got cut off at 12.
> 
> It is kind of flooded with the same PAPI + Essentials errors. Not sure what PAPI has to do with them, but in any case they're there, and may have remotely something to do with this issue.
> 
> The server is in offline mode, which may be determining on why this happens.
> 
> I already contacted MarriageMaster, they obviously think this isn't their fault, which makes sense, since it worked for you.

That's right, but in this case, it also makes sense that this has nothing to do with us neither then. I mean, there's 99% chance this isn't related to us since PAPI itself told you there's an issue with the placeholder. So this has to either be an issue on PAPI or MarriageMaster with your config.

The only thing I can suggest is playing around with your config files, maybe even resetting them. We can't do anything more unfortunately.

**Comment by GeorgH93** [comment]
> 
> 
> [2021-09-24-3.log](https://github.com/kangarko/ChatControl-Red/files/7230346/2021-09-24-3.log)
> Here's a log from yesterday including startup, since the one for today got cut off at 12.
> 
> It is kind of flooded with the same PAPI + Essentials errors. Not sure what PAPI has to do with them, but in any case they're there, and may have remotely something to do with this issue.
> 
> The server is in offline mode, which may be determining on why this happens.
> 
> I already contacted MarriageMaster, they obviously think this isn't their fault, which makes sense, since it worked for you.

It looks like there is something wrong with your MarriageMaster language file, it seems to be missing a lot of entries. Could you please try to delete and regenerate the language file.
