### ISSUE TITLE
1.17.1: does not support Chinese message

### ISSUE THREAD

**Issue by SheerYin** [kangarko/ChatControl#1332]
Unable to save Chinese information as a database, it will directly display empty or garbled characters
Include server-name/chat, etc. 

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey,
Could you please provide us your `/chc debug` file and your latest.log file?
The issue may be caused by a lot of different reasons, however, usually when people report a such issue with Chinese and non-latin characters, it's most likely either caused by their database driver being outdated, or a wrong table encoding. Providing us these files will allow us to make sure about this. Thanks! 😉

**Comment by kangarko** [comment]
Closing, please follow what Banana said and see this: https://github.com/kangarko/ChatControl-Red/wiki/Use-Right-Encoding
