### ISSUE TITLE
Optimising plugin

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1333]
Plugin version : 10.6.4
Minecraft Version: 1.16.5 (Airplane)
MySQL: false
BungeeCord: false (my server is under velocity, but bungeecord is FALSE in my config

My debug (on 10.6.3, config didn't change since this time) : 
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7129695/debug.zip)

The plugin can be "heavy", I mean, it's in the top consuming ressources, as you want to optimise the plugin, you can take a look at this spark; and I hope you can optimise it : 
https://spark.lucko.me/p3OOmt6FVR

**Comment by WarnDa** [comment]
Another sparks :
https://spark.lucko.me/iYtkHuV3Dp
https://spark.lucko.me/hMJeN902EZ

it can go up to 1.5% :/

**Comment by kangarko** [comment]
Looks like spy broadcasting is heavier than usual. you'd have to cut back on your format parts to optimize this as per https://github.com/kangarko/ChatControl-Red/wiki/Performance. Compiling formats takes time due to how Minecraft splits colors 
 and hover/click events into different components etc, but it typically doesn't cause a real in-game issue.
