### ISSUE TITLE
1.17.1: Wondering how to disable censoring in a specific chat

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl#1334]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Hello! was just wondering on how to disable the swear filter in a certain chat - I had tried adding the command that sends it into the chat in the group.yml file however that didnt seem to work, was wondering if i was missing another area somewhere to do so ?

**Comment by ElBananaa** [comment]
Hey,
I believe gone-incognito already answered a similar question in #400, so feel free to take a look there, and try what he said!
Let me know if it works, or if you need anything else! 😃

**Comment by SecretarySami** [comment]
> Hey,
> I believe gone-incognito already answered a similar question in #400, so feel free to take a look there, and try what he said!
> Let me know if it works, or if you need anything else! 😃

based off what he said was to add something like the following in the group.rs file 

# Do not filter swears in the channels below.
ignore channel <channel_name>

I had added this and it still seems to filter the swear words in it , honestly not sure what im doing wrong even after checking the wiki as well

**Comment by SecretarySami** [comment]
Added it here 
https://i.imgur.com/D7Lsj2o.png

**Comment by TheIntolerant** [comment]
I had a similar issue once where I thought ``ignore channel`` was broken but as all my staff use a command to talk in the admin chat, etc. Therefore I needed to also add ``/adminchat`` etc. via ``ignore command`` to disable swearing, in that channel.

Hope this helps.

**Comment by TheIntolerant** [comment]
Another thing to note is that, if you use ``Commands.yml`` or a plugin to create aliases, keep in mind these typically work by getting the user to effectively run a command twice. 

So if the aliase was ``/adminchat`` but the actual command was ``/channel send admin``
The user is executing both ``/adminchat`` and ``/channel send admin``

For that reason, you would need to use ``ignore command /adminchat|/channel`` instead.

The only problem with the above, as ``ignore command`` does not seem to block multi-argument commands such as ``/channel send admin`` so you are forced to just use ``/channel`` in the ignore command operator. This however could prove to be problematic depending on setup, as people may be able to do ``/channel send main_chat`` etc to swear.

For that reason, if the only reason you use ``Commands.yml`` or a plugin to create aliases, is to make the command (/adminchat etc) work with tab-completion, I strongly recommend getting chatcontrol to handle the actual command by adding something like this in the command.rs file

```rs
# Provides user with description about "/adminchat"
match ^\/(adminchat|achat|ac)$
then warn &cDescription: Send a message to admin chat.
then warn &cUsage: $0 <message>
then deny
dont verbose


# Send messages starting with "/adminchat" to admin channel
match ^\/(adminchat|achat|ac) (.*)
then command channel send admin $2
then deny
dont verbose
```

You do not need to remove the aliases created. This way you only need to add ``ignore command /adminchat`` and not also include ``/channel`` etc in that operator. 

Also, keep in mind if you do use a plugin to create an alias, and this issue hasn't been resolved, check to see if you are able to register the command, as this has been a common issue in the past where chatcontrol was not working correctly with command aliases created within a plugin. Since chatcontrol was unable to detect the command thus the issue continued to persist.

**Comment by SecretarySami** [comment]
> Another thing to note is that, if you use `Commands.yml` or a plugin to create aliases, keep in mind these typically work by getting the user to effectively run a command twice.
> 
> So if the aliase was `/adminchat` but the actual command was `/channel send admin`
> The user is executing both `/adminchat` and `/channel send admin`
> 
> For that reason, you would need to use `ignore command /adminchat|/channel` instead.
> 
> The only problem with the above, as `ignore command` does not seem to block multi-argument commands such as `/channel send admin` so you are forced to just use `/channel` in the ignore command operator. This however could prove to be problematic depending on setup, as people may be able to do `/channel send main_chat` etc to swear.
> 
> For that reason, if the only reason you use `Commands.yml` or a plugin to create aliases, is to make the command (/adminchat etc) work with tab-completion, I strongly recommend getting chatcontrol to handle the actual command by adding something like this in the command.rs file
> 
> ```rust
> # Provides user with description about "/adminchat"
> match ^\/(adminchat|achat|ac)$
> then warn &cDescription: Send a message to admin chat.
> then warn &cUsage: $0 <message>
> then deny
> dont verbose
> 
> 
> # Send messages starting with "/adminchat" to admin channel
> match ^\/(adminchat|achat|ac) (.*)
> then command channel send admin $2
> then deny
> dont verbose
> ```
> 
> You do not need to remove the aliases created. This way you only need to add `ignore command /adminchat` and not also include `/channel` etc in that operator.
> 
> Also, keep in mind if you do use a plugin to create an alias, and this issue hasn't been resolved, check to see if you are able to register the command, as this has been a common issue in the past where chatcontrol was not working correctly with command aliases created within a plugin. Since chatcontrol was unable to detect the command thus the issue continued to persist.

I'll try this out as soon as I get a chance:)

**Comment by SecretarySami** [comment]
> I had a similar issue once where I thought `ignore channel` was broken but as all my staff use a command to talk in the admin chat, etc. Therefore I needed to also add `/adminchat` etc. via `ignore command` to disable swearing, in that channel.
> 
> Hope this helps.

added /channel to our filter and doing some testing , thank you guys for the help! gonna close this :)
