### ISSUE TITLE
1.17.1: Rule for quick channel message using ignore and require

### ISSUE THREAD

**Issue by RetGoatCopper** [kangarko/ChatControl#1390]
Is there a reason why the below would not work for the purpose stated? It seems to not be hitting the ignore...

- Catch "/helpchat <message>" and "/hc <message>" and send it to Help channel.
- ignore first rule if user is already in Help channel in read mode
- Join user into Help channel in read mode

```
match ^\/(helpchat|hc) (.*)
dont verbose
ignore channel Help read
then command channel send Help $2
then command channel join Help read
then warn &7Click the channel prefix to leave the help chat
then deny
```

- If not matched to rule above
- Require user to be in Help channel in read mode. as to avoid "already joined" message
```
match ^\/(helpchat|hc) (.*)
dont verbose
require channel Help read
then command channel send Help $2
then deny
```

Console Read Out 
![Screen Shot 2021-10-16 at 8 06 19 AM](https://user-images.githubusercontent.com/43792057/137586651-54d00641-4c66-47a9-90df-c622f70eec1f.png)

In-game Read Out
![Screen Shot 2021-10-16 at 8 06 42 AM](https://user-images.githubusercontent.com/43792057/137586663-512ebd37-2cb8-4b6c-bf8c-a22a2f71d21c.png)

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
I am sorry, the ignore channel option checks and ignores the channel from which the sender is writing. In your case, you can still be chatting from your "standard" channel and be joined in the help channel as reading. 

The rule would work if you would send a message from the Help channel. But since this is utterly illogical, I made an exception in the code for you and the rule wont execute starting the next version, if player is already reading the Help channel.
