### ISSUE TITLE
1.12.2: Is there (any) support for Sponge and/or Forge

### ISSUE THREAD

**Issue by LurgenAU** [kangarko/ChatControl#1421]
Minecraft Version: 1.12.2
MySQL: true
BungeeCord: true

I run a network with a mixture of servers, one of which is a Sky Factory 4 box. This runs on Sponge / Forge, so can't run Spigot plugins. The rest of our servers are more conventional Paper (one is Mohist). We'd love to be running ChatControl-Red but this one lingering host would be an obstacle. What's the best approach to this one?

**Comment by LurgenAU** [comment]
I have started experimenting with the plugin (bought it, the 30 day trial offer is a good idea) and found the Chat_Forwarding option in the Bungee config, but so far it doesn't seem to do anything at all when I enable it. More experimentation required I guess.

**Comment by LurgenAU** [comment]
Interestingly, join/leave messages ARE being forwarded to the server without a plugin - odd!

**Comment by ElBananaa** [comment]
Hey,
The plugin doesn't support sponge.
I don't exactly know how the chat forwarding option works, but I guess sponge doesn't have all the needed api parts for it to worl properly. Anyways i'd suggest waiting for Kangarko ^^

**Comment by kangarko** [comment]
I don't think we have the resources nor time to support anything else than Spigot at the moment. Velocity support is in active development. The Chat Forwarding feature is recognized by Spigot servers, not sure what happens when the data is received on Sponge. If that won't work for you, you can either keep using the plugin the rest Spigot part of your network or apply for a refund.
