### ISSUE TITLE
1.16.5 : Use hex color 

### ISSUE THREAD

**Issue by WarnDa** [kangarko/ChatControl#1423]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

Hello,
I want to make my own chatcolor system (using deluxemenus) to only use HEX colors for chat (as it's not possible currently into the plugin itself).

So I give the player the perms : 
> chatcontrol.color.#A724CC
> chatcontrol.guicolor.#A724CC

Then I make a command throught console "/chc color #A724CC reset %player%", it applies the color, but when he disconnect/reconnect, he doesn't get his color anymore.
How to set a permission for Hex colors ?

**Comment by kangarko** [comment]
Thanks, will be fixed in the next version.

**Comment by WarnDa** [comment]
Not fixed on the latest release.
What is the permission to get a hex color ?

**Comment by ElBananaa** [comment]
Reopening the issue as asked by the author on discord.

**Comment by TheIntolerant** [comment]
The permissions are ``chatcontrol.hexcolor.{color}``

So for the hex colour you mentioned it would be ``chatcontrol.hexcolor.A724CC``


----

## Suggestion regarding this issue

I was planning on making my own GUI for chat colors that also had hex colours players could select from, I noticed that the perm ``chatcontrol.hexcolor.{color}`` applies to both ``/tag nick`` as well as "/chc color" when using hex colors. Is there any chance the perms for Hex colors in "/chc color" are something like ``chatcontrol.guicolor.hex.{color}`` etc? As I personally would prefer separate permission nodes for chat colors vs nicknames etc.


#### Perms for "Colors.Apply_On" 
In other words, these permission nodes
   - ``chatcontrol.color.{color}``
   - ``chatcontrol.hexcolor.{color}``
 etc

Only apply to whatever is listed here "Colors.Apply_On" in your settings, and the hex permissions do not apply to "/chc color".


### Different Perms for "/chc color"
But the perms for "/chc color" have their own set of perms for hex colors.

So instead of using ``chatcontrol.hexcolor.{color}`` for both "/chc color" and whatever is listed here "Colors.Apply_On" in your settings, such as nicknames etc. The perms for "/chc color" are as follows:
   - ``chatcontrol.guicolor.{color}`` for the normal colors such as red (&c) gold (&6) etc
   - ``chatcontrol.guicolor.hex.{color}`` and this for hex colors 
   
If that makes sense, I also feel this would be less confusing too.

Since you would have one set of perms that is clearly for the chat color GUI, while all the other perms are for things such as chat, nick, me, private_message, etc aka whatever is listed in "Colors.Apply_On".

**Comment by kangarko** [comment]
Love it, thanks for the explainer!
