### ISSUE TITLE
1.16.4 Bungeecord Permission

### ISSUE THREAD

**Issue by PascalBrassat** [kangarko/ChatControl#143]
Hello, so we are trying to push chatcontrol red live on a bungee server, and it seems we are missing a permission in order for regular users to actually chat cross-server? We have narrowed it down to a bypass permission but if you or anyone has any further information that would be awesome. (Our team is pulling an all nighter so we could have missed something)

**Comment by NerdyBirder** [comment]
I am having the same issue where only opped players' messages are being sent across servers on a bungeecord network.

**Comment by Godlycreations** [comment]
I am having the same issue on 1.16.4 bungeecord/mysql, I sill cannot find the perm that works, but using chatcontrol.* seems to allow it also.

**Comment by PascalBrassat** [comment]
> I am having the same issue on 1.16.4 bungeecord/mysql, I sill cannot find the perm that works, but using chatcontrol.* seems to allow it also.

as a temporary solution, using chatcontrol.bypass.* works for this, but figuring out which specific perm in the bypass would do it we have not been able to figure out.

**Comment by NerdyBirder** [comment]
I found out something interesting with this problem today. When i am spying our global chat i see messages from other bungeecord instances but when i join the global channel to write i stop seeing them.
Also, if we do /chc send global or join the global channel and talk other subservers can see my messages but players that are spying global and are in the same subserver cant see it at all.

**Comment by kangarko** [comment]
Thank you. That was an odd glitch. Explanation here https://github.com/kangarko/ChatControl-Red/issues/94, basically I coded a special message "deduplicator" which prevents doubled messages being sent if using Redis.

The deduplicator would take plain messages like "hello" instead of properly categorizing it, and so when that message is sent twice, first time for spying, and second time for players, players would not receive this.

This problem will be solved in the next version, I apology for the inconvenience.
