### ISSUE TITLE
How is /chc purge {playername} supposed to work?

### ISSUE THREAD

**Issue by P-paj** [kangarko/ChatControl#1444]
I try and purge a players text - it tells me it has been purged, but nothing gets removed??

Minecraft Version: 1.17.1 (Paper)
MySQL: false
BungeeCord: true

**Comment by P-paj** [comment]
Aside - i DO run viaversion... does that invalidate this feature?

**Comment by ElBananaa** [comment]
> I try and purge a players text - it tells me it has been purged, but nothing gets removed??
> 
> Minecraft Version: 1.17.1 (Paper) MySQL: false BungeeCord: true

Hey!
The purge system is supposed to completely remove messages sent by the specified player.
In order to get it working, you need both ProtocolLib installed and up-to-date. You also need to enable the channel feature.

I ran some tests on my end and it works perfectly fine on my side. May I ask what's your server version? I'm pretty sure running ViaVersion on a 1.17.1 server is kinda useless since it's basically the latest version available ^^

**Comment by kangarko** [comment]
Thanks to Banana for explaining. Just to add, this may not work when using ViaVersion due to the way they intercept packets.
