### ISSUE TITLE
1.12.2: Check if muted

### ISSUE THREAD

**Issue by Superalex0102** [kangarko/ChatControl#1450]
Minecraft Version: 1.12.2
MySQL: true
BungeeCord: true

Hey!

I want to block the player from using /helpop (channel) if he is muted via LiteBans, is there a way to do this? If yes, how?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.12.2 MySQL: true BungeeCord: true
> 
> Hey!
> 
> I want to block the player from using /helpop (channel) if he is muted via LiteBans, is there a way to do this? If yes, how?

Hey!
To block specific commands for muted players with litebans mute feature, go to your litebans config file, and under the `mutes:` section, add the commands you would like to block.

I'm closing this since it's not related to chatcontrol-red.
Please only open issues related to our plugin next time.

**Comment by kangarko** [comment]
You can also create a rule in our rules/command.rs, see examples there
