### ISSUE TITLE
How to use regex101?

### ISSUE THREAD

**Issue by BoomScoom** [kangarko/ChatControl#147]
How do you use regex101?

**Comment by kangarko** [comment]
Hello,
I am really sorry, but I cannot give you a general information on regular expressions and how to test them, since I myself lack enough knowledge. Furthermore, your question is too general and I would like to rather spend time on the plugin itself then explaining such services. However, I can try to give you some concise tips and maybe someone else will help more.

See the picture. In the field marked by 1. insert your regular expression. Then write some text you want to test the regex against in the field 2. Explanation how the regex works in is field 3.

![tutorial](https://cloud.githubusercontent.com/assets/1918426/8639399/0f94dca0-28d9-11e5-8042-9620814dc639.PNG)

**Comment by BoomScoom** [comment]
I still don't get it.  If I wanted to change the f word in the rules to the s word how would I find it it works with the regex?

**Comment by kangarko** [comment]
See following post for example filter and how to change the characters:
https://github.com/kangarko/ChatControl/issues/120
