### ISSUE TITLE
1.16.5 Tuinity - Database connection is slow

### ISSUE THREAD

**Issue by 1ntent1on** [kangarko/ChatControl#1484]
Minecraft Version: Tuinity version git-Tuinity-"b12d0cc" (MC: 1.16.5)
MySQL: true
BungeeCord: true
Latest plugin version

Hello, i started getting these messages few days ago, although i didnt modify any configs, since it was working. "[ChatControlRed] Warning: Database connection is slow (3079.45 seconds), game will not lag, but data will be delayed." Thanks to that, ingame commands dont work (console does), since player data arent loaded, but this issue is only on the base server with all of the chats. When i asked my MySQL host about it, they told me that i "should ask plugin author, since its not their bad". Is there anything that i can do about it ?

**Comment by ElBananaa** [comment]
Hey,
Please try to lower the value of the `Log.Clean_After` option in your settings file.
As example, in my case, I defined it to 1 week: 
![image](https://user-images.githubusercontent.com/53318613/142663969-f450d621-d564-41d5-b023-8ba8cacea9c9.png)

If you don't use our internal logging command (`/chc log`), you could also completely disable it by replace your `Apply_On:` part with `Apply_On: []` (Or if you only use some parts of the logging feature such as private messages/chat messages, set `Apply_On [chat, private_message]`.

You can also lower the `Clear_Data_If_Inactive` part value. In my case, I set it to 30 days, so if a player haven't joined the server for 30 days or more, their plugin data will be completely cleared (which means chat colors, channels joined/leaved, players ignored etc.

You may also want to switch to MariaDB which offers much better performances than MySQL.

Also, please keep in mind that mutualized database host often have poor performances, especially when you reach a certain amount of db requests, so this issue may actually be caused by limitations on your host side. In comparison, I never had a such issue with a db hosted on the same dedicated server than my mc server.

**Comment by kangarko** [comment]
Thanks to Banana for the tips. If you're still experiencing this, take a screenshot of ChatControl tables in your phpMyAdmin if possible, like this one (https://i.imgur.com/Gx8A0m4.png) so I can see how large your tables are.

It's also recommended to use MariaDb for best performance. Closing this but will follow up with you if needed below.

**Comment by 1ntent1on** [comment]
Hello, i tried doing what Banana wrote. It kinda helped since im not having this issue that much as i used to, but its still not completly solved. Here are the tables (https://imgur.com/a/L7AyUrG). 
Currently im not able to switch to MariaDb.

**Comment by ElBananaa** [comment]
> Hello, i tried doing what Banana wrote. It kinda helped since im not having this issue that much as i used to, but its still not completly solved. Here are the tables (https://imgur.com/a/L7AyUrG). Currently im not able to switch to MariaDb.

Hey,
Your database size is extremely small, a such issue shouldn't happen.
There's definitely something wrong, but I doubt it's related to chatcontrol. In my opinion it's either being caused by your minecraft host or your mysql host being slow.

**Comment by kangarko** [comment]
I see you're Czech, let me just answer in your language:

Vyzerá to tak, že ChatControl_Log je dosť veľká tabuľka (relatívne). Ak je možné, skúste si ju exportovať a stiahnuť na PC, potom vymazať, či bude nejaká zmena. Jediná vec čo sa zmení je že pomocou /chc log príkazu sa nezobrazia staré záznamy.

**Comment by 1ntent1on** [comment]
Díky, pomohlo to.
