### ISSUE TITLE
1.17.1 Issues with colors and channels.

### ISSUE THREAD

**Issue by MuriloWentz** [kangarko/ChatControl#1543]
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

On the image at the end, i marked in red some things to help me explain to you the error because it is fully translated to portuguese!
All of that was tested in a non-op account, and every permission needed was added to the member UltraPermissions group.
![Sem título2](https://user-images.githubusercontent.com/50129175/145312547-1473f77f-bc88-46b6-9401-5a26c1b2ad1b.png)

so lets move on, im having 2 problems i can explain with the image bellow.
1. I changed my chat color.
2. after changing my chat color, i was auto added to the local channel (????)
3. then i joined back to the global channel 
4. after in global channel my chat color got reset
These first 4 topics is 1 error, the next one is another
5. this mark show that when i try to join back to local channel the Already_Connected localization message show up, but not Switch_Success or Success message.

Everything works just fine on a op account, so i assume im missing something i cant find. 

![Sem título](https://user-images.githubusercontent.com/50129175/145313514-41cca3e4-99e2-44e0-9a70-af05c554672d.png)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7681342/debug.zip)

**Comment by ElBananaa** [comment]
Hey,
Your issue is caused by your permission setup.
You are trying to force players to automatically join the global channel in both write & read mode, which is a bad thing, while also forcing them to automatically join the local channel in write mode, which makes things even worse.

Players can only join **one** channel in write mode **at once**, and this cant be changed/increased since you can't write in 2 different channels at the same.

On the other hand, your players can automatically join as many channels as you want in read mode, **if the amount of channels they're trying to join (automatically or not) is equal or lower than the `Max_Read_Channels` value defined in the settings file.**

Please only keep one autojoin permission for a write channel (so if you want players to automatically join the global channel in write mode, only give them the permission to automatically join the channel in write mode, and not in read mode).

Let's suppose you want to setup your channels as I said above, remove the permissions that are in the red squares, if you want a different setup, simply edit your permissions to match what I said above.
![145312547-1473f77f-bc88-46b6-9401-5a26c1b2ad1b](https://user-images.githubusercontent.com/53318613/145658490-c93675b9-ac9c-4d44-97f0-6e86748c3c72.png)

**Finally**, if some of your players have already joined the server and you'd like to avoid manually fixing your permissions for each user, I'd suggest removing your data file, so they will automatically and properly join the right channels.
Keep in mind that you must remove the data file while the server is stopped, and deleting the file will cause players to lose they chat colors, ignored player list, mutes (if using our mute system) and their tags (if using our internal tag system).
