### ISSUE TITLE
1.17.1: First-time join messages?

### ISSUE THREAD

**Issue by yourlocalvirgo** [kangarko/ChatControl#1545]
Minecraft Version: 1.17.1
MySQL: true I think
BungeeCord: false

Hi, I'm trying to set up join messages for people who join my Minecraft server for the first time. I saw another forum from August asking the same question, and saw that `ignore firstjoin` and `ignore playedbefore` may have been added, however, when I try to add those to my join config file for Chat Control Red, it doesn't recognize it. Please help!

**Comment by TheIntolerant** [comment]
Hey,

Assuming you aren't using a proxy setup of any kind since you wrote ``BungeeCord: false``, as you may have guessed by now, the operators ``ignore firstjoin`` and ``ignore playedbefore`` only work on a bungeecord server (OR any fork such as waterfall etc) using the bungee plugin "BungeeControl-Red".

To use create a first-time join message inside chatcontrol-red instead of bungeecontrol-red, there should be an example in the default file for ``join.rs`` on chatcontrol.

If you cannot find that then just copy and paste this
```yml
# An example of First Join Message for 1.13+ versions. Uncomment the lines below if your server runs MC 1.13 or greater.
# Please make sure to keep your first join message at the top of the file, above any other join message to avoid any issues.
group firstjoinmessage
require sender script player.getStatistic(Java.type("org.bukkit.Statistic").PLAY_ONE_MINUTE) <= 1
message: 
- &7Welcome to the server &c{player} &7!
```
