### ISSUE TITLE
Discord formatting condition

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1579]
When someone messages from Discord to in-game, can we please have a formatting condition to display if they are coming from discord, at present my global chat requires a permission from the default group to display their username, because my staff have permissions for their usernames to be formatted with gradients. Because of the way this is designed the default group has to have a permission otherwise names are shown twice for staff.

Which means, when someone writes from discord they don't show up with a username.
And all their hover over placeholders dont work, which is a bit silly, I want to be able to have a click/hover for this discord user too.

**Comment by ElBananaa** [comment]
As stated on our wiki (https://github.com/kangarko/ChatControl-Red/wiki/Variables), you can use the `{sender_is_discord}` variable to check if the message comes from a discord user ^^

**Comment by kangarko** [comment]
Hi Tom!

You can use the following format part snippet to show discord-only format:

<img width="652" alt="Screenshot 2021-12-23 at 09 10 07" src="https://user-images.githubusercontent.com/1918426/147209239-ba441bdd-afa5-4f36-934a-39d40b01c355.png">

Most placeholders won't work because they require a player instance which is non-existent if player is chatting from Discord.

**Comment by TomLewis** [comment]
Aha I knew I had seen it somewhere, this is in chat.yml, thank you both!
All working now!
