### ISSUE TITLE
1.12.2: Server kicking out for Timed Out

### ISSUE THREAD

**Issue by Superalex0102** [kangarko/ChatControl#1591]
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false
ChatControlRed version 10.8.9

Hey!
I wanted to disable the ability for players to auto complete all the commands on the server, but when I try to, the server just kicks the player with the message "Timed Out".
I understand the following: `Warning: Detected ViaVersion. If you're getting kicked out or see artifacts in chat, set Integration.ProtocolLib.Listen_For_Packets and Tab_Complete.Enabled both to false in settings.yml`, but order to disable auto complete on commands, I need to enable that.
What do I need to change on ViaVersion/ChatControlRed settings so I don't get kicked out?

**Comment by Superalex0102** [comment]
Update: I also get kicked out with Timed Out while ViaVersion is not even loaded

**Comment by Superalex0102** [comment]
[00:40:07 INFO]: Plugins (5): ChatControlRed, LuckPerms, PlaceholderAPI, ProtocolLib, Vault

**Comment by ElBananaa** [comment]
Hey,
Please provide us your `/chc debug` output file. I've been using chc-red for quite a while now and never experience this issue before.

I doubt this is related to chc-red tho, since it would kick you for `too many packets` in this case. `Timed Out` means the server took too much time to send an answer to the client (I belive).

**Comment by Superalex0102** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7798197/debug.zip)

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7798197/debug.zip)

Hey, Happy New Year!
I don't see anything wrong. The only thing that could potentially solve your issue is to set `ProtocolLib.Listen_For_Packets: false` in your settings file, at least for now, until Kangarko takes a look at your issue.

I doubt there's much he can do about that tho, plugins such as ViaVersion & ViaBackwards are pretty tricky to works with ^^

**Comment by kangarko** [comment]
Unfortunately that is an error in ProtocolLib. Just tested and confirmed even if we do not hook into anything it still happens. I advise contacting that developer instead.
