### ISSUE TITLE
1.18.1: Message for chat is before the name with this recent update.

### ISSUE THREAD

**Issue by Michael-A-Sloan** [kangarko/ChatControl#1613]
latest version: true
Minecraft Version: Paper 132 (1.18.1)
MySQL: false
BungeeCord: false

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7803357/debug.zip)

<img width="439" alt="in game issue" src="https://user-images.githubusercontent.com/89812914/147964545-26501554-8600-48a2-bc5e-8031d0d7aa59.png">

<img width="439" alt="global chat format" src="https://user-images.githubusercontent.com/89812914/147964563-695fb247-24a6-434b-a469-62493e8717f9.png">

The issue at had only happened with this recent update: 
Messages for chat is before the name with this recent update check pictures and debug zip.

**Comment by Terminal-Access** [comment]
Chat Control Red Version: 10.9.0
Minecraft Version: paper-1.18.1-132
MySQL: false
BungeeCord: false

Confirming this bug, 
as seen below - formats/ *.yml files are being re-written every server load and the defined section parts within are meing misplaced. thus screwing up the order of the formatting.

I wonder if adding some form of "weight" to the section parts could solve this, then when their put back together you call upon the weight in order to see what part  comes before another (just like how permission/ranks can be weighted)

![2022-01-03_18 20 06](https://user-images.githubusercontent.com/6170786/147965471-1dffa65b-8487-426c-a075-5fee753106b4.png)

**Comment by kangarko** [comment]
I used a HashMap instead of LinkedHashMap internally which optimizes components order according to Java. Will be patched asap today.

**Comment by kangarko** [comment]
From my research, seems like you will need to manually either load a backup version of ChatControl Red folder or manually realign, so sorry for that! Caused by the last update trying to fix Spigot/Paper change in how config is stored crashing our plugins.

**Comment by Terminal-Access** [comment]
> From my research, seems like you will need to manually either load a backup version of ChatControl Red folder or manually realign, so sorry for that! Caused by the last update trying to fix Spigot/Paper change in how config is stored crashing our plugins.

No worries thanks for the heads up, and this is exactly why i have backups and a dev environment to test updates xD

Keep up the amazing work, thanks so much for the very fast responce on getting back regarding the past few day's worht of bugs and happy new year!
