### ISSUE TITLE
1.18.1 - BungeeControl LuckPerms integration Join messages

### ISSUE THREAD

**Issue by NovaPixell** [kangarko/ChatControl#1630]
Hi, I just want to know if it is possible to set join/left messages by integrating LuckPerms and rank prefixes. Since I didn't find any information online, thank you.

**Comment by ElBananaa** [comment]
> Hi, I just want to know if it is possible to set join/left messages by integrating LuckPerms and rank prefixes. Since I didn't find any information online, thank you.

Hey!
Chatcontrol works fine with most permission plugins, and especially luckperms, so you can use luckperms placeholders with the plugin. You can also define custom join/leave messages based on a permission, a group, or even a player.

Here's an example of custom join message taken from my server join.rs file:
```
group elbananaa-join-message
require sender script "{player}" == "ElBananaa"
message:
- &6[&a+&6] &d{player} &fjoined the server !
```

You can adapt this script to use the rank placeholder instead. As example, if a player with the primary group `Test` joins the server, this script will be triggered. Also note that this is case-sensitive.
```
group elbananaa-join-message
require sender script "{player_primary_group}" == "Test"
message:
- &fA player with the TestRole role joined te server
```

You can find more informations about this on our wiki: https://github.com/kangarko/ChatControl-Red/wiki/Messages 
As for BungeeControl, i'm not 100% sure that this will work, since placeholderapi doesn't work over bungeecord, so you may need to do this on the lobby server, not on the proxy.

**Comment by TheIntolerant** [comment]
While PlaceholderAPI doesn't work on bungeecord could "BungeeControl-Red" implement a way of obtaining data from PlaceholderAPI from the backend servers?

Would be a cool addition if not too complicated of a task @kangarko

**Comment by kangarko** [comment]
Thanks for explainer Banana!

TheIntolerant you're right, on Bungee we don't get that data. The amount of headache with data sync has been over my head. Especially with larger network experiencing kicks due to packet overflow, I don't have the time to do yet another rewrite right now.
