### ISSUE TITLE
Question about color permissions

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#167]
```
Setup that I want/currently have with CHC 8:

- Players can use the hexcode / color codes in their nickname that they have in their rank prefix to match nickname with prefix.
- A donator rank can use all hexcodes / color codes in their nickname and a specific color in /chc color.
```

With CHC 10, it seems I can not allow the donator rank to use a hexcode/color code in chat AND in nicknames, since then the normal players would be able to use colors in the chat as well. I'd like a similiar permission system as CHC 8 has for this.

I know of the config setting, but if I set it to chat and nickname, normal players would be able to use colors in chat.

Is there anyway to achieve my old setup?

**Comment by kangarko** [comment]
Hello!

What if you leave 'chat' and 'nicks' in the Colors section: https://i.imgur.com/6NMiaZC.png and then give normal players negative color permissions? So that only donators would have color permissions to use colors. These are described in the comments header of that section. 

We don't support toggling sections per player groups, that would be over complicated. You can however distinguish between guicolor and normal color permissions for donators and normal players.

**Comment by Sikatsu** [comment]
If I give normal players a negative permission, they wouldn't be able to use it within nicknames. I want them to be able to use the colors / hexcodes from our rank prefix within the nickname, but not within the chat.

While a donator rank can use it within the chat and nickname.

In CHC I can achieve this with permissions though

**Comment by kangarko** [comment]
Got it, next version will have such feature :)
