### ISSUE TITLE
Add java 17 support for 1.8.8 and 1.12.2

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl#1670]
I am using Nachospigot that is compiled on java 17 and yeah is compatible from java 8 too, but i noticed when i use java 17 and chatcontrol red and nashorn (as i reported on java 1.12) it fail to load and crash,
Java 17 is more efficient than older java  on older versions and it would bring beneficst, chatcontrol red is the only plugin that is not working, i would like to see it compatible with these on old versions

**Comment by kangarko** [comment]
I understand, but is technically not feasible for me to spend time on this since people are moving on to new MC versions. You need to stay on Java 8 which is supported until 2030. By the way other plugins will have issues too running J17 on old MC versions, I remember luckperms had some issues in the past.

**Comment by iSilviu-debug** [comment]
@kangarko 1.18 servers, are not yet stable to hold more than 300 players and java 17 makes these servers the best solution to manage them better. Then java 16 works, why not make java 17 work too? I understand the support you specified, but 70% of your customers use 1.8 servers.

**Comment by kangarko** [comment]
Under 7% of all my customers run ChatControl on an old MC version : https://bstats.org/plugin/bukkit/ChatControl%20Red/13100


 Java 15+ had reflection breaking changes and removed a library we use and cannot load since Spigot added this ability to 1.16+ only. 

The only solution is to use NashornPlus, if that does not work then you can post an error log and I can have a look regardless.

**Comment by Malachiel87** [comment]
This is the error that i get when i use NashornPlus and java 17 on 1.8.8
![image](https://user-images.githubusercontent.com/3611852/150748525-af9b0952-5b10-402f-9b69-06b237a5d073.png)

**Comment by kangarko** [comment]
Can you post your full startup log?

**Comment by kangarko** [comment]
@Malachiel87 fixed!!! Get the new Nashorn here:

https://bitbucket.org/kangarko/nashornplus/downloads/NashornPlus-1.2.0.jar

**Comment by Malachiel87** [comment]
Great! I will test later! Love you!
