### ISSUE TITLE
1.17.1: database driver is outdated

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1685]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

So during startup, I get this message in the console
"[ChatControlRed] Warning: Your database driver is outdated. If you encounter issues, use MariaDB instead."
However, the version of mariadb I am using is 10.5.13 which was released 2021-11-08, that being said is there anything I need to do to fix this? I don't seem to have any sort of connection issues.

In the ``mysql.yml`` file I have this set.

``Line: jdbc:mysql://{host}/{database}?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false``

Since I am using mariadb, should I change anything in that line? or is it fine as it is?

**Comment by ElBananaa** [comment]
I believe this message is caused by Foundation using an outdated and deprecated JDBC version. It shouldn't cause any issues, however I'd definitely suggest switching to an up-to-date one (Kangarko suggests to use a connector that's older than 12 years in foundation's comments).

I'm working on fixing this on my side then will most likely make a pr once everything's been tested. I also managed to implement HikariCP (based on this pr https://github.com/kangarko/Foundation/pull/76/files). I didn't manage to test it so far, but i'll probably run tests by next week. (If I finally manage to compile Chatcontrol-red, because for an unknown reason maven can't find Foundation on my computer).

**Comment by kangarko** [comment]
Thanks. As long as this works right now I am prioritizing recording the new program and will gradually update Foundation in the process later.

**Comment by kangarko** [comment]
@ElBananaa appreciated you making a fix, just submit a PR once ready <3
