### ISSUE TITLE
1.17.1: Issue with Skript & Chat (Only happens with CHC)

### ISSUE THREAD

**Issue by Tosfoy** [kangarko/ChatControl#1688]
Hello! I have an issue with chc and skript.
Whenever my script asks to enter the message/amount in chat, it does not delete the message like other chat formater does.

For example, I have a few scripts that are used for announcements, giving money, and so on. These scripts ask for a msg to be typed in chat.
EssentialsChat, VentureChat, and Deluxechat deletes the message successfully
Could you help with that? Here's an example of the script and a picture of the problem

![462ad47e00234c3494a06014f4d23cd7](https://user-images.githubusercontent.com/58991099/151675134-98ddeda8-e635-4ceb-af3e-fd3901c66799.png)

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey,
I believe this is caused by our system. Since Chatcontrol completely overwrites the default chat system to implement its own channel and rule system. I don't think anything could be done unless Kangarko decides to fully rewrite the system, and since skripts need their own api, I don't think you can do anything either.

Please wait for Kangarko to take a look at your issue tho.

**Comment by kangarko** [comment]
No idea how I can fix that honestly. Your last resort would be reading our Wiki > Listener Priorities and trying all the values there to see if anything will fix that (in the sense that Skript will be able to remove its chat message before we do).

Alternatively you can try disabling our ProtocolLib integration.
