### ISSUE TITLE
1.16.5: Chat hexcolor settings not being remembered on reconnect?

### ISSUE THREAD

**Issue by Alucardz997** [kangarko/ChatControl#1690]
Hi, I have a question on a particular matter.

I wanted to provide my users with HEX colors on a "general" chat channel without giving them the permissions.
I've done this using DeluxeMenus (GUI + view permissions within the GUI for each item/color) where each item provides the user with the desired color by executing the command as console. (ex: chc color #ffdbfd reset %player_name%)

The problem I'm having is the fact that the user's color selection is not remembered after reconnecting.
I'm not having the same issue as Operator, thus I think it might be a permission matter.
What am I missing here?

I've tried troubleshooting this by providing the users with access via the following permissions:
- chatcontrol.command.color (was not intended to by provided in my initial design for this "feature" - wanted to keep them away from this command and it's downstreams thus the idea of applying the color via command executed by console)
- chatcontrol.use.color.chat (was also not intended for my initial design - not sure how ok my design was in regards to this aspect)
- chatcontrol.hexcolor.ffdbfd (not intended for my initial design - pretty sure it was not needed as the command is executed via console)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

**Comment by TheIntolerant** [comment]
Hello, I can confirm you do no need to give users the following permissions:
``chatcontrol.command.color`` and ``chatcontrol.use.color.chat`` and ``chatcontrol.hexcolor.ffdbfd``
For users to use your own chat color GUI. As I have also created my own GUI for chat colors.

The reason you don't need this perm ``chatcontrol.hexcolor.ffdbfd`` is because it is for allowing users to use the actual hex color code in chat itself and has zero impact on the usage of /chc color either in-game or the console.

---

Unfortunately, for users to keep their chat color after reconnecting, they need the color gui perm for that specific color code which is ``chatcontrol.hexguicolor.{color}``

Using the hex color code you've listed above, the perm you would need instead would be: ``chatcontrol.hexguicolor.ffdbfd``

That is the only permission node needed for the users to retain the color code they've selected with the GUI you've created.

**Comment by kangarko** [comment]
Thanks to Ezra for helping out! Lemme know below if you have any more questions.
