### ISSUE TITLE
Hi, I have a doubt

### ISSUE THREAD

**Issue by iTzAndreZGameZ** [kangarko/ChatControl#173]
I have a doubt

I want to know in which "folder" you can put the words you want to block (insults etc) since there are not many videos about this plugin and I try to put it in the "Rules" folder and the only thing that jumps me is the message " Please do not insult "but do not correct or block it, Thank you for your time

**Comment by kangarko** [comment]
Hello,

the folder where we store rules is named 'rules'. In the respective files, e.g. rules/rules.txt (the main file), you create rules which can block whatever messages you'd like, including insults.

1. The most easiest way to add rules is via ingame command '/chc addrule'.

2. To add them manually, I recommend you look though the file rules.txt since there is a comprehensive header that includes every possible option. You can also check this wiki article for a tutorial on creating advanced swear rules:

https://github.com/kangarko/ChatControl/wiki#rules

**Comment by kangarko** [comment]
Closing. If you have any more questions, feel free to comment below.
