### ISSUE TITLE
@p not working in commandblocks for /motd

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1737]
Simple one, I tried to /motd @p from a commandblock and it didnt work with Chatcontrol red.

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

**Comment by TheIntolerant** [comment]
Hey, so I believe this is a common issue, since generally speaking target selectors only work for vanilla commands.

Something you could use instead is [PsudoCommands](https://www.spigotmc.org/resources/psudocommands-add-the-target-selector-to-plugin-commands.56738/), I'm not sure if it works on the latest versions as it's only been tested on 1.7-1.14. However this plugin seems to add the ability of using target selectors to other commands. This is something I have personally never had the need to use, but could be helpful.

Anyhow, I'll leave this issue open, in case this is something that matej wishes to implement.

**Comment by kangarko** [comment]
I apology, target selectors do not work with us, they are meant for command blocks and vanilla commands, or as Ezra said above try the other plugin.

**Comment by TomLewis** [comment]
Weird, works fine with CMI.

Never heard of PsudoCommands, thanks, I will check it out!
