### ISSUE TITLE
1.18.1: Messages are blank

### ISSUE THREAD

**Issue by FinlayHDev** [kangarko/ChatControl#1748]
When people send messages they show up as blank spaces, bossbars work though.

<img width="394" alt="Screenshot 2022-02-19 at 18 30 40" src="https://user-images.githubusercontent.com/73852683/154814136-1a79de13-3a26-40d2-b333-1e92e956e58c.png">

Minecraft Version: 1.18.1
MySQL: true
BungeeCord: true

**Comment by TheIntolerant** [comment]
Hey, just for clarification, when you say "messages" are you referring to chat messages or private messages (/msg, /reply etc)

Also could you upload ur debug file, just type /chc debug, to generate this file.

**Comment by FinlayHDev** [comment]
"Private Messages"

Debug File:
https://ufile.io/y42nru2z

**Comment by TheIntolerant** [comment]
It seems your format files for /msg are empty, which is why the messages are blank.

**To fix this issue, do the following:**

1) Find the ``pm-receiver.yml`` and ``pm-sender.yml`` files, inside ``plugins/ChatControlRed/formats``

2) Inside ``pm-receiver.yml``, it should look like [this](https://pastebin.com/ydeUQhiX)

3) Inside ``pm-sender.yml``, it should look like [this](https://pastebin.com/9GSCU2BR)

**Comment by FinlayHDev** [comment]
Thanks
