### ISSUE TITLE
1.18.2: DiscordSRV issues

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1793]
Got a few questions/issues:

1.) When I have DiscordSRV installed, if I have it set to Enabled: false in settings.yml then it works but with some problems. So I enable it, and it is only accepting the {message} placeholder from my chat.yml. It works fine from Minecraft > Discord, but from Discord > Minecraft then it won't show the Discord user's name. It only seems to listen for/accept the {message} placeholder and any static text next to it. The {name}, {player_nick} and the rest of the things in my chat.yml are fully ignored.

2.) Trying to use the variables section with JavaScript to essentially make an "anti-autoclicker". Basically if a player hasn't typed a message or command in X minutes, it will run a command. Could be to bring up a GUI, kick them, etc
Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by HorusApl** [comment]
chat.yml: https://www.toptal.com/developers/hastebin/owepehuwuy.php

settings.yml: https://www.toptal.com/developers/hastebin/atakaleqaz.yaml

**Comment by HorusApl** [comment]
![image](https://user-images.githubusercontent.com/64336395/158561629-4553eeb5-23a6-40de-9835-9251fcfa9f4b.png)

**Comment by ElBananaa** [comment]
Hey,
Your first issue is related to #1790 so let's continue there about it.
I don't understand your second point, ChatControl is a chat-management plugin, not a GUI creator or an Anti-Autoclicker plugin ^^

**Comment by TheIntolerant** [comment]
Regarding the first issue mentioned after looking through both issues, it seems this is being caused by the issue noted #1720 in regards to the the placeholder ``{player_nick}``

-----

Now regarding the second issue as mentioned above normally people would not use a chat plugin for such things however it would be possible with Chatcontrol to make a javascript variable inside a timed message with a delay of 60 seconds etc which is how often this anti-autoclicker you have setup runs a check using the timed messages within chat control.

Also note, this won't work as intended if you have "timed" messages to stop on the first-match.

Assuming you have the javascript working so that it returns "true" when a player hasn't typed a message or command in X minutes. Than all you would need to do, is add a timed message group with a setup like this:

```
group anti-autoclicker
require receiver script {anti-autoclicker}
then kick You have been afk for...
delay 60 seconds
message: 
- none
```
Note the "delay" is how often this is checked and you could replace 
``then kick You have been afk for...`` 
with something like 
``then command <command>`` 
if you have a command that opens a GUI etc.

**Comment by kangarko** [comment]
Thanks guys for helping out. The next release will also patch some other, possibly related issues, let me know below if you will still need help as of the next release.
