### ISSUE TITLE
1.18.2: Add support for MythicMobs v5 (API Changes causing errors when killed by a mythicmob)

### ISSUE THREAD

**Issue by MusicTW** [kangarko/ChatControl#1796]
Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8304558/debug.zip)

**Comment by ElBananaa** [comment]
Hey,
The issue is due to MythicMobs API including numerous major changes in their API for v5. It appears we don't support the new versions of MythicMobs yet.

@kangarko You can find the new API methods on their github https://github.com/xikage/MythicMobs-API-Examples/ as their javadocs haven't been updated to MythicMobs API V5 yet.

**Comment by kangarko** [comment]
Thanks, looks like a larger scale update, I've asked the author to save time: https://github.com/xikage/MythicMobs-API-Examples/issues/2

**Comment by kangarko** [comment]
Added!
