### ISSUE TITLE
1.18.2: Players not listed in channels

### ISSUE THREAD

**Issue by pupshadow** [kangarko/ChatControl#1818]
Minecraft Version: Paper 1.18.2
MySQL: false
BungeeCord: false

"Issue at hand"

When using the command /ch list  its not showing players in any channel.
![not showing players in channels](https://user-images.githubusercontent.com/35120956/159795698-e98b2771-4784-40d5-9804-0efd8299b0c1.jpg)

"Debug file"
https://ufile.io/x6qtjez8

**Comment by ElBananaa** [comment]
Hey,
According to your debug file there are only 2 online players.
Are these players in vanish? (Seems like, you, at least, are in vanish as we can see a particle on the screenshot).
If so, then I believe this is an intended behavior.

EDIT: After running tests, it appears this issue happens when using the flat file database.

**Comment by pupshadow** [comment]
I was the only one in vanish since I was running test before making the bug report.

**Comment by ElBananaa** [comment]
@kangarko Could you please have a look?
I did run tests and I'm able to reproduce the issue. It only happens when using a flatfile database.

**Comment by kangarko** [comment]
Thanks, will be patched!
