### ISSUE TITLE
Player delay (suggest)

### ISSUE THREAD

**Issue by D3BoxOfficiel** [kangarko/ChatControl#1846]
Hey, possible to add a message to indicate the remaining time before the next execution?
player delay 2700 seconds (message <delay>)

**Comment by kangarko** [comment]
I believe you can already customize this using our localization file, please see the appropriate Wiki article.

**Comment by TheIntolerant** [comment]
I believe there has been a slight misunderstanding.

From the conversation I had with this person on discord, they were actually wanting to give the user a message if a rule is delayed using the operator ``player delay`` plus a possible placeholder like ``{player_delay}`` to show how long till the player delay ends.

I will show some use cases for this...

Basically i will show examples with player delay for the command "/pvp" for every 60 seconds and if the player delay is active it will send the user this message: "&cYou need to wait {player_delay} to use /pvp again."

Where a placeholder {player_delay} would return the time till the rule is active again

So the actual output might look like
"&cYou need to wait 43 seconds to use /pvp again."

Both examples would require a new placeholder ``{player_delay}`` to show how much time is left for the player delay.

---

EXAMPLE 1
```rust
match ^\/pvp\b
player delay 60 seconds &cYou need to wait {player_delay} to use /pvp again.
then title &eWelcome to the|&e&lPVP Zone
dont verbose
```
> In this example the message in ``player delay`` is only sent if the player delay is active

---

EXAMPLE 2
```rust
match ^\/pvp\b
require player delay 
then warn &cYou need to wait {player_delay} to use /pvp again.
dont verbose

match ^\/pvp\b
player delay 60 seconds 
then title &eWelcome to the|&e&lPVP Zone
dont verbose
```
> In this example we use an operator ``require player delay`` to show a message if a rule has been delayed.

---

I feel like example 1 might be easier code wise to implement, however the benefit of example 2 is you could use ``then bossbar`` etc instead of a message in chat. Though I am not sure of which option would work better.

Anyway hope that clears this up!

**Comment by kangarko** [comment]
Thanks, I've implemented {player_delay}, could you please add this to our Wiki > Rules into the player delay operator? This will however not print any time duration so players can easily translate it, for example:

`&cYou need to wait {player_delay} second(s) to use /pvp again.`
