### ISSUE TITLE
Suggestion for less lag

### ISSUE THREAD

**Issue by Chumb3x** [kangarko/ChatControl#1891]
Hi, how is it going? so I have a suggestion for you. Since t"ChatControlRed::Event: org.mineacademy.chatcontrol.listener.PlayerListener (PlayerQuitEvent)" event is the most laggiest and laggs the server most, why wont you have a option to disable it, If it's not that important. I don't even know what it does so yeah. Maybe I'm saying something stupid.

**Comment by ElBananaa** [comment]
Hey, wrong format, I'm closing this issue.
(We've already warned you multiple times on your past issues, we will now close any issue not following the formats)

Please open a one issue with :
- The appropriate format and a proper title
- Provide us a timings report and a spark profiler report, we can't change something because it "is the most laggiest" if we don't have proofs that it is, and that it's not related to your setup.
- Provide us an up-to-date `/chc debug` file

**Comment by kangarko** [comment]
It's the most important event to save player data and clean up to prevent memory leaks. Otherwise you'd end up with players not seeing their saved chat colors, nicks etc. We've already done a handful of optimization when using a database, please consider using mysql instead of data.db
