### ISSUE TITLE
[10.11.4] Messages in localization not capitalized

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1909]
![image](https://user-images.githubusercontent.com/87967222/170284534-65d8fed1-dccf-4b59-8698-9b0b86110d68.png)
![image](https://user-images.githubusercontent.com/87967222/170284587-ae8255f2-3755-4d0f-aa13-0386fc3c93ef.png)
The "s" is not capitalized even though it should be. This happens only in few messages.

**Comment by ElBananaa** [comment]
Related to #1866.
Can reproduce, seems like this only happens when you add symbols before the first word.

**Comment by kangarko** [comment]
Yes, these messages are a little bit special because we intelligently combine two messages into one if both color and decoration is set. 

If I would disable automatic lowercase and capitalization, then the other "Set your decoration" would have a capital S: 

https://i.imgur.com/4tRRxYK.png

The capitalization system cannot recognize that you put something in front of the first word such as your prefix, this is a technical limitation.
