### ISSUE TITLE
1.19.1 - Option to disable Microsofts Chat Reporting  

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1946]
Quick overview for those not in the loop:
https://www.reddit.com/r/Minecraft/comments/vitzzf/java_chat_reporting_from_the_perspective_of_a/

Full article:
https://help.minecraft.net/hc/en-us/articles/7149823936781

There are already some plugins that disable cryptographic signatures already;
https://modrinth.com/mod/no-chat-reports

Please can you add the option to do the same, so we are not forced into this situation with false player reports. 

https://www.youtube.com/watch?v=hYAUEMlugyw

**Comment by ElBananaa** [comment]
Hey,
The modrinth link is for a mod, not a plugin.
I believe making such modifications would require a major rewrite of the whole message handling, and could lead to breaking features such as the player message purge command.

Kangarko will most likely give you a more detailed answer, but honestly I doubt this is something he can work on.
Imo, if such features needs to be added, it should be done by spigot/paper, like the online/offline mode option.

EDIT : I actually may be wrong. I completely forgot this point, but I believe Kangarko uses his own message handling system in ChatControl, which means it's possible that the new report system may already not work when our channel feature is enabled. Once again you should wait for kangarko to confirm this.

**Comment by kangarko** [comment]
That's sick. I try to avoid the word "hate" as much as possible but I hate where our society is heading with this. I am just waiting for my discord server to get suspended for the suspension of promoting LGBT propaganda and other nasties.

Since we handle chat in a completely customized way, I believe this should already not work, although I haven't tested this, can you do me a favor on the next version and report whether you are still able to report these messages? Thanks.

**Comment by kangarko** [comment]
That's sick. I try to avoid the word "hate" as much as possible but I hate where our society is heading with this. I am just waiting for my discord server to get suspended for the suspension of promoting LGBT propaganda and other nasties.

Since we handle chat in a completely customized way, I believe this should already not work, although I haven't tested this, can you do me a favor on the next version and report whether you are still able to report these messages? Thanks.

**Comment by ElBananaa** [comment]
> That's sick. I try to avoid the word "hate" as much as possible but I hate where our society is heading with this. I am just waiting for my discord server to get suspended for the suspension of promoting LGBT propaganda and other nasties.
> 
> Since we handle chat in a completely customized way, I believe this should already not work, although I haven't tested this, can you do me a favor on the next version and report whether you are still able to report these messages? Thanks.

I believe the problem is that you can't really know if the report did "work" or not, as no matter what you're trying to do, you will still be able to submit a report.

Paper denied a feature request about adding a similar feature. But it should apparently already break due to how spigot handles this : https://github.com/PaperMC/Paper/issues/8043
