### ISSUE TITLE
Chat spam

### ISSUE THREAD

**Issue by YellowZaki** [kangarko/ChatControl#196]
You can't repeat two similar messages but you can tell for example: Helloooo, then type any letter like: f, and finally repeat again Hellooooo. So users bypass the chat spam system.
Please help.

**Comment by kangarko** [comment]
Hey,

I can advise to create a chat rule (rules/chat.txt) that will remove the duplicated characters: Hellooooo --> Hello. That way, you can increase the effectiveness of the antispam.

    # Example of limiting repeating characters to four repeats maximum.
    match (.)(?=([a-z])\1{3})
    then replace

**Comment by YellowZaki** [comment]
The problem is not the repeated characters. I want to block the similar messages.
Example:
-Player types: "Come to my shop /warp username"
-He tried to repeat the message again, but he can't
-Player types: "a"
-Player can type again: "Come to my shop /warp username"

**Comment by YellowZaki** [comment]
I would like to establish time between similar messages

**Comment by kangarko** [comment]
You can prevent similar messages at **Anti_Spam.Chat.Similarity_Message_Check_Count**, and set the time between messages at **Anti_Spam.Chat.Delay_Between_Messages**.

**Comment by kangarko** [comment]
Closing, if you have any more question feel free to write below.

**Comment by YellowZaki** [comment]
But I would like to set the time for similar messages, not for all messages.

**Comment by kangarko** [comment]
Yes, that aforementioned option is for similar messages, because the filter itself is for similar messages.

**Comment by YellowZaki** [comment]
No, it works for all messages, not only for similar messages.

**Comment by kangarko** [comment]
Well, ChatContol has only this option to prevent similar or exact messages (Anti_Spam.Chat.Delay_Between_Messages). 

The way it works is this: You can set in how many percent the present message

**Comment by kangarko** [comment]
Well, ChatContol has only this option to prevent similar or exact messages (Anti_Spam.Chat.Delay_Between_Messages). 

The way it works is this: You can set in how many percent player's present message is similar to his last one, to block it. Iff you set it to '100', it will be disabled. If you set it to 99, only exact messages will be blocked. If you set it to for example 70, messages that are similar 70% **or more** to their last ones will be blocked. You can't only block similar messages and not exact messages, because that's inherited within the filter.

**Comment by YellowZaki** [comment]
Anti_Spam.Chat.Delay_Between_Messages doesn't take into count the Similar_Percentage_Block, it will set a delay in seconds for all chat messages. It doesn't mind if they are more or less similar.

The only way to block similar messages is Anti_Spam.Chat.Similarity_Message_Check_Count but it works depending on the number of chat messages. If Similarity_Message_Check_Count=3, you will not be able to chat a similar message within you have send 3 messages. This option does take into count the

**Comment by YellowZaki** [comment]
Bump! @kangarko

**Comment by kangarko** [comment]
Hey,

I am sorry I must've totally missed you message. Thank you for reminding me.

Yes, **Delay_Between_Messages** and **Similar_Percentage_Blocks** are two totally independent options. This is intended because not everybody wants to use both of them, so it is possible to just enable one. That is why they do not see each other's result.

**Similar_Percentage_Block** and **Similarity_Message_Check_Count** are linked. The first option specifies how much the player's messages must be similar in percent to player's previous message. The second option sets how far in the player's history of messages we should go to evaluate. Then, each of player's previous messages is evaluated independently against Similarity_Percentage_Block.

I've made a quick graph to illustrate the logic better:

![pic](https://i.imgur.com/ff6oUk9.png)

**Comment by kangarko** [comment]
I am closing this, please let me know if you have any more questions.
