### ISSUE TITLE
[Suggestion] Make data.db reloadable

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#1991]
Since while using database, there is a memory leak, I'd like data.db file to reloadable, because the higher its size is, the more the server lags (0.2% up to 5% cpu usage in spark). Even when I rewrite data.db and use /chc reload, it doesn't work. The only way to rewrite data.db right now is after server restart.

**Comment by kangarko** [comment]
data.db is not intended to be edited, it is managed by the plugin internally.

Can you please share with me your big data.db so I can test the performance issues?

**Comment by Teslicek** [comment]
Since I have 150-200 players online most of the time, when using data.db, its file size increases dramatically over time (400KB each day). Each time the file size is larger, `PlayerListener.onJoin()` and `PlayerListener.onQuit()` take more and more cpu usage (recorded in spark). When using database or when resetting data.db, those two functions are not even present, meaning they do not lag the server at all.

Anyway, if you still want my data.db, which has 270KB (it took 15 hours from 0KB), here you go.
[data.zip](https://github.com/kangarko/ChatControl-Red/files/9141347/data.zip)

**Comment by kangarko** [comment]
Can you wait until it's over 1MB so I can test with a significant data please?

**Comment by Teslicek** [comment]
I unfortunately cannot do that, because the server would run out of RAM or would lag too much with such file size.

**Comment by kangarko** [comment]
Since database problems were fixed you are encouraged to use that instead now :) Due to concurrency issues in the past we are now always saving/reading the data.db file in the main thread, which, if the file is excessively large, will always produce a spark report.

I have also added the option Channel.Save_To_Database which will further reduce the file/db size in case you only have one channel and join everyone there when they enter the server.
