### ISSUE TITLE
[10.12.7] Another Database Memory Leak

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2011]
Yes, there is another ChatControl-Red database memory leak.

I think that Kangarko is still not closing database connections properly, which is resulting in old garbage collection, a lot higher cpu usage (over time) as well as server crash.

This issue does not happen when using data.db file.

**Comment by kangarko** [comment]
Thanks and sorry to hear. I moved the remaining two statements about loading mails and player data into an auto-closeable block.

It's pretty hard for me to find this bug since I can't reproduce it (because I have a 1-person test server most likely so it never gets overflooded). Next time if you have any crash dumps or logs please provide them as they are always helpful.
