### ISSUE TITLE
Leave Command

### ISSUE THREAD

**Issue by Tazler89** [kangarko/ChatControl#2013]
when using leave command i.e /ch leave global it removes you from all channels not just the one, i can be in 6 channels in read mode and it will remove me from them all.

**Comment by ElBananaa** [comment]
Hey,
Please update your message to match the issue format, or open a new one, and provide all the requested informations.

**Comment by Tazler89** [comment]
as far as i know i have submitted this correctly, and given all details i have, if the problem seems to hard for you to look into please tell me what it is your needing as your above message is not detailed to what your asking for what so ever

**Comment by ElBananaa** [comment]
This is how your issue is supposed to look like, so we can already have as much informations as possible about your environment.
![image](https://user-images.githubusercontent.com/53318613/181123073-c784a96e-9d1c-41d7-9dc1-23b93419a9de.png)
(Providing us a debug file isn't necessary, and if it is, but you'd like to keep it private, you can simply send an email to support@mineacademy.org including the debug file and a link to the github issue).

**Comment by Tazler89** [comment]
Fully updated chatcontrol 10.12.7
paper 1.19
all plugins updated
new server no players in build
 issue:
when using leave command i.e /ch leave global it removes you from all channels not just the one, i can be in 6 channels in read mode and it will remove me from them all.

don't have any dumps or debugs, you will have to mind i have never had to submit an issue before most plugins i use i helped develop directly with them, so all ways have direct message with them for any problems i get as i test alot of plugins

**Comment by kangarko** [comment]
I cannot reproduce I am sorry:

![a](https://i.imgur.com/FaoPnGK.png)

I was joined in all channels on the server in read mode, then typed /channel leave global and I am still joined in the other channels. Make sure there is no automation, rule in rules/ or a script that is merging this command or that may be causing a conflict.
