### ISSUE TITLE
priority problem

### ISSUE THREAD

**Issue by YrChen1001** [kangarko/ChatControl#2015]
When I use InteractiveChat to send a item to show, like I use [item] that will show the item to everyone
That ChatControlRed's chat priorities block it to show, can't parse the item
But when player use private to send it , that can work. I don't know why.
Below are the InteractiveChat priority settings
![image](https://user-images.githubusercontent.com/99790174/180795821-f3fa5cf9-152f-4228-95f2-278b7b721966.png)
And I set ChatControlRed's priority to LOWEST, that still not work on global chat

Minecraft Version: 1.19
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
Hey,
I don't think there's anything that can be done here. When using our channel feature, chatcontrol completely overwrite the existing chat system so we can take advantage of features like the X message removal.

So this is most likely an incompatibility with InteractiveChat. If the owner of the plugin wants, I'm pretty sure Kangarko wouldn't mind proving them access to chatcontrol so they can try to work on getting this issue fixed together.
@kangarko

**Comment by YrChen1001** [comment]
now, it's work ingame , but not work on discord channel. (I changed InteractiveChat's chat priority to lowest)
Does that can compatible?

**Comment by YrChen1001** [comment]
![image](https://user-images.githubusercontent.com/99790174/181191192-66ff4b16-7e02-4a51-8743-0e9212b5b79f.png)

**Comment by kangarko** [comment]
They can contact me for a free copy, but I don't think it can be solved as we handle both discord and chat in our own way.

**Comment by YrChen1001** [comment]
Did you see this?
![image](https://user-images.githubusercontent.com/99790174/182063886-c8d3a410-e902-4e06-a596-b6aa5a479b21.png)

**Comment by kangarko** [comment]
We have internal reasons for not doing that, such as that the library we rely on Foundation has hooks for other developers. I don't think they are willing to hook into it manually.

**Comment by YrChen1001** [comment]
oh , so that can't be done

**Comment by kangarko** [comment]
Everything can be done, unfortunately my plate is full at the moment and you are the only person having this issue in years. Hope you understand.

**Comment by bobhenl** [comment]
@kangarko How this issue seems please?

As I see it looks there are multiple people having this problem. Can you look at it, please? It's being delayed a long time now.

<chat=a4e11efc-7feb-4e2a-acb5-4b642438f6a7:[item]:> This is what we get. If I disable chatcontrol Discord, how can then I enable sending messages into my standard chat? From some reason it doesn't work.

https://github.com/kangarko/ChatControl-Red/issues?q=is%3Aissue+interactivechatis%3Aclosed+ look how many tickets with this is here on this github already

**Comment by kangarko** [comment]
Thanks, sorry, I did not have a look because I was quite busy. To help me, can you please tell me the exact steps to reproduce and upload your chatcontrol "/chc debug" ZIP file so I can test it myself and do it quicker? Thanks again.

**Comment by YrChen1001** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9478330/debug.zip)

**Comment by bobhenl** [comment]
Not sure who debug you meant, but I'm sending it as well.

So, there are two problems, I've opened separate ticket on supporting InteractiveChat Discord.

First problem is that when you use [item] [ender] [inv] etc. then it's not set to your Discord, you see just this <chat=a4e11efc-7feb-4e2a-acb5-4b642438f6a7:[item]:> if you use InteractiveChat DiscordSRV addon.

Otherwise when I've disabled integration with Discord in CHC and tried to send message from Discord to game, there was message that it's sending in console but it wasn't shown in a chat! So CHC somehow cannot display it into chat without Discord integration enabled, although the messages from Minecraft to Discord were normally sent. Just anote, when I've disabled CHCR Discord integration I've used standard DiscordSRV MC to Discord chat probably.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9478867/debug.zip)

If you want some more help, just free to message me on Discord Renzotom#6586.

**Comment by kangarko** [comment]
I will collaborate with that plugin's developer and be happy to resolve this asap for you (and others), let's continue on the other ticket!

@bobhenl I have tried it myself, after setting our event priority to HIGHEST the [inv] variable started to work normally: 

![a](https://i.imgur.com/gkZ0mkJ.png)

**Comment by bobhenl** [comment]
Yeah but this was meant as Discord issue, in chat it works, but on Discord it's not sent properly @kangarko

**Comment by kangarko** [comment]
Cool, so lets follow up on the discord problem in the other ticket you opened.
