### ISSUE TITLE
[Question] What is ChatControlRed?

### ISSUE THREAD

**Issue by tomhula** [kangarko/ChatControl#202]
Ok, so I am getting very confused about ChatControlRed and have many questions about it:

Is it free?
Why isn't it on SpigotMC?
Why are you still offering the old **paid** version?
If it is paid, will I get it when I bought the SpigotMC 8.x version?
Or is it just some Beta version and will be uploaded to SpigotMC later?

Because I just bought the paid version on SpigotMC and would be very mad if this is free and better.
Thank you for explaination.

**Comment by ElBananaa** [comment]
> Ok, so I am getting very confused about ChatControlRed and have many questions about it:
> 
> Is it free?
> Why isn't it on SpigotMC?
> Why are you still offering the old **paid** version?
> If it is paid, will I get it when I bought the SpigotMC 8.x version?
> Or is it just some Beta version and will be uploaded to SpigotMC later?
> 
> Because I just bought the paid version on SpigotMC and would be very mad if this is free and better.
> Thank you for explaination.

Hey! CHC Red is ChatControl 10, the plugin is currently in BETA testing phase, and it waiting for approval on spigot.
The actual version (Chc v8) will be released publicly when CHC Red is released on spigot.
Chc red won't be free, but since you recently bought it, I think Kangarko said you'll have free upgrade for chc red.

(And I'm not part of the plugin's team at all, I'm just a beta tester, I'm just giving you infos that Kangarko gave us on spigot/discord)

**Comment by tomhula** [comment]
Ok, thank you so much, I just hope I won't have to buy Red seperatly.

**Comment by OfT3N** [comment]
> Ok, so I am getting very confused about ChatControlRed and have many questions about it:
> 
> Is it free?
> Why isn't it on SpigotMC?
> Why are you still offering the old **paid** version?
> If it is paid, will I get it when I bought the SpigotMC 8.x version?
> Or is it just some Beta version and will be uploaded to SpigotMC later?
> 
> Because I just bought the paid version on SpigotMC and would be very mad if this is free and better.
> Thank you for explaination.

This is the new version of ChatControlPro

1) No, it will be paid, but technically free for now
2) See the screenshot below
3) The plugin is currently being uploaded on SpigotMC (it depends on how fast moderation will approve it)
4) If you `recently` bought it on SpigotMC, you will get the new version for `free`
5) Yeah, it is some beta version

![image](https://user-images.githubusercontent.com/62369973/100779358-5633e380-3419-11eb-9f6c-83ad97e4f18d.png)

**Comment by tomhula** [comment]
Ok, thank you both very much.

**Comment by kangarko** [comment]
Thanks guys for replying! Just adding my official reply, if anything is needing more clarification please let me know!

1. ChatControl Pro is ChatControl generation 8th.
2. ChatControl 9 was ChatControl generation 9th that is now deleted.
3. ChatControl Red is a brand new plugin. Internally, it says generation 10th but we rewrote everything. That's why I also decided to sell it separately.

4. ChatControl Pro and ChatControl Red will be sold separately. People who helped with Red or purchased Pro recently will get it for free.
5. ChatControl Pro will be phased out (not deleted) once ChatControl Red is stable.
