### ISSUE TITLE
Question about Chat Colours

### ISSUE THREAD

**Issue by zombwie** [kangarko/ChatControl#2046]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

when aplying chat collor it gets restet on server change. 

and how do i change the defolt chat collor from dark gray?

**Comment by TheIntolerant** [comment]
### **Why is someone's chat colour reset on server change/rejoin?**

If a chat colour is reset on server change/join this suggest a potential permissions issue. It is also possible it may be a MySQL issue but in my past experiences it is most likely a permission issue.

First thing I suggest is to double check the permissions the user has are correct, those permissions are as follows:
``chatcontrol.guicolor.{color}``
**OR**
``chatcontrol.hexguicolor.{color}``

To check if MySQL is working correctly, you can set ``Debug: [mysql]`` in your ``settings.yml`` file and apply a different chat colour, there you should see the value ``Chat_Color`` change in the console.

---

### **How do I change the default chat colour?**
The default chat colour is determined by your format, example:
This will make my default chat colour, white, because of the ``&r`` used in this format.
```yml
  message: 
    Message: "&7: &r{chat_color}{chat_decoration}{message}"
```

**Comment by TheIntolerant** [comment]
Assuming this issue has been resolved I'm going to close this, but if this is still an issue just comment below and I'll open this issue again
