### ISSUE TITLE
Mitigate the crash being caused by NoEncryption

### ISSUE THREAD

**Issue by malonnnn** [kangarko/ChatControl#2058]
### Summary

There was a recent topic regarding /msg not working, and I've finally tracked down the issue to NoEncryption (at the time I wasn't sure what was causing it).

They have a thread on my issue here, scroll to the bottom you can see multiple people reporting it:
https://www.spigotmc.org/threads/noencryption.562043/

The suggestion would maybe be to build NoEncryption functionality directly into ChatControl, since they seem to be slow/not responding to the issue.

The easiest way to reproduce, is to go to the system console and type "say test" which normally makes the console print "test" to chat, but instead it kicks all players.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

We would just simply have to wait for NoEncryption to update

**Comment by TheIntolerant** [comment]
Adding NoEncryption functionality into chatcontrol is not needed as long as you use chatcontrol's channel system, private message etc since these messages are sent as "system messages" thus cannot be reported.

Here I send a private message using chatcontrol ``/msg`` (top) and than again but with vanilla ``/minecraft:msg`` (bottom)
![image](https://user-images.githubusercontent.com/48093184/184238980-e67a0cd1-876e-4147-9167-8e46a0b56c5f.png)
As you can see, there is a gray line on the chatcontrol private message, this means that is a "system message" therefore it cannot be reported, the vanilla private message however can be reported.

---

I confirmed this by pressing ``P`` and only the private message sent via the vanilla command was reportable, so as long as people use chatcontrol's messaging systems those types of messages will be treated as a system message when chatcontrol is the plugin handling those types of messages

By "chatcontrol's messaging systems" I mean these features ``/me``, ``/msg``, ``channels`` etc

---

Of cause the dev of Chc may still choose to add this feature, I just wanted to make it known that isn't needed as long as people use chatcontrol's channel and private message features etc, all those messages will be treated as system messages and therefore cannot be reported.

**Comment by kangarko** [comment]
Uninstall NoEncryption, we send all messages as system chat so that they cannot be reported. Thank you!
