### ISSUE TITLE
1.19: My plugin's custom placeholders are not showing up.

### ISSUE THREAD

**Issue by AndrewKosatka** [kangarko/ChatControl#2103]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

**Inside my plug-in, there are some custom placeholders, which when the plug-in is activated are automatically registered in PlaceholderAPI**. They work with the command `/papi parse me...` and with other plug-ins, but with **ChatControlRed**, they are not shown. The text `{identity_fullname}` remains in Chat (Added through the _format yaml_ file). Could you help me?

SourceCode:  https://github.com/AndrewKosatka/Identity

**Comment by ElBananaa** [comment]
Hey,
Could you please try to run `/chc info variables <yourNick> {identity_fullname}`? If it doesn't work, try with `%identity_fullname%` and give us the output of the commands

**Comment by kangarko** [comment]
Yes because {identity_fullname} is wrong, you had Identity as identifier and our plugin was case sensitive. Typing {Identity_fullname} would work.

Given the fact that other plugins may be case sensitive too I recommend you rename it to all lowercase.

I have made ChatControl case insensitive from the next release
