### ISSUE TITLE
Previous owner of ChatControl Pro

### ISSUE THREAD

**Issue by EchocallingEarth** [kangarko/ChatControl#2104]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

We recently discovered that ChatControl was not in fact dead as it was assumed some time ago.  This discovery is the result of the partnership with ItemsAdder.  Our question is how do we take advantage of the free upgrade offered? The links are dead, which is a bit disconcerting, so we are reaching out here. 
Please respond with instructions so we can continue using ChatControl and all its great features. 
Thank you very much Co-Owner FWS Servers

Note the purchase was made via the owner so he would be providing the requested info. If he should instead open a ticket please also let me know So I can request (TimmyT0yz- owner FWS Server) Tim promptly do so.

You may reach out to me here, via discord EchocallingEarth#0001, or email at admin@friendlyworldserver.com

Again thank you in advance.

**Comment by ElBananaa** [comment]
> ### Are you using MySQL?
> No
> 
> ### Are you using BungeeCord/Velocity?
> No
> 
> ### Question
> We recently discovered that ChatControl was not in fact dead as it was assumed some time ago. This discovery is the result of the partnership with ItemsAdder. Our question is how do we take advantage of the free upgrade offered? The links are dead, which is a bit disconcerting, so we are reaching out here. Please respond with instructions so we can continue using ChatControl and all its great features. Thank you very much Co-Owner FWS Servers
> 
> Note the purchase was made via the owner so he would be providing the requested info. If he should instead open a ticket please also let me know So I can request (TimmyT0yz- owner FWS Server) Tim promptly do so.
> 
> You may reach out to me here, via discord EchocallingEarth#0001, or email at [admin@friendlyworldserver.com](mailto:admin@friendlyworldserver.com)
> 
> Again thank you in advance.

Hey,
It indeed looks like the upgrade link is dead, thanks for reporting it. **<---** @kangarko 
In order to get your license back, please send an email to support@mineacademy.org with the following information:
- The paypal email used to buy the plugin
- The paypal invoice id
(You can also provide a copy of the full invoice directly)
- A link to your current BuiltByBit profile page

Then you simply have to wait, Kangarko will reach you via email once he gave you back access to the plugin (This usually takes less than a week).

Please note that ChatControl-Red is a complete rewrite of chatcontrol-pro, which means it includes a lot of new features. There is a migration system to help you properly upgrade to chatcontrol-red, however, we also highly suggest you take a deep look at our wiki.

Finally, if you urgently need ChatControlRed, feel free to join our discord server https://discord.gg/SAYYKRvjQZ and send me a dm with a copy of the invoice, i'll provide you the latest version of the plugin so you can already start working on it until Kangarko approves your upgrade request.

**Comment by kangarko** [comment]
Thanks @ElBananaa,

We have since created a fully automated migration you can enter at mineacademy.org/upgrade and get new access to Red instantly.
