### ISSUE TITLE
1.19.2: Prevent_Spying breaks DiscordSRV chat forwarding to discord.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#2117]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!
ChatControl-Red v10.13.9

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9591682/debug.zip)

### Information about the issue/bug

I only use a single channel for a "global" chat, which is bridged by DiscordSRV and EmojiChat (for emoji handling both ways).

With this set;
```
  Prevent_Spying: true
```
DiscordSRV does not pick up on messages said in-game to forward to discord channels.

---

With this set;
```
  Prevent_Spying: false
```
DiscordSRV bridged chat works fine, however players get kicked by ChatControl with not secure invalidation client kick message whenever someone writes something in-game. Which seems to also be reported here. https://github.com/kangarko/ChatControl-Red/issues/2109 I do not use secure profiles since I support versions older than 1.19.2 via ViaVersion.

Using the AntiPopup plugin with ``Prevent_Spying: false`` _does_ seem to work around chatting kicking players.
https://github.com/KaspianDev/AntiPopup

**Comment by ElBananaa** [comment]
@kangarko
After digging a bit further into this, it appears this only happens when `Integration.Discord.Enabled` is set to `false`.
I then enabled DiscordSRV debug mode, and it appears the plugin doesn't send messages to discord if the `AsyncPlayerChatEvent` event is canceled. DiscordSRV authors also appears to be against cancelling the chat event.
```
[18:10:33 INFO]: [standard] ElBananaa: test
[18:10:33 INFO]: [DiscordSRV] Plugin ChatControlRed v10.13.10 cancelled AsyncPlayerChatEvent (Bukkit) (author: ElBananaa | message: test)
[18:10:33 INFO]: [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] Chat message received, canceled: true, channel: standard
[18:10:33 INFO]: [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] User ElBananaa sent a message but it was not delivered to Discord because the chat event was canceled
```

There is an hidden option, `RespectChatPlugins` which can be set to `false` in discordsrv config.yml file to fix this, however they clearly stated that this should never be disabled on production servers.
Not canceling the event here also fixes the issue, however the message is printed twice in the console: https://github.com/kangarko/ChatControl-Red-Src/blob/master/src/main/java/org/mineacademy/chatcontrol/listener/ChatListener.java#L212

Finally, the author of #2097 told me on discord that the `Prevent_Spying` feature seems to break from time to time, kicking all their players (this is not related to DiscordSRV).
Apparently, plugins like [FreedomChat](https://github.com/e-im/FreedomChat) seem to work fine with discordsrv handling messages. The only downside is that they don't get rid of the `[Not Secure]` chat prefix.

**Comment by kangarko** [comment]
Thanks, that is a wontfix issue. The Prevent_Spying option will cancel the chat event, which has unwanted consequences like that one, but is fine as long as we take over the chat and Discord. This option will need to be disabled if the user above does not want to use our Discord to format his chat.

**Comment by mibby** [comment]
Ah, I see. Bit of a shame it won't be fixed since I can't use ChatControl's native discord integration since it does not forward / translate emojis from EmojiChat plugin properly.

**Comment by kangarko** [comment]
Can you try disabling Prevent_Spying and using an alternative plugin for that purpose such as FreedomChat that Banana suggested?
