### ISSUE TITLE
1.19: Server Hangs With CHC installed

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2120]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/5d138c32ed7944cb88ca609168855ea5

### "/chc debug" output (strongly recommended)

Sent in email

### Information about the issue/bug

I have CHC installed, the server will periodically kick all members as seen in the bottom of the log WatchDog error.

**Comment by kangarko** [comment]
Seems like we are trying to decipher a message using protocollib and that takes too long, I assume this is caused by your third party plugins inserting some long json stuff into it or protocollib incompatibility as we have not seen crash reports like this previously.

I am going to investigate this though.

To eliminate this issue you can disable protocollib hook and packet rules by setting Integration.ProtocolLib.Listen_For_Packets to false in settings.yml

Also please fix the following errors as they may affect the overall stability of your server:

[11:32:29] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "0162000877589"

[11:32:34] [Server thread/WARN]: [MiniaturePets]  A material in use for this pet is for an older version. If you have issues, update it to at least the 1.13 material! https://helpch.at/docs/1.13/org/bukkit/Material.html (ItemName:head | Material:SKULL_ITEM)

[11:50:42] [Craft Scheduler Thread - 6 - ChatFeelings/INFO]: [Essentials] Found UUID 00000000-0000-0000-0009-01f23b3632ef 
for player BR_Diamondplayz7, but player already has a UUID (00000000-0000-0000-0009-01f09aec3462). Not replacing UUID in usermap. 
java.lang.RuntimeException: null


[12:21:28] [Server thread/ERROR]: Could not pass event EntityDamageByBlockEvent to DeathMessages v1.4.15
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getSimpleName()" because the return value of "org.bukkit.entity.EntityType.getEntityClass()" is null

**Comment by TZ122** [comment]
Hey just received another crash today - Ive disabled the protocollib listen for packets as well as fixed many of the issues you mentioned above.  Any way I can prevent this from happening?

https://paste.gg/p/anonymous/0c6fc9097e9d424bab670a19d09908fa

> Seems like we are trying to decipher a message using protocollib and that takes too long, I assume this is caused by your third party plugins inserting some long json stuff into it or protocollib incompatibility as we have not seen crash reports like this previously.
> 
> I am going to investigate this though.
> 
> To eliminate this issue you can disable protocollib hook and packet rules by setting Integration.ProtocolLib.Listen_For_Packets to false in settings.yml
> 
> Also please fix the following errors as they may affect the overall stability of your server:
> 
> [11:32:29] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "0162000877589"
> 
> [11:32:34] [Server thread/WARN]: [MiniaturePets] A material in use for this pet is for an older version. If you have issues, update it to at least the 1.13 material! https://helpch.at/docs/1.13/org/bukkit/Material.html (ItemName:head | Material:SKULL_ITEM)
> 
> [11:50:42] [Craft Scheduler Thread - 6 - ChatFeelings/INFO]: [Essentials] Found UUID 00000000-0000-0000-0009-01f23b3632ef for player BR_Diamondplayz7, but player already has a UUID (00000000-0000-0000-0009-01f09aec3462). Not replacing UUID in usermap.  java.lang.RuntimeException: null
> 
> [12:21:28] [Server thread/ERROR]: Could not pass event EntityDamageByBlockEvent to DeathMessages v1.4.15 java.lang.NullPointerException: Cannot invoke "java.lang.Class.getSimpleName()" because the return value of "org.bukkit.entity.EntityType.getEntityClass()" is null

**Comment by kangarko** [comment]
Thanks, I found that the Integration.ProtocolLib.Listen_For_Packets option in settings.yml was not being respected, I will patch this in the next release asap tonight.
