### ISSUE TITLE
1.19.2: WARNING-ILLEGAL-ASYNC-ACCESS

### ISSUE THREAD

**Issue by Lorias-Jak** [kangarko/ChatControl#2121]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/9594231/debug.zip)

### Information about the issue/bug

Were using placeholder for our chat-names in the most channel. Now i tried to writ in our "reden" channel and in the chat, where the playername should be, was an error. It says "WARNING-ILLEGAL-ASYNC-ACCESS". I dont know how to solve it, in the 1.18.2 it worked perfectly

I have also updated the CHC version at the same time of the version change. From 10.13.5 to 10.13.9

![grafik](https://user-images.githubusercontent.com/62625225/190913629-44c5b242-07a9-4785-b1cc-83f7755e3c06.png)

**Comment by kangarko** [comment]
I am afraid this is something broken due to changes in PlaceholderAPI. We run the replacement on the primary thread, you will have to talk to the depenizen author about this:

https://github.com/DenizenScript/Depenizen/blob/ff6ee7ccda7a144c89fbcd3c9edcb771d8815f33/src/main/java/com/denizenscript/depenizen/bukkit/bridges/PlaceholderAPIBridge.java#L113
