### ISSUE TITLE
Regarding 'unknown packed identifier'

### ISSUE THREAD

**Issue by NoobcoreNetwork** [kangarko/ChatControl#2146]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

No

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Hey! So I know the client log spam is a known thing, But I keep getting users reporting it to me saying there's something wrong with my server and it's causing lag, (I know it isn't causing lag) but I do like to keep things clean, Is there any chance we can get this fixed? I'm getting up to 50k outputs in an hour and eventually crashing my client log,

Thanks! <3

![Discord_aNyrxJwEEj](https://user-images.githubusercontent.com/62724418/194322182-d19f36bd-7aa3-4904-b871-c7328c3e9eb3.png)

**Comment by kangarko** [comment]
Thanks, this is a known issue because the client does not recognize our "packet". @ElBananaa did you have any chance to look into this please?

**Comment by ElBananaa** [comment]
> Thanks, this is a known issue because the client does not recognize our "packet". @ElBananaa did you have any chance to look into this please?

I already made a Pr to try to solve this, but you denied it as it was apparently breaking changes for project orion students.

**Comment by kangarko** [comment]
Unfortunately, the fix was lacking and breaking any channels by others using Foundation as I mentioned.

I ended up redoing the whole system so that we use "BungeeCord" channel and insert the specific channel name as "sub channel" by means of putting it as UTF string in the data array. Full commit here:

https://github.com/kangarko/Foundation/commit/b7b7338331bc28b3ea818e0fa01022cd03ad294d

So far works, definitely more testing is needed (I tested chat, /list, /mute, /ignore etc.)
