### ISSUE TITLE
[1.19.2] [10.14.4] Incorrect chatcolor text

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2165]
### Are you using the latest version of the plugin available?

Yes, the plugin is up-to-date!

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

Typed: `/chc c #ffff00`

10.14.4:
![image](https://user-images.githubusercontent.com/87967222/196766679-50d32ac5-b163-46cb-abc9-4609b26b90e4.png)

10.14.1:
![image](https://user-images.githubusercontent.com/87967222/196766920-d60b6ce7-ca65-4188-95e3-8110369b4061.png)

The #ffff00 is missing in the new chatcolor messages.

**Comment by ElBananaa** [comment]
Thanks for reporting. This issue was introduced with the new way of handling messages in the previous version: `Improve | Replaced "/chc color" localization language keys with new keys which are 100% translateable into any language`
I have fixed this and made a PR, so this will most likely be patched in the next version.

**Comment by kangarko** [comment]
Thanks, will be fixed! @ElBananaa please see my system solution in ChatControl :)
