### ISSUE TITLE
1.19.2: Multiple options in chatcontrol.bypass.spy.x

### ISSUE THREAD

**Issue by fredagsguf** [kangarko/ChatControl#2169]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Is it possible to get a feature where each part of the spy system is divided in to individual permissions e.g:

If i wanted my helpers to see what my admins type in msg, i would give the admins these perms:
- chatcontrol.bypass.spy.chat
- chatcontrol.bypass.spy.command
- chatcontrol.bypass.spy.mail
- chatcontrol.bypass.spy.sign
- chatcontrol.bypass.spy.book
- chatcontrol.bypass.spy.anvil

And avoid giving admins the permission: **chatcontrol.bypass.spy.msg**

Not sure if this is possible already?

**Comment by TheIntolerant** [comment]
Currently, there is only one permission ``chatcontrol.bypass.spy``, though this would be a good addition! Having better control over what spy features are enabled for specific users and what spy features people can bypass, would be amazing!

---

### Note for Developer 
A similar suggestion has been made in the past as seen in #1924 & #529

The suggestion I made (#529) addresses all the permission nodes that may need to be looked at for this to work effectively. Also, #1924 Makes a good case as to why there should be finer control of the spy system but was denied due to lack of time.

**Comment by kangarko** [comment]
Thank you for your suggestion! I am monitoring this and will consider pulling this into production in the future, however at present my time is quite limited.

**Comment by BakiDance** [comment]
Given that some time has passed since this issue was closed, is there still possibility of this being implemented? Due to #1924, ALL staff on my server have access to social spy (yikes!).

It's unfortunate that almost a year later there isn't a better solution than giving all staff members social spy.

**Comment by TheIntolerant** [comment]
Another person has requested/made an enquiry about spy![image](https://github.com/kangarko/ChatControl-Red/assets/48093184/f8a39d98-df5e-4a92-a83e-dd11ff5f292f)

**Comment by TZ122** [comment]
This would be an amazing addition for the flexibility of the spy feature in the plugin. I hope to see this added one day

**Comment by kangarko** [comment]
@TheIntolerant would you be able to add this? You should have access to CHC source code if I am not wrong :) Thanks!

**Comment by TheIntolerant** [comment]
> @TheIntolerant would you be able to add this? You should have access to CHC source code if I am not wrong :) Thanks!

Unfortunately this is something I wouldn't feel comfortable implementing myself due to my lack of experience with coding

**Comment by kangarko** [comment]
@TheIntolerant no probs, I found the time and added this :)
