### ISSUE TITLE
1.19.3 Using MMOitems along side CCR

### ISSUE THREAD

**Issue by Dracathio** [kangarko/ChatControl#2238]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

So I'm just here to ask a question really, how would Chat Control Red effect a command line for a plugin that does item creation like MMOitems?

So I was forced to disable Chat Control Red just to add an enchant onto an item using their ingame item creation feature, I wanted to know if this is really a CCR side issue or if it's a MMOitems side issue.

**Comment by TheIntolerant** [comment]
Could you explain why you had to disable ChatControlRed, to add the enchantment?

**Comment by Dracathio** [comment]
I have no clue, something about how the MMOitems can't read the commands for creating custom items,  the data being put in for the items, etc.  No dang clue really.

Moment I disabled CCR I was able to add the enchant. The guy at MMOitems says it's something with CCR, but I believe it's just that MMOitems hasn't figured out how to deal with chat plugins like others have figured out.

**Comment by TheIntolerant** [comment]
Assuming the incompatibility this specific plugin is making you type in chat instead of via command.
The example you type the command, then in chat, it asks what level enchant you want and you type it in chat, etc.

Have a read through <https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities> and see if changing this setting and then restarting your server fixes the issue.

Also, make sure to check MMOitems to see if they have a Listener_Priority setting (or something similar) as you may need to change that too.

**Comment by kangarko** [comment]
Also you could have tried removing the [item] variable from variables/ folder or disabling our protocollib integration in the Integration section of settings.yml
