### ISSUE TITLE
1.19.3: Deathmessages often throws an error

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#2245]
### "/version ChatControlRed" - plugin version

ChatControlRed version 10.16.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/ue5uaGDq

### "/chc debug" output (strongly recommended)

More details to be found on your email.

### Information about the issue/bug

The deathmessages do not always work, often they throw an error in console and show the default minecraft death message.

**Comment by ElBananaa** [comment]
What is your mythicmob version?
Make sure to update to the latest version to see if this happens again.

**Comment by kangarko** [comment]
I am already working with a customer over the same issue via email, it should be fixed in 1-2 days. Thanks

**Comment by TZ122** [comment]
Hey I thought I would add in this that it happens to me without using mythic mobs death messages. (I commented them out / removed them)

Happens to me while using {killer}, mob kill and player kill

https://pastebin.com/TRFNEL0p

**Comment by Sikatsu** [comment]
I do actually have the same error on purpur 1.19.3 @kangarko

**Comment by kangarko** [comment]
So sorry guys. Did not come up in my testing so I rewrote how we integrate with that plugin directly instead of using reflection: https://github.com/kangarko/Foundation/commit/5d4d8c82847c028801a0d0e9b9094b9e241900f2

Again I tested with success, but let met know if anything pops out perhaps the error will now be more indicative as for some deeper issue.
