### ISSUE TITLE
Packet replace removes color from message

### ISSUE THREAD

**Issue by Tsuser1** [kangarko/ChatControl#228]
So, due to another issue I was attempting to get emojis working (Rules in chat.txt and rules.txt didn't work due to Herochat which needs integration with ChatControl) and I was forced to use packet rules. However, when I added the rules, I was stunned to see this:

[Click to view screenshot](http://imgur.com/a/dgTT6)

So, if the issue isn't immediately apparent, where did the color go? I only used replace in the packet rules so it shouldn't of done _that_ from what I understand.

Thanks for taking the time to respond to my bugticket! 😄

**Comment by kangarko** [comment]
Hello,

thank you for using ChatControl. As per the current system, colors are removed from the message because otherwise, if players would use a color in their message, it wouldn't be matched with the rule.

Btw, ChatControl Pro has an option to disable removing the color, but keep in mind that this can lead to bypassing rules easier.
