### ISSUE TITLE
[Issue] Lag and error when removing messages

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#228]
When we remove messages, sometimes an error shows up. Players also experience lag when we do it.

https://pastebin.com/dcL1MLcZ

Also the chat scrolls up and down when performing a delete:

https://www.dropbox.com/s/csz21uewajg2vz4/Minecraft_%201.16.4%20-%20Multiplayer%20%283rd-party%20Server%29%202020-12-04%2011-13-16.mp4?dl=0

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> When we remove messages, sometimes an error shows up. Players also experience lag when we do it.
> 
> https://pastebin.com/dcL1MLcZ
> 
> Also the chat scrolls up and down when performing a delete:
> 
> https://www.dropbox.com/s/csz21uewajg2vz4/Minecraft_%201.16.4%20-%20Multiplayer%20%283rd-party%20Server%29%202020-12-04%2011-13-16.mp4?dl=0
> 
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true

I just tried on a my test server (paper 1.16.4 no bungee & no mysql), no issues, even while spamming the message delete feature. This is the worst latency I have when removing a message: `42.03 ms` But, I just noticed I get kicked for spam when I remove messages too fast.

**Comment by Sikatsu** [comment]
Hmm, I've seen it go up to 2k ms already. That's odd! There is a permission to bypass the kick for spam "chatcontrol.bypass.spamkick"

**Comment by ElBananaa** [comment]
Thanks for the permission. As I said, I don't have any issue, but I guess it's related to the fact that I don't use MySQL or BungeeCord.

EDIT: I just noticed you say you're using Tuinity. You should consider giving a try to this feature under paper. Using Tuinity isn't the best idea, even for test servers. Don't forget that Tuinity is some kind of experimental version of paper. Tuinity's additions end up getting added to paper if they work properly. You should at least try with Paper, and see if it still happens :)

**Comment by kangarko** [comment]
Thanks @ElBananaa for catching up. Right, giving chatcontrol.bypass.spamkick will prevent the Bukkit's antispam kick.

The lags are there since we have to sort hundreds of thousands of messages, I haven't found a stable way around this (yet), however I will make an experimental change where the chat will be removed async. Please test the next version with care and report anything that shows up.

Regarding flicker, this happens when there is not enough cached messages in history. We simply fill those with blank messages which causes a slight flicker.
