### ISSUE TITLE
1.19.3 Endless error spam

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#2288]
### "/version ChatControlRed" - plugin version

10.16.12

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Error log (if applicable)

https://pastebin.com/raw/Yt6f4Hr8

### Information about the issue/bug

Load a default plain test server with CHC, join as a player and enjoy.

When player joins, and stream of endless errors appears.

Even Bungee spams errors. Log file over 1 gb.
Error something like this: https://pastebin.com/raw/CEEgWPxr

**Comment by ElBananaa** [comment]
Dupe of #2271, let's continue there.

**Comment by x1p** [comment]
Dupe or not, I really think one should leave this issue open to warn others not to use this (beta) version as it is unsuitable for production. If I wanted to be a guinea pig, then I would have placed this on a test server and not a production machine.

**Comment by kangarko** [comment]
Will be solved there asap in 1 hour.

**Comment by kangarko** [comment]
I apology for the inconvenience of me putting this onto production. I always test my software, the problem was that people have multiple bungee-related plugins on their machines which broadcast their own plugin messages and I forgot to exclude that. My testing went through fine since I only use BungeeControl Red on my Bungee machine.

What other plugins do you have on Bungee? I can install them on my server so future testing rounds will be more bulletproof.

**Comment by x1p** [comment]
Testing, developing, trial and error. It's all fine by me, as long as it's published as dev or beta. Then admins can make an informed decision to update or not. This is common practice as stated on the many jenkins sites with dev builds. Publishing on BBB suggests some sort of stability.

I usually let CHC load on a test server to let it create a plugin folder. After that I compare files what is changed/added. Update my files and update the production servers.

This particular version loaded fine, but went berserk after a player joined. There is no need to test with extra plugins. A default Bungee and default test server will do. But I guess I just need to test every update myself including joining with a player in order to find out if it at least works. It's tedious but seems necessary.

**Comment by kangarko** [comment]
Okay but the issue was that the problem did not come up with no extra plugins installed, it required the bungee plugins that you have for the issue to arise. So I am just curious to hear what Bungee-only plugins you have installed and so I can include those that are most popular to extend my testing capabilities.

You are right in that publishing on BBB suggest that the plugin has undergone testing and is production ready, that is my intention also. Including a jenkins site for in-between releases whenever there is a bigger change that requires some sort of public testing is something I can consider.

**Comment by x1p** [comment]
The most likely to cause compatibility problems are: Protocollize, ViaBackwards, ViaVersion. I will mail my full pluginlist as I'm not comfortable publishing it here.

Publishing on some public place like Jenkins is not likely a solution for a paid plugin like CHC.
So maybe a versioning system can help.

**Comment by kangarko** [comment]
Thank you so much! Yes, I can totally make a release prefixed -BETA or -DEV next time on BBB when there is major changes and it needs to be aged a bit.
