### ISSUE TITLE
Alternative_Console_Sending making DiscordSRV messages not appear

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2293]
### "/version ChatControlRed" - plugin version

10.16.5

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

Explained in the title.

**Comment by kangarko** [comment]
Because we cancel the chat event. It is noted in the # comments about that key that it will cause third party plugins to break. If that would not be the case then I would just enable that option globally for all people.

You can try tinkering with Listener_Priority. Or just use our native DiscordSRV integration, I tested using our hook and that appears working:

![a](https://i.imgur.com/sSjFz6H.png)
