### ISSUE TITLE
1.18.2 is VelocityControl updated for 10.17.8s update "Solved "Player is not online on this server"

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2334]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Via [10.17.8](https://builtbybit.com/resources/chatcontrol-red-format-filter-chat.18217/update/97659/)

> Fix | Solved "Player is not online on this server" in some commands, thanks to @ElBananaa for the prompt fix and I apology for introducing the bug in the last release

Is this needed to be updated in VelocityControl first before we can update ChatControl red to [10.18.0](https://builtbybit.com/resources/chatcontrol-red-format-filter-chat.18217/update/97778/)?

Maybe @james090500 is the required tag here.

**Comment by ElBananaa** [comment]
This update doesn't require any changes on velocitycontrol's side. Kangarko simply added new debug lines to bungeecontrol, which is why he suggests updating it.

So yeah, you are safe to update right now, no need to wait for velocitycontrol to update.

**Comment by kangarko** [comment]
It's generally safe to update in regards to sync changes between Spigot-Velocity/Bungee.

In case of an issue you will immediately notice a big spam of errors in the console due to wrong packet data. No data corruption will occur, only data won't sync (i.e. /tell won't work) so you can safely downgrade.

If there is a change in the protocol or packets I will ping James to update VelocityControl.

**Comment by TomLewis** [comment]
Thanks guys!
