### ISSUE TITLE
1.18.2: what pixel grid size is your example creeper.png

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2341]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Your creeper.png has 10 squares, that represent 10 squares in-game, what Im trying to figure out is what this represents per square in pixels so I can make a photoshop template with the grid system.
The closest I can figure out is 12.8px per square on that creeper.png image, which seems like such a weird measurement to use.

How does your code translate from pixels to in-game blocks? what is the measurement I can use?

![Screenshot 2023-04-19 at 14 24 33](https://user-images.githubusercontent.com/144046/233089684-6c358f4d-8201-4eae-b9e5-2792df5e9c91.png)

**Comment by ElBananaa** [comment]
I'm not sure to understand you question here. Pixels are not translated, images are sent to the chat.
The default size of the creeper image is 128x128px. Since it's divided in a 10x10 square in the chat, the math is simple: 128x0.1 = 12.8.

**Comment by TomLewis** [comment]
For example, could I use a 8x8px image? so its 1:1 translation. 

why was 128x128 taken to convert it into 8x8 pixels or 10x10? each of the pixels in game can only represent 1 color right?

**Comment by ElBananaa** [comment]
You can use a 8x8px image yeah, I believe images are only resized when they reach a specific size. The default height (if none is specified) is 8, but if you want to use a 20x20 image and specify a height of 20, then the image should not be resized.

The images are resized because you can't show a full 128x128 image in the chat unless your chat takes the whole screen.
That's why every plugin allowing you to use custom emojis or such in your chat also resize their images, because even a simple 60x60 image would be way too big otherwise. And yeah, one pixel = 1 color, your computer screen works the same, so does your phone screen, your tv, etc. (That's basically the whole point of a pixel xD).

If you wish to know more about how the images are handled, you can take a look at this class https://github.com/Kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/model/ChatImage.java

**Comment by ElBananaa** [comment]
@TomLewis Do you need anything else, or may I close this?

**Comment by kangarko** [comment]
Thanks @ElBananaa!

To be honest I have no idea I just modeled the code off of bobacadodl's open source library he abandoned a decade ago. (https://github.com/arxenix/ImageMessage)

One idea: Can you try copy pasting the parseImage and resizeImage methods from [our library](https://github.com/Kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/model/ChatImage.java) and asking ChatGPT, for instance. I apology for the unprofessional answer of mine and lack of experience in this regard.

**Comment by TomLewis** [comment]
Brilliant, this is great I will continue to use 8x8 so its 1:1 so I know exactly how it will turn out.

One last quesiton I have is how transparancy works, It seemed to work before but one of my recent images no longer shows a transparent background/block.

**Comment by kangarko** [comment]
Have you tried a complete white color as transparent? Or a complete black. I do not thing we ever supported transparency with this, we simply replace empty pixels with white.

**Comment by TomLewis** [comment]
I have not! I will try both and report back so it can be updated in the docs 👍

**Comment by ElBananaa** [comment]
Transparent background has always been converted to white. I know at some point this was causing issues and I remember having to rewrite a really small part of code handling this (see https://github.com/kangarko/ChatControl-Red/issues/1848)

But if that's something that's really bothering, I can try to take a look at this, and see if, somehow, we can allow transparent characters.

EDIT: Had a quick look at it, tried a few things but none of them worked. Seems like it would take more work/time than I expected, and I can't spend this time on a a such "gadget" feature, so you may have to wait for @kangarko to take a look at it, if he wants to (or you can make the changes since the class handling this is public)

**Comment by TomLewis** [comment]
Best solution here is to just use a resoure pack then, Im yet to make mine! So I havent experienced Resource packs yet.

I hope chatcontrol works with them, or things like ItemsAdder

**Comment by ElBananaa** [comment]
> Reference in n

Indeed, it is.
So far we don't have any known compatibility issues with ItemsAdder or Oraxen so you should be fine, yeah.
