### ISSUE TITLE
1.20.1: Sever freezing when doing the command "/chc log all"

### ISSUE THREAD

**Issue by NotPatrick565** [kangarko/ChatControl#2405]
### "/version ChatControlRed" - plugin version

10.19.1

### Are you using MySQL?

Yes

### Error log (if applicable)

https://paste.gg/p/anonymous/6100920e5973403f8d27785a4a62cbbc

### Information about the issue/bug

STEPS TO REPRODUCE:

install chatcontrol
enable mysql
enable chat logging [chat, private_message]
execute the command /chc log all

we've got 4 servers connected to the db, with a total of 100 players using the chat in the same time

**Comment by kangarko** [comment]
How big is your ChatControl_Log table? Looks like the table is oversized, try removing the oldest entries by running a SQL.

**Comment by NotPatrick565** [comment]
we have 122367 database lines

speaking to one of our devs. he said that it shouldn't cause problems if the request is made in async. cause we have much bigger databases and when doing an action similiar to the one done in chatcontrol they don't cause issues like that.

**Comment by kangarko** [comment]
Thanks. He's right and we reach for the database async. However we need to compile the Spigot chat component sync and due to technical implementation, all of the logs are compiled before paginated. And this is causing the crash because the component was not designed for this lenght.

I make it so only the newest 10,000 valid logs can be browsed for stability to avoid crashes, before I have time for a more proper fix.
