### ISSUE TITLE
1.20.1 Chat remove glitching

### ISSUE THREAD

**Issue by Ryzz3nn** [kangarko/ChatControl#2423]
### "/version ChatControlRed" - plugin version

10.20.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

[_Startup logs_](https://mclo.gs/CW52XBF) 

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/12353951/debug.zip)

### Information about the issue/bug

the issue is very strange, but basically when you remove stuff the chat bugs out completely, the video shows more of it

[plugins.txt <- list of all plugins we have](https://github.com/kangarko/ChatControl-Red/files/12354078/plugins.txt)

https://github.com/kangarko/ChatControl-Red/assets/47952472/7a27de06-bb38-4cd4-b1bd-6729bc484ed0

**Comment by kangarko** [comment]
Thank you for reporting. Unfortunately we listen to the chat packet using protocollib and it appears you have viaversion and other packet-altering plugins, which might cause this bug. I am unable to proceed since we have no control over the chat messages that protocollib reports to us that we save and re-render once the [X] button is clicked.

**Comment by Ryzz3nn** [comment]
i think its not protocol lib anymore, i made an local test server today with latest version of chc and protocol lib and it works fine

**Comment by Ryzz3nn** [comment]
i wonder what else it could be though 
i could provide a list of all the plugins i have currently if that helps

**Comment by kangarko** [comment]
Well it got to be another plugin, you need to do a test where you remove them one-by-one until you find the culprint
