### ISSUE TITLE
Support Plotsquared v7

### ISSUE THREAD

**Issue by malonnnn** [kangarko/ChatControl#2437]
### Summary

Plotsquared v7 stable was released today, and console has the following error:

`[ChatControlRed] Warning: Could not hook into PlotSquared. Version 3.x, 5.x or 6.x required, you have 7.0.0-Premium`

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

I honestly have no idea

**Comment by waseric** [comment]
Supplementing, "What would happen if we didn't implement this feature? Why not having this feature is a problem?":

As one might expect, the plotsquared-plot parties functionality is not working.
Ref: https://github.com/kangarko/ChatControl-Red/wiki/Channels#party

Players report they cannot see party chat.

Since v7 is the Plotsquared path to 1.20.1, the choice is between upgrading to 1.20.x or having ChatControl parties support.

**Comment by kangarko** [comment]
Thanks, support added!
