### ISSUE TITLE
1.20.1: Performance Issues

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2441]
### "/version ChatControlRed" - plugin version

10.21.0

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### "/chc debug" output (strongly recommended)

[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/12446635/debug.1.zip)

### Information about the issue/bug

Massive performance issues after updating from 10.19.1 to 10.21.0, haven't moved due to 10.21.2 yet due to other issues open on GitHub suggesting it'd make other issues worse but changelog doesn't indicate anything would change with performance. It appears it's coming from things ChatControl is calling from DiscordSRV. I've already chatted with the DiscordSRV support, and they said the issue was with ChatControl. Previous to updating, ChatControl would take 3% or less of the tick time with 20~ players.

Spark Reports:
https://spark.lucko.me/fhDV4zfetS
https://spark.lucko.me/OgKmBdYkmW

**Comment by HorusApl** [comment]
Issue getting consistently worse with higher player counts, now it's just freezing my server: https://mclo.gs/teDmmjd

I downgraded back to 10.19.1 and issues seem to have resolved.

**Comment by kangarko** [comment]
So sorry to hear. I have noticed your log file has over 1,500,000 lines, which, due to physical limitations of a computer, take a long time to read when it is read as a file on your disk:

![a](https://i.imgur.com/ibuUNx0.png)

So what I recommend is you enable MySQL databases, because we can perform IO operations asynchronously and do further optimizations along the way.

That should hopefully resolve DiscordSRV being slow too since this slows down everything else.

PS: In the next version I optimized the file saving more, got your big file written to from 300ms to under 1ms.

**Comment by HorusApl** [comment]
Thank you for the reply, and I would like it to be very clear that I downgraded back to 10.19.1 and the issue is gone completely. No errors, no real lag and back down to the 3%~ tick time as expected. Same log file, same everything, different ChatControl version.

**Comment by kangarko** [comment]
Very interesting indeed. Because the log code was exactly the same for the two versions but perhaps something else was different. Can you try upgrading to the new version from the morning, please?
