### ISSUE TITLE
Bypassing swearing with colors

### ISSUE THREAD

**Issue by jb42300** [kangarko/ChatControl#247]
Is there a way to fix to bypass the swear filter with color codes? saying Shit is blocked but saying &aS&2hit isn't

**Comment by kangarko** [comment]
Hello,

ChatControl free is only checking swears against the regular expressions in the filters in the rules/ folder. Those are for practical reasons not designed to handle color codes. You can change them, if you have basic knowledge about regex.

ChatControl pro removes colors automatically (its Regex_Strip_Colors option) before the words are filtered. This took lots of work and that's why it won't be ported down to the free version. Thank you for your understanding.

**Comment by jb42300** [comment]
yeah I have the pro version
I appreciate thank you
