### ISSUE TITLE
Chat deleting Format 

### ISSUE THREAD

**Issue by xskylite** [kangarko/ChatControl#2524]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

lines appear in the chat how to remove it
![im2121age](https://github.com/kangarko/ChatControl-Red/assets/124276866/3fa07acd-4f80-4028-a200-9ed00d5bc5b2)
![111111](https://github.com/kangarko/ChatControl-Red/assets/124276866/6acfadc8-68b5-43a8-8496-ad8789dde105)
![ima121ge](https://github.com/kangarko/ChatControl-Red/assets/124276866/9b39f714-6eac-4fd8-9f22-10a5209e829c)

**Comment by xskylite** [comment]
and how to fix this (msg) 
![image](https://github.com/kangarko/ChatControl-Red/assets/124276866/8318cd97-8eb1-4d85-b335-2465467c4b10)

**Comment by kangarko** [comment]
Hey!

For the first issue, unfortunately that appears to be caused by the icons. Do lines appear when you don't use ItemsAdder or any special icons? If not then you need to fix the issue on your end since we don't control that.

The second issue, you mentioned you are not using BungeeCord but have not provided /chc debug so I cant investigate. Please provide /chc debug. Ensure that 1k3A is not a nickname but an actual name or enable nickname linking in Tag section of settings.yml
