### ISSUE TITLE
Plugin disables itself on loading

### ISSUE THREAD

**Issue by afroman84** [kangarko/ChatControl#255]
i'm sorry @kangarko , the plugin disables itself due to "vulnerabilities", i do not have time now to update it to the 7.5.0 version and without ChatControl i can't run the server. Am i forced to put the server offline to find some spare time to update ChatControl ? :confused: it was a Beta update and i have not read anywhere that suddenly the plugin won't load up anymore if the update was not installed soon.
Could you please tell me how to disable this behaviour ? i can't update it now, i have to rewrite all configuration files and don't have time. Please let the 7.4.24 version to be run on servers, you released a stable 7.5 version on friday, 3 days ago, i don't think you wanted to disable previous versions without at least an advice for server owners.

some errors when trying to rewrite configuration... following the few informations i found here and in github about updating to the 7.5 version: https://pastebin.com/DRV0yMdY
and this is a mysql syntax error: https://pastebin.com/KdFvu4zR
the previous version won't load, wonderful, even if check_updates is on false. i have to put offline the server :( can't believe this is happening.
this was totally unexpected, please make an URGENT update to let the 7.4.24 version run, it worked perfectly, then we can talk about updating to the new 7.5!

**Comment by kangarko** [comment]
Hey,

first of all, my apology for the issues. I did the mistake of not being transparent enough in this case because of the piracy increased extremely for some reason in the few weeks. Combined with the fact that the last version rendered the ad filter unusable, I decided to shut it down. This won't happen again in a global manner anymore.

As we discussed, the next version will bring automatic MySQL migration. Don't worry about your data if you happen to already dropped the table, in the 7.4.x there were roughly only warning points stored in the MySQL, not updaing those should not impose a practical loss.

Lastly, I understand you may have been in a rush or stressed out due to plugin not working at all, but next time please post to [ChatControl-Pro](https://github.com/kangarko/ChatControl-Pro) channel (this here is for the free version)

The 7.5.0 branch was in beta stage til 7.5.3, and now it is in release candidate. I personally would only put a beta version on my server if I could check it at least twice a day for any errors, but I am pretty confident in saying that you can perform the update to the upcoming 7.5.4 as it will cover the last bigger issues reported.
