### ISSUE TITLE
Ultimate Clans Chat Support | Intergration

### ISSUE THREAD

**Issue by TheTechnologyStudio** [kangarko/ChatControl#2567]
### Summary

Please add support for Ultimate Clans to have chat channels via ChatControl Red, Similar to the Factions Chats or party chats. 

Link: https://polymart.org/resource/ultimate-clans.1162

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

With-out this feature i can not offer Clan specific chat as i don't want to have users chat outside ccr's control.

**Comment by TheTechnologyStudio** [comment]
https://github.com/UlrichBR/UClansV7-API  API for Ultimate Clans

**Comment by kangarko** [comment]
At this time I have no capacity for this since it's a hobby project but I made some code changes allowing developers to add custom parties with easy.

The next release will bring this change. I recommend you send this article to that plugin's author so he can add it:

https://github.com/kangarko/ChatControl-Red/wiki/API#adding-a-custom-party
