### ISSUE TITLE
problem with domain filter

### ISSUE THREAD

**Issue by sOxTw** [kangarko/ChatControl#269]
The problem is when the users use the public chat (without commands) to send links cin point and instead of the point use a space, how could it be solved?
I am talking about the following default lock rule

# Domain/URL filter.
# You can add new domains by inserting '|your_domain' after '|io' (e.g. '|io|pl' for also blocking '.pl' domains)
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|(punto)|,)\s?(com|org|net|es|cz|co|uk|sk|biz|mobi|xxx|eu|me|io|nu|g-s|cc|gs|us)\b
# If you want to whitelist your server, it is only necessary to add it once in format:
# website.domain (example: procraft.com)
# To add more domains simply add them after the last one and divide by |
ignore string minecraft:|banlist.mipropia.com|anydesk.es|youtube.com|imgur.com|join.me|search.com|mcskinsearch.com|survivalrolemine.no-ip.org|survivalrolemine.buycraft.net|http://survivalrolemine.buycraft.net|survivalrolemine.enjin.com|http://survivalrolemine.enjin.com|http://survivalrolemine.enjin.com/|google.com|ts3.srolemine.com|mc.srolemine.com|premium.srolemine.com
id 2
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]
#handle as advertisement

**Comment by kangarko** [comment]
Hey,

It is unclear, in what your issue lies. If the domains are stripped from dots: google.com becomes google com, then this change is not coming from ChatControl. Essentials is known to do that, try adding your players permission essentials.chat.url and essentials.msg.url for private messages

If you however, wish to block domains like 'google com' natively, you need to edit that filter. I am not that good at regex so I can't help you in that, but also keep in mind that such edit will produce great amount of false positives.
