### ISSUE TITLE
Make removing message still possible without protocolib

### ISSUE THREAD

**Issue by noaskers** [kangarko/ChatControl#2710]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

Protocolib is very bad for big servers and is the cause of most lag spikes on servers
Please make it so its still possible this is most likely possible with:
packetevents

Not sure I'm not a coder but someone told me this is possbile.

**Comment by noaskers** [comment]
Some plugins are already working on this:

- LibsDisguises 
![image](https://github.com/kangarko/ChatControl-Red/assets/90572779/e6764211-a271-4a10-9e0e-078ad3e1423a)

**Comment by Lorias-Jak** [comment]
Good question! I know a hand full of plugins wich are implementing PacketEvents

**Comment by kangarko** [comment]
Please provide evidence such as a spark report of ProtocolLib lag and inferior performance to PacketEvents. I dont have time to rewrite the entire core and [complex methods](https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/model/PacketListener.java#L294) of dealing with cross mc compatibility just because it's the new trendy thing. I have large server owners use protocollib just fine.
