### ISSUE TITLE
"Advanced" swear filter

### ISSUE THREAD

**Issue by bobbyrossy123** [kangarko/ChatControl#2723]
### "/version ChatControlRed" - plugin version

10.27.2

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Using the "Advanced" Swear and Offensive word filter for ChatControl Red, hardly any of the words are actually filtering any/all bypasses. Basic stuff which should be filtered such as "F!ck or "Hent@i" aren't picked up at all.

**Comment by TheIntolerant** [comment]
@kangarko could I get access to the source code for the addon? As I could easily add most of these bypasses.

Thanks

**Comment by kangarko** [comment]
These rules are made to balance performance and effectiveness. For performance reasons, the filters might exclude some edge case bypasses. You can always improve the effectiveness of each filter by adding more letters separated by | and surrounded by ().

Example - the following rule matches "penis" but not "pen!s". To add the ! to the filter, simply edit:

`match \b(p+(\W|\d|_)*e+(\W|\d|_)*n+(\W|\d|_)*i+(\W|\d|_)*s+(\W|\d|_)*)`

to

`match \b(p+(\W|\d|_)*(e|\!)+(\W|\d|_)*n+(\W|\d|_)*i+(\W|\d|_)*s+(\W|\d|_)*)`

If you cannot see what we did, note the "e" in the block "e+(\W|\d|_)*" being now (e|\!). Note that due to the ! letter being used as a regular expression operator, we had to prefix it with \ to match it literally instead of using it as a function.

----

To save you time, I have edited the fuck and the hentai filters for you here:

```
# Blocks 'fuck'
match \b(f+(\W|\d|_)*(u|\!)+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
group swear

# Blocks 'hentai'
match \b(h+(\W|\d|_)*e+(\W|\d|_)*n+(\W|\d|_)*t+(\W|\d|_)*(a|@)+(\W|\d|_)*i+(\W|\d|_)*)
group swear
```

----

@TheIntolerant thank you. If you have time, I have pushed the upsell/ folder to the source code - you can add more letters to the filters. But please keep in mind it has performance impact so try to keep it to the necessary minimum.

**Comment by TheIntolerant** [comment]
Hey @kangarko thanks! I must of missed that when looking for it lol.

Anyway, I have had a busy few days but I've made most of the changes, just need to test in case of any typos etc. 

I personally have used these complex Regular Expressions with little to no impact on performance on smaller server but as it is something that can impact performance as you stated, I thought I would add two files that people could pick once that want to use? (seen the screenshots below)

![image](https://github.com/kangarko/ChatControl-Red/assets/48093184/e35c8c44-17fb-4821-914b-a90c20a50a27)

I added a quick note about the two files explaining what makes them different, in the READ ME file.
![image](https://github.com/kangarko/ChatControl-Red/assets/48093184/13028672-da4b-49ff-838d-481c463fa1c0)


Does this seem okay? That way people can pick with they want to use more complex set of rules.
Just to give an example for words like "hentai" with the changes I made in the complex file, 

It will get matched with any of the following plus more!!
h3ntai
hent@i
henta!
h3nt@1
etc.

The work 'Fuck' is similar, with it matching to far more common bypasses
f#ck
f#ck
f**k
f@%k
f__k
etc.

I looked at almost every word in the file and tried my best to see how I can make it harder to bypass, which is why I spilt the files into too, in case it has a performace issue for people!

For example the N word with the "complex" file will also get matched for bypasses like this
^igg4
^!99@
n!g9a
etc.

So it should pretty much be up to 10x harder for people to bypass the filter, if they choose to use this new file!

**Comment by TheIntolerant** [comment]
Anyway, Let me @kangarko know if you are cool for me spilt them into two files. With the current "advanced" swear filter in one file and a more complex one in another file? and I'll make a pull request with those changes!

**Comment by kangarko** [comment]
Sure, I love that idea! I will approve the pull request asap :)

**Comment by TheIntolerant** [comment]
**Quick update:** I am still working on this but was unwell for several days, currently just trying to determine the best RegEx to use for each word to make it harder to bypass but also not accidentally create a ton of false positives!

**Comment by kangarko** [comment]
Get well soon!

**Comment by TheIntolerant** [comment]
Sorry about the massive delay, the last few weeks caught me off guard and became extremely busy but I updated the advanced swear pack and split it into two files, one with the simple (current setup) and another one with a more complex setup.

With the improvements I made to the RegEx used throughout the plguin, the "complex" setup should have no major impacts on performance!

The update is just pending approve from @kangarko ;)

**Comment by kangarko** [comment]
Got it, thank you!

**Comment by kangarko** [comment]
Just a note, I assume you are testing everything, basically every word needs to be tested as a regular player in the game. You don't need to test on 1.8.8 and 1.21.1 twice, but at least boot up the 1.8.8 and test one word to see that it works, and the rest you can do on the latest version.

I hope not to sound rude but it's the amount of times I had a pull request which was untested is like 60-70% of the times of the time from all peoples which is sad. Thank you!

**Comment by TheIntolerant** [comment]
I tested it all via regex101 but I will do fully comprehensive test in-game.

I made sure to include extra details within the Regular expressions to decrease the likelihood of false positives especially with the more complicated one that blocked things like "f&$k" etc but that all being said, I am happy to do some extra testing via in-game!

**Comment by kangarko** [comment]
Thank you!!

**Comment by TheIntolerant** [comment]
I found some time today to do more testing and after discovering a bug with ``before replace`` I had to make a few changes. 

I will make a bug report about the issue but due to the changes I made as a result of discovering the bug, it will have zero impact on the advanced swear pack that I updated!


Otherwise, all is working as intended!

**Comment by kangarko** [comment]
Awesome, happy to hear! I'm still processing the foundation update before going into ChatControl 11. I will keep servicing ChatControl 10 for the time being and we can ship these changes there too. Thanks.
