### ISSUE TITLE
1.21.0: Velocity console spam

### ISSUE THREAD

**Issue by zestian56** [kangarko/ChatControl#2752]
### Error log (if applicable)

https://pastebin.com/ut34uf7w

### Information about the issue/bug

Hello im having my console spammed with this messages. They come from chc red, and happens a lot.

![image](https://github.com/user-attachments/assets/936959d8-ed58-4336-acd4-ca600504dd4d)
![image](https://github.com/user-attachments/assets/ba37feaa-ced6-4a0b-a14c-946ef4b67df9)
It completely blocks the whole console

**Comment by kangarko** [comment]
How many players were online at that time?

**Comment by zestian56** [comment]
> How many players were online at that time?

350+

**Comment by kangarko** [comment]
Thank you. The issue was that the transfer packet was poorly designed and not compressed:

```
{
  "BP_Elias17272": "G:&3Dango.<<P:&7.<<PS:&7",
  "isaacprofine": "G:&3Dango.<<P:&7.<<PS:&7",
  etc.
}
```

The G is the group, the P is the prefix and the S is the suffix. 

I have split it so that we send three packets instead of one now. So the packet is now much smaller:

```
{
  "BP_Elias17272": ":&3Dango",
  "isaacprofine": "&3Dango",
  etc.
}
```

Also, I have applied a deflater compression to the above message, so it further is reduced in size. 

It should never happen in the next version. No ETA because I am still working through other changes but once it's out the fix will be there.

Appreciated your report. All the best with your network.

Matej
