### ISSUE TITLE
large consumptionVersion: Title

### ISSUE THREAD

**Issue by Z3r0xh** [kangarko/ChatControl#2779]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - BungeeCord

### "/version ChatControlRed" - plugin version

10.27.7

### Steps to reproduce

https://spark.lucko.me/pRwn7t0TFl

**Comment by Z3r0xh** [comment]
after 30 min 
https://spark.lucko.me/snFLOR2Zql

**Comment by kangarko** [comment]
Hey there,

This is the first time I am seeing a report like this, unfortunately I cannot expand it beyond this line since it's a native C call to a linux function. Looks like something's  off or slowing down your operating system. Can also be a hardware limit. I'd recommend googling or asking elsewhere since I am not a linux sysadmin, sorry.

![a](https://i.imgur.com/8i0pc8K.png)
