### ISSUE TITLE
[Issue] Deathmessage incompatibility with mcmmo?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#281]
In some cases it shows the hearts of a mob (the hearts are from McMMO), I have not experienced this on CHC 8.

![image](https://user-images.githubusercontent.com/5664135/102520785-5b896300-4094-11eb-8529-93ff9f7c2716.png)

1.16.4, MySQL, Bungee.

**Comment by kangarko** [comment]
What should the hearts represent? The name of the killer or the dead player?

**Comment by kangarko** [comment]
It's likely pulling the entity name which is set to hearts. This is a feature since we want third party support so that you will see "kangarko has been killed by Mighty Creeper" instead of just Creeper if you have a Boss plugin for example.

Not sure, maybe I can add a dirty exception, please copy and paste the UTF heart symbol that it uses. You can copy this from logs. I need the symbol literally to exempt it.

**Comment by Sikatsu** [comment]
It should be the name of the killer (mob). I can not find this line in the logs, does it even output to console or latest.log?

**Comment by Sikatsu** [comment]
Years ago I used a plugin that had something like this:

```
# If the mob name contains any of the following characters and 
# heart-compat-mode is enabled, the default mob name is displayed. You can add 
# characters if the health bar is still visible (copy the character from the 
# death message logs) or remove them at will.
heart-characters: "♡♥❤■"
```

**Comment by kangarko** [comment]
I feel adventurous so I haven't tested this, but I assume it should work starting the next version :)

<img width="910" alt="Screenshot 2020-12-17 at 20 20 05" src="https://user-images.githubusercontent.com/1918426/102533128-45d06980-40a5-11eb-8888-535fbde1ef08.png">

**Comment by Sikatsu** [comment]
Awesome, that's a quick fix! Will let you know if it doesn't work :)
