### ISSUE TITLE
1.21.1 -  10.28.0: Query about channels.

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl#2823]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### Question

Hi, this is a two-part question. I'm hoping you might have some ideas to support or even accomplish.

So the first one is a placeholder as input for range so I can set the placeholder per user and the range will adjust depending on what they have. If this isn't a feature its no worries!

Secondly, I was hoping to accomplish the range area of the channels if someone is say 3-4 blocks away from the max range so an example:
the range is set to 14 blocks and if someone is 12 blocks away it will "Muffle" their chat so it can change their chat that they type to "...m...." Muffled words on top of this I am hoping I can do this if someone has blocks in front or around them so you cannot hear the range "through walls"

**Comment by kangarko** [comment]
I apologizes for the late response!

First question - what placeholder do you mean? Can you give some examples? Not sure if I understand you here, sorry! Generally, the channel range can only be customized globally per channel, in our settings.yml. Not per user.

Second - Sounds like a great addition, however with the other priorities we have I am afraid I wont be able to add this. In theory you can get a developer or write a hook to our API to do these things since the entirety of plugin is unobfuscated. Paper API already provides raytracing so it should be accomplishable.

**Comment by Ash10744** [comment]
Hi Kangarko no worries I an example would be

Range: {Luckperms_meta_range}

and say I was to set their metatag to a number it can pick up that number and adjust the players chat range dependant on that.

**Comment by Ash10744** [comment]
Also could the second option be possible with the javascript addition?

**Comment by kangarko** [comment]
Yes, good idea! You can use javascript and put the variable there, and then do custom stuff depending on the output. Just have a look at how variables/item.yml works (just make sure to change the type to FORMAT if you want to clone the file)
