### ISSUE TITLE
[ChatControlRed] Warning: JSON Message

### ISSUE THREAD

**Issue by danieliustt** [kangarko/ChatControl#2834]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

Latest v10.28.0

### Steps to reproduce

[20:00:29] [Server thread/INFO]: [ChatControlRed] Warning: JSON Message to ZakajusYt was 25758 bytes oversize, removing interactive elements to avoid kick. Sending plain: '[PM] [08:00] [PriÅ¾iÅ«rÄ—tojas Solidas

How to fix that warnings?

**Comment by kangarko** [comment]
Put less stuff in your format. And the next ChatControl 11 will further do some optimizations to reduce the size of the text component. You have to understand since Minecraft 1.7 even sending a simple message like &chello &2world is "["",{"text":"hello","color":"dark_red"},{"text":" world","color":"dark_green"}]", so the size will add up quickly. Nothing I can do, complain to Mojang :/
