### ISSUE TITLE
ChatControl Red on Spigot

### ISSUE THREAD

**Issue by Tylwen** [kangarko/ChatControl#285]
Hello !
ChatControl Red will be on Spigot or it is necessary to buy it on MC-Market?

**Comment by Sikatsu** [comment]
It won't be on spigot, you will have to buy it on Mc-Market ^^

**Comment by Tylwen** [comment]
Okay nice xD

**Comment by incredimike** [comment]
Why not publish to spigot?
It's less ideal for me as the customer. All my other plugins are purchased on spigot, which makes it easier for me to download updates instead of visiting multiple sites.

**Comment by Sikatsu** [comment]
Spigot is really slow in accepting new premium plugins as of late. They also don't seem to accept plugins of certain categories anymore, because a lot of them already exist. Like mini-game plugins for example. Not sure if this also counts for chat plugins though.

There was a huge discussion going on last week on Spigot. Even tho developers help(ed) Spigot grow, theres a lot of restrictions towards developers. Hope this answers your question, maybe Kangarko has something to add later. ^^

**Comment by OfT3N** [comment]
> Why not publish to spigot?
> 
> It's less ideal for me as the customer. All my other plugins are purchased on spigot, which makes it easier for me to download updates instead of visiting multiple sites.

CHC is called on MCM as "MCM exclusive", so I don't think it will be on spigot. And also spigot is shit, because they do EVERYTHING against plugin developers community

**Comment by PascalBrassat** [comment]
https://i.imgur.com/4a3KVbL.png

From what was posting on his discord back in November it was stated it will be uploaded to spigot unless I have missed something since then.

**Comment by kangarko** [comment]
We got banned. More information coming soon.

**Comment by Sikatsu** [comment]
No way, what? Other developers also got banned lately. What is going on as of late?

**Comment by kangarko** [comment]
https://mineacademy.org/the-death-of-spigotmc/
