### ISSUE TITLE
Paper 1.21.1: How to add custom commands defined in rules to tab completion?

### ISSUE THREAD

**Issue by RikMichiel** [kangarko/ChatControl#2884]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

Hello. I am currently using ChatControl and VelocityControl on my Velocity network. I'm also using a plugin called PL-Hide-Pro to hide admin commands from players and give players custom tab completion based on a list of commands. 
How do I add custom commands from chatcontrolred rules to this? 

For example, I've made a command /wiki that returns a link to the wiki in chat. When I add this to the pl-hide commands list, it does not recognize the command as a real command and doesn't show it to the player. 

I've already tried adding the command to the Tab_Complete section in settings.yml, but this just disables every tab completion. So, the pl-hide tab completion doesn't show anymore, and neither do the defined commands in settings.yml.

I've already contacted the plugin devs of pl-hide. They said I should contact you to find a way to add the commands to tab completion.

Can you help me with this?

**Comment by kangarko** [comment]
This is not possible due to how tab completion is sent packet-wise. The client has no idea and neither does the server that the rules exist, they are dynamically checked at the player command event.

One thing you can try is placing the command into commands.yml root server file to see if it gets registered. Or last resort would be opening chatcontrol.jar then editing the plugin.yml command  section to put the empty command label there such as

```
commands:
  yourcommand:
```

**Comment by TheIntolerant** [comment]
@RikMichiel have you looked at https://github.com/kangarko/ChatControl-Red/wiki/Tab-completing-custom-commands

**Comment by kangarko** [comment]
@TheIntolerant @RikMichiel in ChatControl 11 you can route these command a new /dummy command
