### ISSUE TITLE
This is not an issue, but merely a question

### ISSUE THREAD

**Issue by ShawnPR1** [kangarko/ChatControl#296]
Sorry for posting this here, but I cannot post this on the ChatControl Spigot thread's discussions.

I would simply like to know if it would at all be possible to be able to format the chat per world. As in each world (or a specified world) has a specific format.

This might not be a very needed addition (if it's not already possible), but could benefit small servers that have to make use of multiple worlds and do not have bungeecord available. I say this mainly because it would be nice to have a custom formatted chat in the HUB that does not show player's factions in their names, but in the factions world, they do show (as an example).

Great plugin btw and once more sorry for posting here but I had no other outlets (that I know of) that I could have used.

**Comment by kangarko** [comment]
Hello!

ChatControl free currently doesn't support this feature, but you can build your own formats in the premium version and display them according to conditions or [permissions](https://github.com/kangarko/ChatControl-pro/wiki/Formats#sender_permission), so that you can give different permissions in different worlds using your favorite permission plugin to show different formats in (each) world or even linked worlds.
