### ISSUE TITLE
1.16.4 | Localization Keys

### ISSUE THREAD

**Issue by tjrgg** [kangarko/ChatControl#32]
I combed through the localization file (messages_en.yml) and noticed a couple of things that probably should be addressed.

- `Commands.Mute.Channel_Status`: Server Mute Status
  - Is this message suppose to be "Channel Mute Status"?
- `Commands.Reply.Dosage`: <message>
  - Surely, this is a typo. (Should be `Commands.Reply.Usage`.)
- `Commands.Reply.Prescription`: Reply to last player who messaged you.
  - Surely, this is a typo. (Should be `Commands.Reply.Description`.)
- `Commands.Tag.false`: All active tags were disabled.
  - I'm assuming this one was an oversight and should have a different key name?

Also, as a side note, I noticed that there is a "His" key, but not a "Her" key? Is this an oversight?

**Comment by kangarko** [comment]
Thank you!

> Commands.Mute.Channel_Status

Fixed.

> Commands.Reply.Dosage and Commands.Reply.Prescription

This is a joke. Three times a day sir:)

> Commands.Tag.false

Thanks, had to rename the tag to Off_All since Yaml is changing Off to "false".

> His but not hers

Well ChatControl is a man-made product what do you expect? We're not gonna tolerate feminism. Just kidding. Once there's a need for a Her key it'll be added. I don't like using the neutral Their pronoun so I just use "His". If you're native and some objects are clearly female gender let me know.
