### ISSUE TITLE
1.16.4: Ignore String bypass rules

### ISSUE THREAD

**Issue by steveb05** [kangarko/ChatControl#367]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

The ignore string inside a rule allows to bypass it, I tried with a clean installation of ChatControl Red and the problem remained. I'm using the latest version available on Mc-Market (10.1.11). This bug applies wherever ignore string is used.

![Cattura3](https://user-images.githubusercontent.com/50219120/103100609-aadf0e80-4613-11eb-9427-ad55e9a0ff25.PNG)

**Comment by ElBananaa** [comment]
Hey! Merry Christmas! Thanks for reaching us.
I could actually reproduce this issue.
Kangarko will have a look, and we'll keep you updated!

**Comment by kangarko** [comment]
I apology, there's currently no workaround for this because the system doesn't recognize that you only want to ignore parts of the message. If the "ignore string" matches against the entire message, it is ignored.

We tried making it replace these ignored words to some other characters but that would break "then update" and other operators. There's currently no known fix to man.
