### ISSUE TITLE
1.8.8: ChatControl Red poor performances

### ISSUE THREAD

**Issue by haeiven** [kangarko/ChatControl#375]
Hey,

I'm having ChatControl Red using 1.5-3% of a tick :/ 

I've a full spark timing available here: https://spark.lucko.me/#iYzWSHHd0E

![55e17eb8e46abf7a3fa3938e0a414b5c](https://user-images.githubusercontent.com/11612016/103140101-e4327f80-46e2-11eb-8a39-550f30d9b31b.png)

**Comment by ElBananaa** [comment]
Hey! Merry Christmas!
The plugin will necessarily consume a certain amount of resources due to the very large number of features it includes. However, if you don't notice any problem/latency in the timings, you shouldn't pay too much attention to the spark profiler. Actually, as you can see on the profiler, ViaVersion consumes more than ChatControl, and yet, it is far from having poor performances. I'll leave this open and mark it as a question so Kangarko could come back to you with more details and explanations.

EDIT: I also ran a profiler on my end, and don't have the same results. As I said above, you should consider using the timings to report real performance issues. ;)

**Comment by haeiven** [comment]
I know ViaVersion use more ressources... but you can't compare chatcontrol & ViaVersion, they don't do the same thing.

I'm trying to catch all things that are consumming ressources, today wasn't a day with a lot of people, but i'm going to handle 300-400 players soon ^^

Best regards,

**Comment by ElBananaa** [comment]
> I know ViaVersion use more ressources... but you can't compare chatcontrol & ViaVersion, they don't do the same thing.
> 
> I'm trying to catch all things that are consumming ressources, today wasn't a day with a lot of people, but i'm going to handle 300-400 players soon ^^
> 
> Best regards,

I'm not comparing any plugins. I'm just giving you the proof that spark profiler isn't the right tool to check the performances of a plugin. As I said, if there's nothing in your timings report, everything should be fine.

**Comment by broken1arrow** [comment]
> I know ViaVersion use more ressources... but you can't compare chatcontrol & ViaVersion, they don't do the same thing.
> 
> I'm trying to catch all things that are consumming ressources, today wasn't a day with a lot of people, but i'm going to handle 300-400 players soon ^^
> 
> Best regards,

it's quite a lot that affects, when you should have that number of players.

Among other things, entities take a lot of resources. Load lots of chunks are other issue :) 

Another thing to keep in mind is not to use too much placeholders in the chat, among other things.

**Comment by kangarko** [comment]
Thanks, going to have a look. However at scale those caches you see will scale up as well since we effectively cache resources for each player.

**Comment by haeiven** [comment]
This couldn't be done async?

**Comment by kangarko** [comment]
No sorry, the best and the safest we can do is perform those operations on the main thread. We're already doing a lot of mysql and data.db lookups async, however we can't perform bukkit api calls off of their thread since this messes up things inside the server such as giving dead players etc.
