### ISSUE TITLE
[Suggestion] pay to chat and Timed command

### ISSUE THREAD

**Issue by Yamamot00** [kangarko/ChatControl#378]
If would be good if we had a new variable on the settings/channel or in the Format.yml to insert a cost per message, for example to speak on the global you would need to pay X amount to send the message just like in the old essentials chat.
Adding this will reduce more of the chat spam and make the players interact more with the shop system to maintain money to chat on the expecific channel.

Another thing is adding another variable in the timed.rs a variable to only show a certain message/command in a expecific time of the game, day/sunset/night.

One usage for this would be sending a message only when it gets night on the game to inform the players to be careful about the Monsters.
And when its became day to send a message informing the players that its ok to go outside

**Comment by ElBananaa** [comment]
Hey!

These are some cool suggestions.
However, I must admit that in my opinion, it is still quite a gadget.

For the 2nd suggestion, I'm not sure about it, but I guess you could create a variable to check if is the day or not, and return a boolean (true if so, false if not).

Then, you could use the variable `require script {your_script_here}` to only send a specific message at a specific moment of the day.
It only requires some basic Java/Javascript knowledges. But since you apparently can't use `require script` inside the timed_messages, I guess you'll have to wait for Kangarko and see if this is something that could be added.

But honnestly, I don't think that for your 2nd suggestion, this is something possible with ChatControl.
You could just make a very simple plugin for that.

**Comment by kangarko** [comment]
Thank you for your suggestions! Right now our plate is full but I can have a look later in the future.
