### ISSUE TITLE
1.16.4: White color not showing up in chc color menu

### ISSUE THREAD

**Issue by jnijland** [kangarko/ChatControl#385]
Minecraft Version: Tuinity 1.16.4
MySQL: true
BungeeCord: false

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5743926/debug.zip)

Players with the ```chatcontrol.guicolor.white``` permission don't have the white color showing up in their GUI. Other colors, gray for example, do show up. 

Could this be permission related or is this a bug? I've tried it on different servers and even on a server without other plugins but that didn't help. 

Dump of the permission of the user that cannot use the white color option: https://pastebin.com/zh6mC36h

**Comment by ElBananaa** [comment]
Hey!

I just tried, and same, there's no white color button, but the reason seems pretty obvious to me: the white color is the default color for the chat, so basically, it could mean 2 things:
- Either Kangarko forgot to add a white color button
- Or there's no white color button since white color is the default color, and that means player should use the reset button to get use the white color.

Marking this as low priority.

Have a nice day! :)

**Comment by jnijland** [comment]
Thanks for your reply @ElBananaa :) I'm planning to use gray as the default color for chat, so it would be great if there's a way to set it up like that 👍

**Comment by kangarko** [comment]
Thanks, will get added.
