### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by ZappySK** [kangarko/ChatControl#390]
Hey, i have ChatControlRed, and my chat is still not working.. showing <ZappySK>.. any help?

**Comment by ZappySK** [comment]
![Uploading image.png…]()

**Comment by ZappySK** [comment]
![image](https://user-images.githubusercontent.com/76651966/103171632-1dd3c980-484e-11eb-953f-e40e2232ce64.png)

**Comment by james090500** [comment]
Check your console. Seems you have a formatting issue

**Comment by ZappySK** [comment]
https://pastebin.com/44maxFvB

**Comment by ZappySK** [comment]
no error

**Comment by ZappySK** [comment]
i need to enable chat formatting somewhere in configs or what?

**Comment by james090500** [comment]
I believe you may not be in a channel? 

https://github.com/kangarko/ChatControl-Red/wiki/Channels

Do /chc list then /ch join

**Comment by ZappySK** [comment]
i want to use normal chat, what i need to do? /cdc list not works

**Comment by ElBananaa** [comment]
Hey!

@james090500 Thanks for trying to help him!

@ZappySK As I can see, you are using an outdated version of protocolLib that doesn't fully support 1.16.4, but your server is using 1.16.4. Please update to the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

Also, please provide your `/chc debug` output file.
As james090500 said, the plugin needs the channel feature in order to be able to use a large part of its features.

**Comment by ZappySK** [comment]
I want classic chat like default, no some retarded channels :d

**Comment by james090500** [comment]
> I want classic chat like default, no some retarded channels :d

You can do this but having a single channel called "standard". I have the same setup on my server.

in settings.yml, enable channels make a channel called "standard" like below: (you can adjust the format in formats/chat.yml"

```
  List:
    standard:
      Format: chat
```

You'll need to give default users this permission so they automatically join the channel and can't leave it

```
chatcontrol.channel.autojoin.standard.*
chatcontrol.channel.join.standard.*
```

**Comment by broken1arrow** [comment]
You can need this too chatcontrol.channel.standard.write and chatcontrol.channel.standard.read so should it bee ready too goo. 

@james090500

I think is standard when you install first time, it is setup like that.

**Comment by ElBananaa** [comment]
> I want classic chat like default, no some retarded channels :d

As said in my first message, you need to enable the channels system in order to take full advantages of the plugin features.

However, you should take a look at this wiki page: https://github.com/kangarko/ChatControl-Red/wiki/Channels#auto-join

I'm closing this issue for now. Feel free to keep sending messages here if you still need help regarding this issue, or opening a new issue if you need help or if you have a question/suggestion regarding anything else.

Have a nice day! :)
