### ISSUE TITLE
What is server-name "key" ?

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#428]
like title i don't know that plugin [server-name "key"] mean

**Comment by ElBananaa** [comment]
> like title i don't know that plugin [server-name "key"] mean

Hey!

This key can be found in your `server.properties`. It is used by the plugin in order to define a name for each server, in the database. This feature is mainly used for bungeecord/mysql setups, so the plugin knows with which servers it communicates.
However, you also need to define it even under a single-server/sqlite setup.
