### ISSUE TITLE
NPE on Chat Message

### ISSUE THREAD

**Issue by jakkuh** [kangarko/ChatControl#450]
Minecraft Version: 1.16.4 - Tuinity
MySQL: false
BungeeCord: false

Player was simply sending a message, no other reproducible behaviour was found

Error Log: https://pastebin.com/NSKfA28N

Symptom: 
![image](https://user-images.githubusercontent.com/14115855/103430807-b0d97000-4b7c-11eb-8ed6-85ae45be7c5b.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4 - Tuinity
> MySQL: false
> BungeeCord: false
> 
> Player was simply sending a message, no other reproducible behaviour was found
> 
> Error Log: https://pastebin.com/NSKfA28N
> 
> Symptom:
> ![image](https://user-images.githubusercontent.com/14115855/103430807-b0d97000-4b7c-11eb-8ed6-85ae45be7c5b.png)

Hey!
Happy new year!

Please provide us your `/chc debug file`.
Also make sure all your plugins/dependencies/server software are up-to-date.

A lot of people noticed issues with forks like Tuinity and Purpur.
Please try to reproduce this issue under paper, and let us know if it still happens.

Unfortunately, if it fixes the issue, I guess you'll have to stick with paper since Kangarko can't provide support for each spigot/paper fork.

**Comment by kangarko** [comment]
Thanks, will get fixed to the next version
