### ISSUE TITLE
1.16.4: Error on reload

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#456]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

https://gist.github.com/MithrandirCraft/d68862e1c0c1e14f5498944fe57a6798

**Comment by MithrandirCraft** [comment]
The reload actually finished, and the plugin seems to be working fine, but it took a long time + generated lag.

**Edit:** Ah I see, so this is normal? :l
Maybe add alternative /reload commands that only reload configurations?

**Comment by ElBananaa** [comment]
> The reload actually finished, and the plugin seems to be working fine, but it took a long time + generated lag.
> 
> **Edit:** Ah I see, so this is normal? :l
> Maybe add alternative /reload commands that only reload configurations?

Hey!
Happy New Year!

Thanks for reporting this.
AFAIK, the reload command currently reload the whole plugin datas, including the database. Having a huge database would also mean that the reload could take a long time. (I might be wrong about what I'm saying tho).

Adding an alternative reload system would be a nice idea.
I'll leave this issue open so Kangarko could take a look at it.

**Comment by kangarko** [comment]
Right now we have to reload things on the main thread, so if it's loading mass amount of user data there is going to be a lag. I don't want risking data corruption moving things off of the main thread then it would really make the reload over the top complicated since there would be a call AFTER the reload like 5-10 seconds later which would break stuff since you could already be doing other things until that call is received.
