### ISSUE TITLE
1.16.4: Plugin not compatible with java 15.0.1 

### ISSUE THREAD

**Issue by CypherPhyre** [kangarko/ChatControl#479]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

Console error: https://pastebin.com/hdFGFWES.

I was forced to update my java version from 1.8.0_161 to 15.0.1 due to pending changes and now the plugin will not load.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false
> 
> Console error: https://pastebin.com/hdFGFWES.
> 
> I was forced to update my java version from 1.8.0_161 to 15.0.1 due to pending changes and now the plugin will not load.

Hey!
Happy New Year!

It was said many times that the plugin doesn't support Java 15. Actually, it's written on the install page (https://github.com/kangarko/ChatControl-Red/wiki/Compatibility). This is due to a replacement of the actual javascript engine (Nashorn is deprecated since java 9+, and was removed in java 15 to be replaced by GraalVM.)

Currently, there is no deadline for java 15 support. However, what do you mean by "I was forced to update my java version"? Paper recently announced that Java 8 is now deprecated, but you can use Java 11 (Which is the new LTS version of java, in replacement of Java 8), or any version later to Java 8, and prior to java 15.
