### ISSUE TITLE
1.16.4 MySQLSyntaxErrorException Specified key was too long

### ISSUE THREAD

**Issue by merlinshaw** [kangarko/ChatControl#486]
Minecraft Version: Paper-345 (MC: 1.16.4)
MySQL: true
BungeeCord: true

I'm getting the attached error.
MySQLSyntaxErrorException Specified key was too long; max key length is 767 bytes
[error.log](https://github.com/kangarko/ChatControl-Red/files/5767673/error.log)

Is there something I need to do to fix this?

**Comment by kangarko** [comment]
The last error is "Table 'ChatControl.ChatControl' doesn't exist" so make sure you set the logs in mysql.yml right. 

Just remove chatcontrol tables in your mysql, update and it if happens again then unfortunately it's driver problem in your database. We require utf8mb4_unicode_520_ci compatibility, just check in with your hosting.

**Comment by merlinshaw** [comment]
So i'm running a dedicated server on Centos 7 so I control the MySQL. It is running utf8mb4_unicode_520_ci  when it creates the table it even says it. I have gone in and checked the mysql.yml and everything is correct.

[error.log](https://github.com/kangarko/ChatControl-Red/files/5773462/error.log)
![Table](https://user-images.githubusercontent.com/3880522/103719218-c5a37280-4f85-11eb-9214-8e86bdaa64e7.PNG)
![Database_LI](https://user-images.githubusercontent.com/3880522/103719261-d81dac00-4f85-11eb-9685-1f02e4b2b85b.jpg)

**Comment by merlinshaw** [comment]
maybe make a guide to help people update their Database to what is all needed?

**Comment by kangarko** [comment]
Try dropping this table and let it regenerate anew. This seems to be a problem out of our control: https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes#:~:text=767%20bytes%20is%20the%20stated,been%20increased%20to%203072%20bytes.&text=This%20is%20because%20the%20maximum,utf8mb4%20character%20is%20four%20bytes. 

Try using MySQL 5.7 or 8.0 instead of MariaDB. I unfortunately cannot assist you with this.
