### ISSUE TITLE
Accents are removed from admin channel

### ISSUE THREAD

**Issue by haeiven** [kangarko/ChatControl#499]
Hello,

Accents are removed from admin channel, i don't really understand why it's happening. This is not happening in the standard channel.

Best regards,

**Comment by ElBananaa** [comment]
> Hello,
> 
> Accents are removed from admin channel, i don't really understand why it's happening. This is not happening in the standard channel.
> 
> Best regards,

Hey! This is probably because the strip accent feature is enabled for rules, and the /ach command is created using a rule. You can easily fix this by either setting `Strip_Accents` to `false` in your settings.yml file and by removing the following rule in your `rules/chat.rs`.
*Note that using this method, it will allow accents everywhere. Which means that you'll have to rewrite your rules to block words/sentences with accents, or it will break the plugin.
```
# Prevent special, unicode characters. Those are misused to bypass filters.
# Please keep in mind that non-English languages use them, so only uncomment this on English servers.
match [^\u0000-\u007F]+
then warn {prefix_error}Unicode characters are prohibited.
then deny
```
If you want to keep using the strip accent feature, then set it to true in your settings.yml, don't remove the rule above, and add:
`before strip [^\u0000-\u007F]+` in under the rule used to chat in the admint chat.

If it still doesn't work, please make sure your plugins, their dependencies and your server softwares are up-to-date, if they're not, update them and try again, and if it still doesn't work, send us your `/chc debug` file
