### ISSUE TITLE
1.16.4: local chat with global chat using a symbol

### ISSUE THREAD

**Issue by Syndr4** [kangarko/ChatControl#513]
Hi, I have several questions about ChatControlRed.
1- I would like to be able to make a local chat what when you place ! you could write globally, I was trying to do it for a couple of hours but I couldn't.
2- Is there any way to block words?

Sorry my very very bad english, i speak spanish

**Comment by ElBananaa** [comment]
> Hi, I have several questions about ChatControlRed.
> 1- I would like to be able to make a local chat what when you place ! you could write globally, I was trying to do it for a couple of hours but I couldn't.
> 2- Is there any way to block words?
> 
> Sorry my very very bad english, i speak spanish

Hey!
1) You can do that with the plugin. In your `/plugins/ChatControlRed/rules/chat.rs` create a rule like this one:
```
# Send messages starting with "!" to globalchat
match ^(\!)(.*)
require perm chatcontrol.channel.autojoin.globalchat.read
then command channel send globalchat $2
then deny
dont verbose
```
Simply replace the permission and the command with the name of your globalchat. So if my globalchat is named `GlobalChannel` in the settings file, I would change the perm to `require perm chatcontrol.channel.autojoin.globalchannel.read`
and the command to `then command channel send globalchannel $2`

**NOTE:** If you are using a bungee setup, there's a rule that already exists for global chat inside `/plugins/ChatControlRed/rules/global.rs`. Simply remove the comments.
```
# Uncomment to forward any message starting with ! to bungee channel
#match (\!)(.*)
#then command ch send bungee $2
#dont verbose
#then deny
```

2) You can block specific words inside the same file: `/plugins/ChatControlRed/rules/global.rs`. It uses regex, so you should take a look at them on google in order to know how to properly edit these rules.
