### ISSUE TITLE
A couple pre-purchase questions

### ISSUE THREAD

**Issue by AZFire1** [kangarko/ChatControl#551]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: true

1. This is likely the most important question, will this plugin stay updated, and will it ever be remade into a new chat-control version that people will have to buy again?
2. I noticed it had death message support, this could lower the number of plugins I have just to this plugin. Is there support for hooking into discordsrv for death messages?
3. How easy is it to configure? I honestly have no idea how the config looks, I've never used this or chat control pro/free

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: true
> 
> 1. This is likely the most important question, will this plugin stay updated, and will it ever be remade into a new chat-control version that people will have to buy again?
> 2. I noticed it had death message support, this could lower the number of plugins I have just to this plugin. Is there support for hooking into discordsrv for death messages?
> 3. How easy is it to configure? I honestly have no idea how the config looks, I've never used this or chat control pro/free

Hey!
Thanks for reaching us.

1) Kangarko doesn't plan to make any new paid version of ChatControl for now.
Keep in mind that ChatControlPro was firstly released in 2015, received 525 updates, and will keep being updated/receive support, even tho the plugin is now free. The reason behind the fact that this version is paid is that it's a complete rewrite from scratch.

2) The plugin actually supports death messages, yes. And the plugin is already hooking into discordsrv for some features, but what do you mean by "Hooking into discordsrv for death messages"? Does the plugin sends ingame death messages to discord?  If so, yes, the plugin actually allows it, (as you can see [on the wiki page related to discord linking](https://github.com/kangarko/ChatControl-Red/wiki/Discord)) and it also allows sending staff alerts when someone sends an ad, broadcasts, player messages...

3) It depends of what you mean by "easy". The plugin actually has a lot of features, and Kangarko is happy to take any suggestions regarding the plugin. The documentation is complete, as you can see here: https://github.com/kangarko/ChatControl-Red/wiki

But to answer you, as an old user of ChatControl-Pro I personally consider ChatControl-Red easy to configure, and if I'd be a new user, compared to a lot of other plugins, since the documentation is very complete, I'd say that even if the configs are complete, the documentation makes the configuration pretty easy. Anyways, Kangarko and I would be happy to help you if you have any other questions, or, if you decide to buy the plugin, to help you if you are in troubles configuring it.

If you need anything else, just let us know! :)

**Comment by AZFire1** [comment]
1: Is it possible to have Death Message groups? So, different groups can get different death messages?
2: Is it possible to have join/quit/kick message groups and also join/quit/kick private messages that I could sell to the store that would override default group messages?

**Comment by kangarko** [comment]
Thanks to Banana for replying!

1. There's no plans to introduce any new paid upgrade.

2. Yes you can have multiple player or players receive totally different message, very easy to setup just see Wiki and/or the default files. You can literally just type "require receiver permission mygroup.vip" then all messages in that group only go to playyers with that permission. 

3. We're the biggest chat plugin so of course if you're expecting to drag and drop and run away then don't buy. You need to configure this. Some people spend days some people tweak this for many years. Theres no definitive answer — if you care about your server then you should constantly improve and test all plugins

**Comment by AZFire1** [comment]
Is there a player GUI for choosing colors in chat as well? What all GUI's are there that come with the plugin?
![image](https://user-images.githubusercontent.com/67762583/105275212-8d9f5080-5b7d-11eb-85b2-14f0aa2b6ea3.png)

**Comment by AZFire1** [comment]
It says the license duration is only 1 year, what happens after it expires, do I lose access to future updates of the plugin?
![image](https://user-images.githubusercontent.com/67762583/105317686-3f9c4400-5ba1-11eb-9d2b-916861dff9df.png)

**Comment by ElBananaa** [comment]
> Is there a player GUI for choosing colors in chat as well? What all GUI's are there that come with the plugin?
> ![image](https://user-images.githubusercontent.com/67762583/105275212-8d9f5080-5b7d-11eb-85b2-14f0aa2b6ea3.png)

Hey!

There's a GUI for ingame color yes.
I'm not sure that there's any other GUIs yet, but there's a lot of chat-formatted interfaces like the mail feature.

Regarding the license, that's due to the fact that Kangarko plans to move to his own platform.
This is what kangarko told me about licensing
![image](https://user-images.githubusercontent.com/53318613/105411916-50e26080-5c34-11eb-907d-0203b603da2d.png)

**Comment by AZFire1** [comment]
Should I wait to buy it on his website then? Or, am I able to buy it on MC-M and get it transferred? I don't want to buy something on MC-M then have the resource removed..

**Comment by ElBananaa** [comment]
> Should I wait to buy it on his website then? Or, am I able to buy it on MC-M and get it transferred? I don't want to buy something on MC-M then have the resource removed..

Hey!

If you want to, you can buy the plugin right now. As Kangarko said on discord, the transfer will be free.
![image](https://user-images.githubusercontent.com/53318613/105511983-df0c2480-5cd0-11eb-84fc-b085e2ebdc7f.png)

**Comment by AZFire1** [comment]
Does the plugin support hex color codes?

EDIT: I answered my own question. Please entirely ignore this message.

**Comment by ElBananaa** [comment]
> Does the plugin support hex color codes?
> 
> EDIT: I answered my own question. Please entirely ignore this message.

Hey!
Alright, no worries haha, and yes it does.

**Comment by AZFire1** [comment]
I noticed the plugin says it has tags? Is this like DeluxeTags? I'd love to simply replace that plugin with this one. It'd be really nice. If so, does it have a GUI where you can pick the tags you want? If not, that could be a suggestion.

**Comment by ElBananaa** [comment]
> I noticed the plugin says it has tags? Is this like DeluxeTags? I'd love to simply replace that plugin with this one. It'd be really nice. If so, does it have a GUI where you can pick the tags you want? If not, that could be a suggestion.

The plugin has tags yeah. You can have a custom prefix/suffix. However this doesn't work like deluxetags. There's no gui to select a tag since you have to write your own tag.
