### ISSUE TITLE
Double messages

### ISSUE THREAD

**Issue by dalandis** [kangarko/ChatControl#566]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Hello
Same issue https://github.com/kangarko/ChatControl-Pro/issues/719
Can you please tell me, is it solved?

I have a new installation. The network has two bungee servers, a lobby and two survivors.
Bungee are connected through radis bungee. BungeeControl is installed on both bungee and ChatControlRed is installed on all servers.

![image](https://user-images.githubusercontent.com/15212686/105609113-7a2ff780-5dc0-11eb-8555-f1dc2be5d2b4.png)

**Comment by ElBananaa** [comment]
Hey!
Could you please provide us your `/chc debug` output.
This issue could be the same than the one you linked, but since this version is a complete rewrite from scratch, I doubt it's the same cause.
Could you also try to send a message in the same channel, using `/ch send <channel> <message>`, and let me know if the message is still sent twice.

**Comment by dalandis** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5860706/debug.zip)

via '/ch send' the same problem.

one more observation. the double message is visible to everyone except the author of the message.
![image](https://user-images.githubusercontent.com/15212686/105610211-f37f1880-5dc7-11eb-83e0-1e3d60d401fa.png)

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5860706/debug.zip)
> 
> via '/ch send' the same problem.
> 
> one more observation. the double message is visible to everyone except the author of the message.
> ![image](https://user-images.githubusercontent.com/15212686/105610211-f37f1880-5dc7-11eb-83e0-1e3d60d401fa.png)

Thanks.
As I can see you are using Yatopia, which isn't supported by ChatControl-Red, could you try under paper?

**Comment by dalandis** [comment]
Could it be a problem that the survival server, bungee server and mysql are on different hosts? Maybe some kind of lag?
All hosts are not on the local network, but in different DC.

**Comment by dalandis** [comment]
I will be able to provide more information and check on the paper only tomorrow.

**Comment by dalandis** [comment]
It seems that if survival (yatopia), mysql and bungee on the same host, then it works fine.
OK. I'll do more tests tomorrow.

**Comment by dalandis** [comment]
I've done a lot of tests. And found out the following.
For clarity, I drew a diagram of my network

![Снимок экрана 2021-01-26 181825](https://user-images.githubusercontent.com/15212686/105856820-10ebf680-6003-11eb-9e5f-caa098cddfe0.png)

The problem manifests itself when players are connected through both bungee servers. 
I have the latest version of bungee. I tried with paper, but it doesn't matter. The problem manifests itself on paper and yatopia.

If all players are connected through one bungee, then everything works fine. But I need both server bungee

**Comment by kangarko** [comment]
I am so sorry! This appears to be a problem in BungeeControl Red if they are indeed connected through both servers. I don't have enough expertise to debug a Redis instance.

We have a simple redis deduplicator though, I have doubled it's reach so that it will deduplicate messages sent in the last 100ms. Lemme know if that helped!

**Comment by dalandis** [comment]
Unfortunately it didn't help.

redisBungee generally to synchronize the tab list. If chatControlRed can sync the tab list, then can I just turn off the redisBungee?
Does chatСontrolRed support tab list synchronization?

**Comment by kangarko** [comment]
No it doesn't sadly, you'll need to seek a third party plugin for that.

Unfortunately as I see this your situation is "not normal" so to speak, never had anyone bring this up and quite frankly having no idea how to fix that so that it doesn't interrupt with the other people we have using redis in another way, so sorry about this but I hope you'll find a way somehow!

**Comment by dalandis** [comment]
Came back to this problem. But I can't find a solution.
Can you watch it again?
Also found the same issue - https://github.com/kangarko/ChatControl-Red/issues/94

**Comment by kangarko** [comment]
Unfortunately I am not able to fix that because I have no Redis programming knowledge, as said on that ticket. If you have a developer I can grant him source code access to BungeeControl.

**Comment by kangarko** [comment]
https://bitbucket.org/kangarko/bungeecontrol-red/src/master/
