### ISSUE TITLE
low tps problem

### ISSUE THREAD

**Issue by ttt0** [kangarko/ChatControl#575]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

https://timings.aikar.co/?id=acd3127572804ac5bd2b5441917748a2

After 60 players tps drops when I check timings it seems chatcontrolred what should I do

**Comment by PascalBrassat** [comment]
Looking at your timings this doesn't seem like a chatcontrol issue to me, but instead an issue in regards to entities, you may want to look into optimizing your mob spawns, and getting a plugin to better handle the amounts on your server,

I would recommend reading this thread and changing the files mentioned, and then looking into a plugin such as stackmob, or something that deals with excessive mobs.
https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/


Another route you can look into is your flags; https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

We had this issue on our server a few months back, going through and optimizing our configurations has helped and we have since not had a single issue.

**Comment by kangarko** [comment]
Thanks for @pabjr17 to such a great help and valuable suggestion! 

Good luck and of course feel free to comment below if you find anything that's purely ChatControl Red related :)
