### ISSUE TITLE
Error on Chat Message

### ISSUE THREAD

**Issue by cades66** [kangarko/ChatControl#579]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: Owned bungee - chat doesn't work at all. In this case, no.
[error.log](https://github.com/kangarko/ChatControl-Red/files/5868705/error.log)

When I use ChatControl and try talking (using channels and chat formatting), I get this error.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: Owned bungee - chat doesn't work at all. In this case, no.
> [error.log](https://github.com/kangarko/ChatControl-Red/files/5868705/error.log)
> 
> When I use ChatControl and try talking (using channels and chat formatting), I get this error.

Hey!
Please provide us your `/chc debug` file.

**Comment by cades66** [comment]
https://ufile.io/cdhii89y

**Comment by ElBananaa** [comment]
> https://ufile.io/cdhii89y

Thanks.
The issue is due to the usage of `{receiver_is_spying_{channel}}` in your chat.yml format file. Replace it with `{player_is_spying_{channel}}` it should fix your issue.

I'm closing the issue, feel free to keep sending messages down below if the issue persists, or open a new ticket if you need anything else.

**Comment by cayoten** [comment]
This seems to have become a new issue with MySQL. I can't attach a debug file as it says the plugin is disabled.

https://paste.gg/p/anonymous/f3d15866396c4deea0199f6b295e6ca2
