### ISSUE TITLE
1.16.5: Shouldn't be commands in commands.rs tab completed?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#594]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

```
# This rule only executes when player is not in the admin channel for reading.
match ^(\/ach)
dont verbose
ignore channel admin write
then command channel join admin write
then deny

# This rule only executes when player is in the admin channel for writing.
match ^(\/ach)
before replace [^\u0000-\u007F]+
dont verbose
require channel admin write
then command channel join standard write
then deny
```

Hi I have command /ach, similar to default "/admin toggle" probably, but this command isn't tab completed... Shouldn't it be? If no, how could I make it tab completed then?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> ```
> # This rule only executes when player is not in the admin channel for reading.
> match ^(\/ach)
> dont verbose
> ignore channel admin write
> then command channel join admin write
> then deny
> 
> # This rule only executes when player is in the admin channel for writing.
> match ^(\/ach)
> before replace [^\u0000-\u007F]+
> dont verbose
> require channel admin write
> then command channel join standard write
> then deny
> ```
> 
> Hi I have command /ach, similar to default "/admin toggle" probably, but this command isn't tab completed... Shouldn't it be? If no, how could I make it tab completed then?

Hey!
Tab-completion is pretty complicated afaik. You can't simply create tab-completion for your commands, this needs to be done internally using libraries like spigot internal system, Brigadier, Commodore etc...

I don't know if what you would like to do is actually possible since, I guess, the plugin doesn't really register commands created in this file like the plugin's internal command.
Kangarko could clearly give you a better answer, but from what I know, these libraries have limitations, and this could be one of them.

**Comment by TheIntolerant** [comment]
As Nathan said, this is complex to do and would require chatcontrol to register the commands (which it does not do) in order for it to work in tab.

As stated by some people on the discord, there are three ways to make custom commands work in tab, using the file ``commands.yml`` or using a plugin such as [Register Commands](https://github.com/RLNT/spigot-registercommands/releases)
________________________________________

So to make a /ach, command that can be tabbed, you can do this three ways,

________________________________________
Option 1) Skip chatcontrol rules completely and just make an alias in ``commands.yml``
> **commands.yml setup**
```
command-block-overrides: []
ignore-vanilla-permissions: false
aliases:
  ach:
  - channel send admin $1
```
**NOTE: Using commands.yml to make this alias, will mean the command isn't togglable, instead it will work as follows
``/ach <message>``**

________________________________________
Option 2) Use chatcontrol rules AND create a fake alias in ``commands.yml`` to make your command tabbable 
> **commands.yml setup**
```
command-block-overrides: []
ignore-vanilla-permissions: false
aliases:
  ach:
  - say this is a a fake alias for /ahc
```


> **ChatControl rules - commanads.rs setup**
```
# This rule only executes when player is not in the admin channel for reading.
match ^(\/ach)
dont verbose
ignore channel admin write
then command channel join admin write
then deny

# This rule only executes when player is in the admin channel for writing.
match ^(\/ach)
before replace [^\u0000-\u007F]+
dont verbose
require channel admin write
then command channel join standard write
then deny
```
chatcontrol will always check the rules first before executing the command so if you add the ``then deny`` operator everything will be tabbable and fine. Due to the ``then deny`` operator the alias in commands.yml won't ever execute the "/say" command you put in there as ChatControl will deny it, if ``then deny`` is used in the chatcontrol rule.

NOTE: For commands.yml to make alias commands work in tab, the alias need to be created for a command that already works with tab, that is why /say, is used in this example
________________________________________

Option 3) Find the two options above too confusing???

> Using this plugin [Register Commands](https://github.com/RLNT/spigot-registercommands/releases), all you need to put in the config for this plugin is as follows
```
commands:
  ach:
    description: Used to talk in admin chat
    usageMessage: /ach
```
Once you restart the server, the command will then work in tab and you can use ChatControl to adjust how the command functions.

**Comment by bobhenl** [comment]
Thank you very much! It can be closed now.

**Comment by kangarko** [comment]
Thanks guys for giving a helping hand <3

**Comment by kangarko** [comment]
@gone-incognito I made you a dedicated wiki page: https://github.com/kangarko/ChatControl-Red/wiki/Tab-completing-custom-commands

Your help has been amazing so far and I am proud to have worked with you!
