### ISSUE TITLE
1.16.5: Chat broken, errors in console

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#596]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

As of yesterdays release, the console spams errors and breaks players formatting: https://pastebin.com/ifgGbdfe

Error.log: 
[error (1).log](https://github.com/kangarko/ChatControl-Red/files/5885880/error.1.log) (please see errors of date 28th)

Debug:
[debug (1).zip](https://github.com/kangarko/ChatControl-Red/files/5885884/debug.1.zip)

**Comment by Sikatsu** [comment]
Seems to have happened after a certain player joined: https://pastebin.com/jYqNegZh

Can't find the player in the database either, as the database doesn't have anyone stored that starts with the letter T.

**Comment by Sikatsu** [comment]
When the player leaves it works again lol?

![image](https://user-images.githubusercontent.com/5664135/106114686-215db780-6150-11eb-8c1a-54d6f2f5a9a2.png)

**Comment by ElBananaa** [comment]
> When the player leaves it works again lol?
> 
> ![image](https://user-images.githubusercontent.com/5664135/106114686-215db780-6150-11eb-8c1a-54d6f2f5a9a2.png)

Hey!
I'm not sure what's causing the NPE, but from what I understand, it could be related to the usermap.
Could you make sure the player is actually inside the usermap?
As I said, i'm not sure it's related to this at all, so please wait for @kangarko.

**Comment by Sikatsu** [comment]
Hey, the usermap is there. I have reverted to the previous version for the time being, and this does not occur.

**Comment by ElBananaa** [comment]
Related to #597, #601, #602 and #604.

**Comment by DoogiePC** [comment]
I'm having this issue and I have to say, I don't think plugin jars should be released to mc-market to paying customers when it hasn't even been tested, I deployed this on my server thinking it had been tested and was safe to use. Nope! my server was fucked, chat broken and had I gone offline for the night like I was planning to, the server would have had that broken chat all night and for a lot of the next day.

**Comment by MinecraftAdmin** [comment]
Can confirm this happens to me too.

**Comment by kangarko** [comment]
I dearly want to apology to everyone. This will be fixed asap! I have tested that release for half a day but it simply happened when a new user that did not have any data stored joined that this would pop up, because we had a condition added to check for his old data to respect potential Mojang's username change. 

I simply did not check this with a brand new nickname simply because in the last 5 years this is the first time such a bug occurred :) Holy cow! Anyways, I'll be dropping a new release in just a few hours and yes, I tested this with a new username!
