### ISSUE TITLE
Sender_Permission any permission in list

### ISSUE THREAD

**Issue by BenjaminHoegh** [kangarko/ChatControl#599]
Is it possible to make a `Sender_Permission `look for any permission match in a list? 
Also can you require multiple permissions?

**Comment by ElBananaa** [comment]
> Is it possible to make a `Sender_Permission `look for any permission match in a list?
> Also can you require multiple permissions?

Hey!
Actually, this can be done, but not with Sender_Permission. You need to use Sender_Condition in order to do that using the placeholder `{player_has_permission_<permission>}`.
So as example, if I only want players with fly and kick permission to use a specific format, I'll use:
`Sender_Condition: '{player_has_permission_essentials.fly} && {player_has_permission_essentials.kick}`

**Comment by ElBananaa** [comment]
> > Is it possible to make a `Sender_Permission `look for any permission match in a list?
> > Also can you require multiple permissions?

Hey!

Actually, this can be done, but not with Sender_Permission. You need to use Sender_Condition in order to do that using the placeholder `{player_has_permission_<permission>}`.

So as example, if I only want players with fly and kick permission to use a specific format, I'll use:
`Sender_Condition: '{player_has_permission_essentials.fly} && {player_has_permission_essentials.kick}'`

**Comment by BenjaminHoegh** [comment]
`[ChatControlRed]  Unhandled exception listening to AsyncPlayerChatEvent`

**Comment by ElBananaa** [comment]
> `[ChatControlRed] Unhandled exception listening to AsyncPlayerChatEvent`

It doesn't help me at all.
Please provide your `/chc debug` file.

**Comment by kangarko** [comment]
player_has_permission_ probably needs PlaceholderAPI, it's not in ChatControl by default

**Comment by ElBananaa** [comment]
> player_has_permission_ probably needs PlaceholderAPI, it's not in ChatControl by default

Right, I forgot to mention that. It actually needs the Player expansion in order to work.
`/papi ecloud download Player`
