### ISSUE TITLE
Channel nicknames

### ISSUE THREAD

**Issue by snhnry** [kangarko/ChatControl#62]
It would be helpful to be able to assign chat channels with nicknames for easier switching. For example, global chat could be "g" and one could simply type "/ch j g" instead of "/ch j global"

**Comment by kangarko** [comment]
Thank you for your suggestion. I can try to add name aliases in the next update.

**Comment by kangarko** [comment]
Closing.

Currently I am focusing on more important updates, such as re-adding color support, private messages.
And it would be kinda difficult to implement since I am planning to add the feature of hiding channels players don't have permission to, and also tab complete, etc.

In the future, this might get implemented.
