### ISSUE TITLE
1.16.4 BungeeCord with MySql - CHC not hooking into Nicky plugin for players nickname

### ISSUE THREAD

**Issue by Godlycreations** [kangarko/ChatControl#63]
We use the plugin nicky on our network because it is the only nickname plugin that keeps the players nickname the same across bungeecord network. In CHC 8, it pulls the nick into chat just fine using {nick}, but in this update it is not working any more. I would do away with the Nicky plugin if CHC 10 would have the ability to keep a players nickname across the network and also be able to display it in BungeeTabListPlus. But your nickname tag also does not keep the color formatting to include the bold or italics. No errors are showing in the console for this issue. If you need additional information, please let me know.

**Comment by kangarko** [comment]
Hi there!

We still support Nicky, but you need to remove "nick" from Tag.Apply_On in settings.yml, but I much rather have you use our nicks since it's faster and more compatible into the future.

I made the "/tag nick"  support color and decoration for which the player has his proper permissions, please see /chc perms for a list. 

So from my understanding you want the nicks to show the tablist, too, and they're not shown?

**Comment by kangarko** [comment]
Don't have to ask you, I think it's a great option so I added tablist modification as a feature!
