### ISSUE TITLE
Minecraft version 1.16.5 - Nicknames

### ISSUE THREAD

**Issue by itsBeaco** [kangarko/ChatControl#641]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hey!

Nicknames are only staying active until you reload, once you leave and join back it resets your name. The reason I believe it is ChatControlRed is because when you do /realname it says there is no nickname in the database. Also, how do I change it so the nickname is in the chat too? (sorry about the question in the issue section)

Thanks!
Connor

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hey!
> 
> Nicknames are only staying active until you reload, once you leave and join back it resets your name. The reason I believe it is ChatControlRed is because when you do /realname it says there is no nickname in the database. Also, how do I change it so the nickname is in the chat too? (sorry about the question in the issue section)
> 
> Thanks!
> Connor

Hey!

Regarding your first issue, could you please provide us your `/chc debug` output file? I tried on my own server, and I couldn't reproduce your issue.

Regarding your question, in your format, replace `{player}` and `{player_name}` with `{nick}`. If the player has a nick, it'll show it, if they don't have a nick, it'll show their name.

**Comment by itsBeaco** [comment]
Hey! Thank you for that, here is the debug.zip it gave me https://ufile.io/1ji03z9z

Awesome! I'll try that now!

**Comment by ElBananaa** [comment]
> Hey! Thank you for that, here is the debug.zip it gave me https://ufile.io/1ji03z9z
> 
> Awesome! I'll try that now!

Alright, so I don't really know what could cause your issue. However, please update your ProtocolLib. You're using a version that doesn't support 1.16+.
Since their build server seems down, I attached the latest version to this message. Please try with it and let me know if it fixes your issue.
[ProtocolLib.zip](https://github.com/kangarko/ChatControl-Red/files/5937798/ProtocolLib.zip)

**Comment by itsBeaco** [comment]
Thank you for looking into that and sending that over, I've updated the plugin and gave it a try and unfortunately it's still not working. Having that said my console was getting absolutely spammed by "java.lang.NullPointerException" and that seems to have stopped that at the moment

**Comment by ElBananaa** [comment]
> Thank you for looking into that and sending that over, I've updated the plugin and gave it a try and unfortunately it's still not working. Having that said my console was getting absolutely spammed by "java.lang.NullPointerException" and that seems to have stopped that at the moment

Alright, I also noticed you're using another chat plugin: DeluxeChat. Keep in mind that ChatControl isn't made to work with other chat plugins.

Consider removing DeluxeChat, and also make sure your plugins, their dependencies and your server software (In your case Tuinity) are up-to-date.

**Comment by kangarko** [comment]
If you're getting any errors, please post them. 

As Banana said, by the way thank you for catching up on this, we can't support concurrent DeluxeChat with our tag system, it's probably causing this incompatibility. Just install PlaceholderAPI and use its placeholders to show DeluxeChat's tags but beware that more bad things can occur due to how DeluxeChat cancels the chat event and so do we. Basically you can't have two plugins doing the same thing on your server
