### ISSUE TITLE
1.16.5: Console Spam

### ISSUE THREAD

**Issue by CoutovyLp** [kangarko/ChatControl#644]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hello. I downloaded and upload the ChatControl Red on server. It starting spamming my console.

Debug: https://ufile.io/vwhlwrp0

Error: https://pastebin.com/T22j6UBS

**Comment by TheIntolerant** [comment]
I don't believe you should be getting such error messages as you aren't using chatcontrol on a Bungeecord network, however, if you add ``server-name=my_server`` or something like that in ``server.properties``, that should hopefully stop the spam of that specific error message.
For more info go to <https://mineacademy.org/server-properties/>

^^ only a temp fix tho :P
Since I am 99% sure non-bungeecord users, should not receive such errors as it isn't needed. :)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hello. I downloaded and upload the ChatControl Red on server. It starting spamming my console.
> 
> Debug: https://ufile.io/vwhlwrp0
> 
> Error: https://pastebin.com/T22j6UBS

Hey!
The error message is self-explanatory: You must add `server-name=Your Server Name` to your server.properties.



> I don't believe you should be getting such error messages as you aren't using chatcontrol on a Bungeecord network, however, if you add `server-name=my_server` or something like that in `server.properties`, that should hopefully stop the spam of that specific error message.
> For more info go to https://mineacademy.org/server-properties/
> 
> ^^ only a temp fix tho :P
> Since I am 99% sure non-bungeecord users, should not receive such errors as it isn't needed. :)

Even tho he isn't on a Bungee Setup, you must define a server-name in your settings. Afaik, it works like that to avoid any issues if you ever want to switch to MySQL at some point. So no, this isn't a temp fix. Anyways, thanks for answering him.
