### ISSUE TITLE
1.16.5: Similarity?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#649]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, why is please similarity showing 70% when I have set 60% in config? and I didn't set anything special for groups.
![image](https://user-images.githubusercontent.com/18662086/107165186-6edcee80-69b2-11eb-9a6a-ad23b72c4c5f.png)
```
    # Block repetitive messages if they are similar to the previous one, in percent.
    # Set to 0% to disable.
    Similarity: 60%

```

**Comment by TheIntolerant** [comment]
That value changes depending on how similar the messages are, so that message is just saying it is 70% similar and therefore was blocked. If you were to say "Test", then again repeat yourself and say "Test", it would say "Please do not type messages that are 100% similar" but if you were to say "Test 1", then again say "Test 2", it would say "Please do not type messages that are 83% similar".

``Similarity: 60%`` Just means the plugin will block anything that is 60-100% similar,

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, why is please similarity showing 70% when I have set 60% in config? and I didn't set anything special for groups.
> ![image](https://user-images.githubusercontent.com/18662086/107165186-6edcee80-69b2-11eb-9a6a-ad23b72c4c5f.png)
> 
> ```
>     # Block repetitive messages if they are similar to the previous one, in percent.
>     # Set to 0% to disable.
>     Similarity: 60%
> ```

Hey!
Everything was said above!

@gone-incognito Thanks for answering him! 

I'm closing this issue, feel free to open a new one if you need anything else.
