### ISSUE TITLE
Plugin causing server ping timeouts.

### ISSUE THREAD

**Issue by zaxman22** [kangarko/ChatControl#65]
Whenever I have this plugin installed, my server always crashes without an error message, only saying:

[Multicraft] Stopping server! 
[Multicraft] Ping timeout! Restarting server...

I don't have many plugins, and this only happens with this installed. Is there something in the plugin that could be stressing out my server?

**Comment by kangarko** [comment]
Hey,

from the very little information you provided, it is almost impossible to find out the problem.
In general no, this plugin it not hardware expensive, but if you have bad regular expressions then it might stuck on sync events like signeditevent or playercommandevent

**Comment by zaxman22** [comment]
Right, probably should have sent the config and list of plugins. Here they are.

settings.yml: http://pastebin.com/tpiATc5a
plugin list: Plugins (29): SimpleBackup, WorldEdit, EasyPermissionsEx, FrameProtect, VoidSpawn, Vault, PermissionsEx, WorldGuard, PlotSquared, LampControl, CoreProtect, ASkyBlock, NoRain, HiveJumpPads, ProtocolLib, ImageOnMap, Lift, Essentials, EssentialsSpawn, VanishNoPacket, ServerListPlus, Multiverse-Core, EssentialsChat, HolographicDisplays, ShowCaseStandalone, CommandSigns, Multiverse-Portals, Multiverse-Inventories, HolographicScoreboard

**Comment by kangarko** [comment]
It is (almost) impossible that this plugin crashes the server. Try disabling the console filter (Console.Filter.Enabled).
You have plenty of plugins that are touchy regarding server stability, e.g. protocollib (there were several bugs since the developer switch), holographics- display and scoreboard (unsure but they are playing with packets) and also showcasestandalone might be unstable (it was in 2012, I didnt use it since then)

**Comment by zaxman22** [comment]
Alright, let me give it a go without the console filter on. I've never had any problems with protocollib even after the developer switch. I'll give it a go.

**Comment by zaxman22** [comment]
Ran it for a while without console filter enabled, everything runs smooth. I don't understand how a filter with only a few things could cause ping timeouts...

**Comment by kangarko** [comment]
Hello,
Sorry for late response. If any issue occur, please let me know. I am not quite sure that the console filter was the problem since it is a lightweight feature, I am using it on a production server with dozens of messages without any ping timeouts.

Oh, I think it is because the filter has hidden some messages that MultiCraft was reading and so preventing MultiCraft to see them. If this is the case then just remove them, in most cases they are the login / leave / kick messages.
