### ISSUE TITLE
1.16.5: Ultra Punishments unable to mute

### ISSUE THREAD

**Issue by cades66** [kangarko/ChatControl#657]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I am using Ultra Punishments (referred to as uPun) across my bungeecord server along with ChatControl Red. Every aspect of uPun works except mutes - it seems that ChatControl still allows messages to be sent if a player is muted! Why is this?
![javaw_r0s0hdQsG7](https://user-images.githubusercontent.com/57970060/107393336-4e9b5580-6ac0-11eb-8b2b-9135cd2072bc.png)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, I am using Ultra Punishments (referred to as uPun) across my bungeecord server along with ChatControl Red. Every aspect of uPun works except mutes - it seems that ChatControl still allows messages to be sent if a player is muted! Why is this?
> ![javaw_r0s0hdQsG7](https://user-images.githubusercontent.com/57970060/107393336-4e9b5580-6ac0-11eb-8b2b-9135cd2072bc.png)

Hey!
That might be caused by the chat listener priority. Try playing with it. You can find it in your settings.yml: `Chat_Listener_Priority`.
You can find the different levels that can be used here: https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities
Also don't forget to restart your server every time you change the listener priority.

Let us know if you found a configuration that fixed the issue, and if so, which one, so we can update the wiki. :)

**Comment by cades66** [comment]
I set it to highest priority and mutes are working - but players can still use commands such as /msg. Any idea how to fix this?

**Comment by ElBananaa** [comment]
> I set it to highest priority and mutes are working - but players can still use commands such as /msg. Any idea how to fix this?

I think you must see that either with @kangarko or contact Ultra Punishment author so they could add support for ChatControl-Red in order to block that.

**Comment by kangarko** [comment]
Yeah this is an incompatibility, sorry about that. We recommend users to use our own mute feature which we now have a whole setup for and can't add compatibility for the dozens of ban mgt plugins out there. We already support the top mute plugins:

![a](https://i.imgur.com/SFNFByx.png)
