### ISSUE TITLE
1.16.5: Add possibility to disable conversation mode

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#677]
The conversation mode confuses a lot of players. Despite having good FAQ on my server, people just refuse to read or cannot understand where to read and how this feature is even called. Some people accidentally send an empty message and thus toggle the conversation. 

I suggest to add an option to `setting.yml` to completely disable this feature. I think some other servers have same problem as me.

If such an option already exists, please help me to find it, because I failed to do so in docs and setting. Thanks.

**Comment by TheIntolerant** [comment]
Since it is just ``/msg {username)`` to toggle this, you can prevent this with a simple regular expression and create the rule in the file ``command.rs`` inside the ``rules`` folder in ChatControl.

Example
```
# Prevents users from enabling conversation mode
match ^\/(tell|w|m|t|pm|message|msg|whisper) ([a-zA-Z0-9_]{3,16})$
then warn &cUsage: /$1 (username) (message)
then deny
```

**NOTE**
Just make sure you add all of the tell aliases under ``Private_Messages:``, in case you've added or changed the default tell aliases As shown below.
```
  Tell_Aliases:
  - 'tell'
  - 'w'
  - 'm'
  - 't'
  - 'pm'
  - 'message'
  - 'msg'
  - 'whisper'
  ```

**Comment by radiant-ai** [comment]
Ok, good it can be solved with a rule. I will leave this open in case the dev decides if it is a good idea to add a toggle in `settings.yml` as well.

**Comment by kangarko** [comment]
Thanks, I think it's just going to stay on and optionally toggleable with a rule. I'll place that rule into our command.rs file as commented out.
