### ISSUE TITLE
1.16.5: Bug with  "then replace" on latest version of ChatControl

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#679]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Example 1**
```
match \:bat\:
then replace \/\|\\ \^\._\.\^ \/\|\\
```

**Example 2**
```
match \:bat\:
then replace /|\ ^._.^ /|\
```
----------------------------------
Prior to **ChatControlRed 10.2.3**, Example 1 worked fine, as I had to use ``\`` to allow chatcontrol to replace ``:bat:`` correctly as it used regex delimiter in the ``then replace`` section. However due to the changes made on the update of ChatControl, it stopped processing ``then replace \/\|\\ \^\._\.\^ \/\|\\`` like it did before which would replace ``:bat:`` with ``/|\ ^._.^ /|\`` in chatcontrol 10.2.2

Since when I did ``:bat:`` (using Example 1) it would replace that with exactly this ``\/\|\\ \^\._\.\^ \/\|\\``, so I tried to use Example 2 instead.

Yet when using Example 2, instead of replacing ``:bat:`` with ``/|\ ^._.^ /|\``, due to the regex delimiter used in the ``then replace`` section, it would often replace ``:bat:`` with ``/`` or ``\`` or something weird like that.

**Comment by kangarko** [comment]
Use example 2, however you need to prepend any | character with \ because otherwise we will interpret this as a delimiter, so that the plugin will randomly choose one out of the three parts of the message created by the two | letters, either just /, or the middle part, or the end /.

This works:

```
match \:bat\:
then replace /\|\ ^._.^ /\|\
```

![a](https://i.imgur.com/IBu7kEc.png)
