### ISSUE TITLE
Tab Complete Again :)

### ISSUE THREAD

**Issue by Tptuaazn** [kangarko/ChatControl#685]
No example for use tab-complete feature D:?

Minecraft Version: 1.16.5

**Comment by ElBananaa** [comment]
> No example for use tab-complete feature D:?
> 
> Minecraft Version: 1.16.5

Hey!

What do you mean by "no example"? Everything's explained in the file.
`Enabled:` = `true` to enable, `false` to disable.
`Prevent_If_Below_Length:` = Prevent completion for words shorter than the number specified.
```
  Whitelist:
  - '@blacklist'
  - '(/ver|/version)\b'
  - '(/pl|/plugins)\b'
  - '/hiddenCommand'
```
Since we specify `@blacklist` at the biggining, it turns the whitelist to a blacklist. It means every commands listed under can't be tab-completed. If you wish to use it as a whitelist, so only the commands listed can be tab-completed, remove the `@blacklist`:
```
  Whitelist:
  - '(/ver|/version)\b'
  - '(/pl|/plugins)\b'
  - '/hiddenCommand'
```
And there you go, only the commands listed above can be tab-completed now.
You can also give users `chatcontrol.bypass.tabcomplete` permission to bypass this check, so they can tab-complete every command.

**Comment by Tptuaazn** [comment]
if I use Via Version + Via Backwards and Tab-Complete doesn't work at lower versions (<1.13) is there a way to solve this problem?

**Comment by ElBananaa** [comment]
> if I use Via Version + Via Backwards and Tab-Complete doesn't work at lower versions (<1.13) is there a way to solve this problem?

Hey!
I don't know about that infortunately. I guess the plugin uses packet manipulations to cancel the tab complete event, and I know that packets don't really like that. Anyways, you should see that with Kangarko ^^

**Comment by kangarko** [comment]
Sorry Via-kind of plugins tend to break this outside of our control.
