### ISSUE TITLE
[Annoyance] - Auto Announcer

### ISSUE THREAD

**Issue by Intensearmadillo** [kangarko/ChatControl#70]
Hello,
The config has a prefix, for different worlds. That's great. It also has a prefix, only available to apply to ALL of these worlds. If possible, this needs to be made per world.

In addition, the prefix - even if not set - adds a space " " (or two), which is really annoying. Again, if possible, please could this be adjusted so if the user would require a space between his prefix and message, he would have to do so himself.

In my config:
PREFIX : '&3&lTip &7\\'
MESSAGE: '&eTo see faction information of a specific player, hover over their name.'

This shows up as "&3&lTip &7\\  &eTo see faction information of a specific player, hover over their name."
with two spaces between the prefix and the message, for some reason.
(https://www.dropbox.com/s/wc4ach0wdj2agpd/Screenshot%202015-01-21%2019.32.31.png?dl=0)

Please allow it so my config will look like this:
PREFIX : '&3&lTip &7\\ ' (Added space to prefix manually)
MESSAGE: '&eTo see faction information of a specific player, hover over their name.'

So it will turn out like this:
"&3&lTip &7\\ &eTo see factio..." (only one space, as before there was two)

Thanks for your time, I really appreciate it!

**Comment by kangarko** [comment]
Hey,

I have tested this configuration: http://pastebin.com/REY0gaY8
and no double space is written between those messages.

Can you post your settings.yml? You can send me a private message on spigot forums if you dont like your config to be posted.

Sorry but if you want a custom prefix on different worlds you have to manually add the prefix before every message and leave the Prefix to '' (Prefix: '') - Currently there will be one additional space in the beginning but I just fixed that and so it will be fixed in 5.0.4

**Comment by Intensearmadillo** [comment]
The extra space issue works fine for some reason now. I'll report back if I have further issues in the future.
Many thanks,
Toby.
