### ISSUE TITLE
1.16.5: Triggering Legacy Material Support

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl#714]
```
[14:16:20] [Server thread/INFO]: [ChatControlRed] Enabling ChatControlRed v10.2.5
[14:16:20] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
```

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> ```
> [14:16:20] [Server thread/INFO]: [ChatControlRed] Enabling ChatControlRed v10.2.5
> [14:16:20] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
> ```
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hey!
This message is due to the fact that the plugin actually works under a wider range of versions. You can ignore it since it doesn't change anything on your side. Some forks like Purpur also have an option to remove these messages as they are useless in most of the cases. However, keep in mind that ChatControl-Red doesn't officially support any Paper fork.
On the other side, I personally use Purpur on my server without running into a single issue related to it.
