### ISSUE TITLE
1.16.5: bungee message get cleared when deleting a message

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#715]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Im currently having a bungeecord network setup which 4 servers
When i clear a chat message with the red X in front, it looks like all bungeecord related messages wont be replaced correctly and are missing in the that, for example the join, quit or server-switch message

Idk if this is the intended behaviour but it might be a bug, i would really appreciate if you can have a look :D
Thanks, Len

**Comment by kangarko** [comment]
This is intended behavior because the Minecraft clients stores a history of chat messages on its own. You will see this behavior especially after you relog into the game and you see the messages before you joined from the last time you played. They will be cleared but not restored since the server does not have them anymore.
