### ISSUE TITLE
1.16.5: Own made strip colors?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#730]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, is it possible to make strip colors on my own? So, when I will set it in settings.yml to false, how to make it to check? I wanna check it only in groups.yml that's why I wanna make it on my own... Cause then it's not working in commands or chat, where I want to use it.

For ex. this is my code. How to disallow there using for ex &c&l or just &a there please?

```
#deb
match (?:(?!debír|de bo|dě bi)(d|ď)+([^a-zA-Z0-9_ěščřžúůôĺľäýíáéďťň]|\d|_)*(e|ě|é|ë)+([^a-zA-Z0-9_ěščřžúůôĺľäýíáéďťň]|\d|_)*(b)+([^a-zA-Z0-9_ěščřžúůôĺľäýíáéďťň]|\d|_)*(i|o|í|ó|ï|ö))
group swear
ignore perm chatcontrol.bypass.swear
then replace @prolong *
then sound <AMBIENT_CAVE>
```

Btw I want to just match &e&l, I don't wanna to remove colors from it.

**Comment by kangarko** [comment]
You can use "before strip" to make the filter ignore colors before matching the string "match"... Or, since you've set Strip_Colors to false, you can now use "match \&e" explicitly and it should match the &e color IF the player does not have permission to transform it into a real color. If he has it, then use "match \§e" or use "match (\§|\&)e" to match both.
