### ISSUE TITLE
private message rules

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl#740]
why private messages don't fallow the global chat rule or any other rules ?

**Comment by Plum1111** [comment]
How did you manage to completely disregard the issue format entirely?

Anyways they fall under the command rule im pretty sure and I'm certain they do follow global ..

**Comment by FakEEE14** [comment]
how and where to enable or disable ?

**Comment by ElBananaa** [comment]
Hey!
@Plum1111 Thanks for answering him.

Next time, please follow the issue format. You should take a look at this post: https://github.com/kangarko/ChatControl-Red/issues/515
Also, being polite helps. Saying hi never killed anybody.

Anyways, regarding your issue, I'm not sure about it, but it makes sense that private messages should follow the rules located in `/plugins/ChatControlRed/rules/command.rs`.
Since the command rules also include rules from `/plugins/ChatControlRed/rules/global.rs`, you can configure your rules in both your global.rs and command.rs files.
For more infos, please take a look at the wiki page: https://github.com/kangarko/ChatControl-Red/wiki/Rules

In order to enable rules in a specific part of the plugin, open your `/plugins/ChatControlRed/settings.yml` file, and search for the `Rules:` part.
Then simply read the comments and enable the parts where you'd like to enable the rules system.
This is how it looks like in the default file: 
```
Rules:
  
  # Where should the rules be applied to?
  # [TIP] You can import rules from other files by writing @import <rule type> in your .rs files.
  # Options: chat, command, packet, sign, book, anvil, tag
  Apply_On:
  - 'chat'
  - 'command'
  - 'packet'
  - 'sign'
  - 'book'
  - 'anvil'
  - 'tag'
  
  # Print the '*--------- Rule match (X) for Y ---------' messages into the console?
  # [TIP] You can hide this per-rule using the "dont verbose" operator.
  Verbose: true
  
  # Remove colors from checked messages? Prevents bypasing filters by using colors: fu&cck.
  # [WARNING] This will remove all custom colors in the message in case it is filtered!
  # TURNING THIS OFF can break packet rules and make players able to bypass rules by using colors.
  Strip_Colors: true
  
  # Replace accents before matching? Such as "dáma" to "dama" or "gjøre" to "gjore" etc.
  # This is applied against the "match" operator.
  #
  # [IMPORTANT] If this is enabled, DO NOT USE accents in your rules because using them will break
  # the rule. Only put "match dama" or "match gjore" and all dama, dáma and gjøre and gjore will
  # automatically be matched for you.
  Strip_Accents: true
  
  # Evaluate the "match" operator in rules/ case insensitively? Poses slight performance penalty.
  # NB: When testing on regex101.com make sure you toggle "insensitive" and "unicode" flags
  # when testing expressions to get accurate results: https://i.imgur.com/QEDZx5N.png
  Case_Insensitive: true
  
  # Prevent regular expressions from rules and messages freezing the server if they take 
  # more time than the amount specified below, in milliseconds.
  # IF THE FIRST MESSAGE AFTER PLUGIN'S RELOAD TRIGGERS A RULE THIS MAY HAPPEN, IT'S NORMAL
  Regex_Timeout_Ms: 500
```

**Comment by FakEEE14** [comment]
this
match ^\/(tell|w|m|t|pm|message|msg|whisper) ([a-zA-Z0-9_]{3,16})$
then warn &cUsage: /$1 (username) (message)
then deny
prevent for swearing in /msg?

**Comment by ElBananaa** [comment]
> this
> match ^/(tell|w|m|t|pm|message|msg|whisper) ([a-zA-Z0-9_]{3,16})$
> then warn &cUsage: /$1 (username) (message)
> then deny
> prevent for swearing ?

No it doesn't. Swearing rules are located in your global rules. Just take a deeper loik at the file

**Comment by FakEEE14** [comment]
im telling again global rules block swearing but not swears from /msg

**Comment by ElBananaa** [comment]
> im telling again global rules block swearing but not swears from /msg

Provide us your chc debug file

**Comment by FakEEE14** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6054606/debug.zip)

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6054606/debug.zip)

Alright, so apparently, you need to copy your swear rules from the `rules/global.rs` into `rules/commands.rs`. The @import at the beginning of the file should already do that, but for some reasons, it doesn't.

**Comment by FakEEE14** [comment]
so this is not a question and it's a bug report

**Comment by ElBananaa** [comment]
> so this is not a question and it's a bug report

Probably, I don't know if this is intended or not, but I don't think so. However, since you didn't follow the format, I won't reopen this issue. So feel free to open a new one following the format.
