### ISSUE TITLE
emojis stopped working

### ISSUE THREAD

**Issue by Rongel92** [kangarko/ChatControl#747]
Hi, I'm using emojis in the chat and they worked fine but for some reason they just stopped showing up I can see them when I type the command but in the msg it's just showing the name on the emoji and not the emoji any idea why?

**Comment by ElBananaa** [comment]
> Hi, I'm using emojis in the chat and they worked fine but for some reason they just stopped showing up I can see them when I type the command but in the msg it's just showing the name on the emoji and not the emoji any idea why?

Hey!
Please follow the question format next time.

Also, please provide us you `/chc debug` file.
Are you using the plugin on a single server, or on a bungee setup?
Are you using MySQL with the plugin?

**Comment by Rongel92** [comment]
Sorry ill make sure to use it next time
this is the debug.zip I got from that command: https://ufile.io/grymce40
its a single server and I'm not using mysql

**Comment by ElBananaa** [comment]
> Sorry ill make sure to use it next time
> this is the debug.zip I got from that command: https://ufile.io/grymce40
> its a single server and I'm not using mysql

Thanks.
It looks like you're using an outdated version. Please update to the latest version (v10.2.7) so we can provide you a proper support.

**Comment by Rongel92** [comment]
I updated it and still not working this is the new debug files
https://ufile.io/7m45o12p

**Comment by ElBananaa** [comment]
> I updated it and still not working this is the new debug files
> https://ufile.io/7m45o12p

Alright, so from what I can see, all the emojis are commented so this is probably the reason why they don't work.

**Comment by Rongel92** [comment]
can u explain to me how to fix this?
how do I uncomment the emojis?

**Comment by ElBananaa** [comment]
> can u explain to me how to fix this?
> how do I uncomment the emojis?

In `rules/chat.rs`, under `# Smileys (some turds call them emojis)`

remove the `#` before all
```
#match :-\(
#then replace ☹
```
So it'll look like that:
```
match :-\(
then replace ☹

match (:\))|(;\))
then replace ㋡

match \:star\:
then replace ★

...
```

**Comment by Rongel92** [comment]
i wasent talking about those smiles im using other plugin for emojis and they worked but stopped working after I installed the new version that was out of chat control plugin and in the older version it worked

**Comment by ElBananaa** [comment]
> i wasent talking about those smiles im using other plugin for emojis and they worked but stopped working after I installed the new version that was out of chat control plugin and in the older version it worked

Chatcontrol doesn't support other chat plugins. However, you can try to change the listener priority: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

**Comment by Rongel92** [comment]
I tried changing the priority to highest and I started getting double text In chat so I changed back to high but now I still get two msgs in the chat
let me send a pic maybe u can tell me how I fix this and also in one msg the emojis show and the other doesn't
![image](https://user-images.githubusercontent.com/49457146/109671156-8146e400-7b7c-11eb-9a33-643f704e5472.png)

**Comment by Rongel92** [comment]
so the second line of text is coming from this   Format_Console: '[{channel}] {player}: {message}'
and u can see that the emojis are working there but not in the chat format that's in the plugin.
what do I do to hide the second msg and also how do I make the emojis work in the regular format

**Comment by ElBananaa** [comment]
> I tried changing the priority to highest and I started getting double text In chat so I changed back to high but now I still get two msgs in the chat
> let me send a pic maybe u can tell me how I fix this and also in one msg the emojis show and the other doesn't
> ![image](https://user-images.githubusercontent.com/49457146/109671156-8146e400-7b7c-11eb-9a33-643f704e5472.png)

Are you using a specific plugin to show the rank "plates"? If so, what's the name/link? You might need to ask its author to add compatibility for chatcontrol, or Kangarko might have to do this himself, I don't really know. Regarding the `Format_Console:`, it shouldn't be shown in the chat, since it's supposed to be the format used in the console. Also, in which file is the`:admin:` "emoji" registered?

**Comment by Rongel92** [comment]
the plugin im using is itemsadder betterranks
the :admin: is in a json file

**Comment by Rongel92** [comment]
i dont know why the console format is showing now cause I literally didn't change a thing just the listener but then I changed it back.
i did a full restart and not just a reload between changes so nothing gets broken
that's even worst then the emojis not showing up :/

**Comment by ElBananaa** [comment]
> i dont know why the console format is showing now cause I literally didn't change a thing just the listener but then I changed it back.
> i did a full restart and not just a reload between changes so nothing gets broken
> that's even worst then the emojis not showing up :/

Well, as I said, ChatControl doesn't support other plugins handling the chat. Try with other priorities. If it still doesn't work, you'll have to wait for Kangarko.

**Comment by Rongel92** [comment]
ill give that another go and try other priorities the weird thing is that it used to work and then after I updated the chatcontrol plugin it stopped working
if the priorities won't help ill try reinstalling the plugin and see if that helps...

**Comment by ghost** [comment]
I think the way itemsadder is handling those custom icons/emotes is by detecting and recplacing a given format like :happy: with a specific text-character which is overwritten from the custom fonts in the ressource-pack, but due to ccr has its own chat formatting it wont work with each other without specific support. I think you can easly recreate the funtionality with ccr's chat rules and a some knowledge of cutom ressource packs. I can have a look later on when im home...

**Comment by kangarko** [comment]
We don't support third party chat plugins because we send the chat message in a different way than Bukkit allows.

We cancel the entire chat event and send this using our own method to allow interactive hover/click events.

As last resort you could check the Listener Priority article as Banana suggested and play with all priorities, not sure if you only tried HIGHEST but try all of them to see if any of those stick.

If that broke recently it may be due to a change in your other chat plugin. I would really just recommend switching to our own rules system like Banana explained which is in rules/chat.txt where you can turn things into emojis.

**Comment by 00Hrtz** [comment]
> 
> 
> the plugin im using is itemsadder betterranks
> the :admin: is in a json file

Can i ask how you managed to get betterranks img's to load in ChatControl, i can not find any information on how it can be done anywhere. Been trying for days to get them to load and still waiting on a reply for my help request. Any help would be greatly appreciated Ronglito.
