### ISSUE TITLE
1.16.5: AsyncPlayerChatEvent problem

### ISSUE THREAD

**Issue by Kamo452** [kangarko/ChatControl#768]
Minecraft version: 1.16.5
MySQL: true
BungeeCord: true

ChatControl-Red delivers messages very slowly. TPS is good.
Console:  [ChatControlRed 10.2.7] ChatListener listening to AsyncPlayerChatEvent
 at HIGHEST priority took 1199.19 ms
The LOWEST monitor has the same problem.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6075228/debug.zip)

Edit: WorldGuard/ProtocolLib dev builds versions have the same issues

**Comment by ElBananaa** [comment]
> Minecraft version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> ChatControl-Red delivers messages very slowly. TPS is good.
> Console: [ChatControlRed 10.2.7] ChatListener listening to AsyncPlayerChatEvent
> at HIGHEST priority took 1199.19 ms
> The LOWEST monitor has the same problem.
> 
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6075228/debug.zip)
> 
> Edit: WorldGuard/ProtocolLib dev builds versions have the same issues

Hey! This is a pretty weird issue, and it shouldn't happen. From what I can see in your debug file, there's nothing that should cause a such issue. Instead of lowering the Listener Priority, try to increase it.
Some people also already reported issues related to ExploitFixer/HamsterAPI, however, I don't know if this is related.
Finally, make sure you're using the latest version of your server software (paper), I also noticed some pretty obvious message latency (especially when I send messages, it looks like they're sent with more than 500ms of latency) since paper introduced Adventure, however, I never had this message in the console.

I'll leave it open so Kangarko could take a look at it.

**Comment by kangarko** [comment]
I replied on https://github.com/kangarko/ChatControl-Red/issues/758
