### ISSUE TITLE
1.16.5: From where is taken {server_name}

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#769]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I wanna ask from where is taken {server_name} placeholder that can be used in commands. Cause in server properties I have just Lobby:
![image](https://user-images.githubusercontent.com/18662086/109860305-41f0c400-7c5e-11eb-8910-4f444c6c3a91.png)
![image](https://user-images.githubusercontent.com/18662086/109860421-6ba9eb00-7c5e-11eb-9991-c32962f15b63.png)

So from where is this taken please? And when I write from console it uses right name
![image](https://user-images.githubusercontent.com/18662086/109860352-53d26700-7c5e-11eb-9ae1-ecfbb54f917a.png)

**Comment by TheIntolerant** [comment]
I believe this issue #754 is also related.

**Comment by kangarko** [comment]
Where do you have "MCReunion Lobby" set up? The {server_name} should be pulled from server.properties file

**Comment by kangarko** [comment]
@Westloch regarding your issue please can you tell me where do you have "A minecraft server" set if not in server.properties? What about BungeeCord's config.yml ?

Also is this problem showing during standard chat in a channel that's connected to BungeeCord? Between two different servers or on the same server?

**Comment by Westloch** [comment]
> @Westloch regarding your issue please can you tell me where do you have "A minecraft server" set if not in server.properties? What about BungeeCord's config.yml ?
> 
> 
> 
> Also is this problem showing during standard chat in a channel that's connected to BungeeCord? Between two different servers or on the same server?

There was only one thing that i saw that contained "A minecraft server", within **server.properties**  "A minecraft server" was the default motd. I did change that to match the server name, i thought maybe the servers name was being pulled from that instead of "server-name="

Besides that i dont think i have "A minecraft server" anywhere, on the proxy config all the motd are not "A minecraft server" they are something else.


I only have 2 channels within chat control, one is global and the other is helpop, both with **Bungee: true**. This is the same across all the servers (all the files are identical), the issue is the same across all servers

**Comment by bobhenl** [comment]
> Where do you have "MCReunion Lobby" set up? The {server_name} should be pulled from server.properties file

This is what I don't know... in server properties is just Lobby, where could be word "MCReunion"? I looked to some files and I can't find it... I looked to server properties, spigot, bukkit, paper, tuinity, yatopia, bungee config, settings of chatcontrol and can't find it anywhere :/ I think I've used it before in server properties, but now it's using Lobby for few months already

And weird is when I'm writing from console it's using just "Lobby"..

May is it possible that it stored old value?

**Comment by kangarko** [comment]
Thanks guys, I am investigating this and will return asap, sorry that I did not make it to today's release.

**Comment by Squeej** [comment]
I had the same exact problem. Change the server name in your papi config.

**Comment by kangarko** [comment]
@bobhenl @gone-incognito can you try what @Squeej has recommended?

**Comment by TheIntolerant** [comment]
I can confirm that if you use Placeholder API and also use the [server expansion](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#server), it will override chat control's placeholder since PlaceholderAPI uses the ``server_name`` placeholder. As stated above, once the server name in the placeholderapi config file is changed and you restart the server or type ``/papi reload`` it fixes the server name.

As I stated, I believe this only affects users who use [server expansion](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#server) with PlaceholderAPI.

**Comment by bobhenl** [comment]
yeah, you were right.

**Comment by kangarko** [comment]
Thanks, I've added this to the wiki!
