### ISSUE TITLE
[1.16.5] Delete Messages Function Not Working

### ISSUE THREAD

**Issue by NiNjAiKoToBa** [kangarko/ChatControl#777]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6096376/debug.zip)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

There seems to be an issue with 1.16.5 where the X in the chat for deleting the message does nothing, where it worked perfectly on 1.15. I had a look through the wiki but could not find any instructions regarding the function. I've tried reverting all configs back to the default to test it, and the issue seems to happen even on a default config.

![image](https://user-images.githubusercontent.com/5144099/110226024-192d3080-7ee3-11eb-82e5-43717a662bb5.png)

**Comment by ElBananaa** [comment]
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6096376/debug.zip)
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> There seems to be an issue with 1.16.5 where the X in the chat for deleting the message does nothing, where it worked perfectly on 1.15. I had a look through the wiki but could not find any instructions regarding the function. I've tried reverting all configs back to the default to test it, and the issue seems to happen even on a default config.
> 
> ![image](https://user-images.githubusercontent.com/5144099/110226024-192d3080-7ee3-11eb-82e5-43717a662bb5.png)

Hey!
As written on the update log, this is a known issue due to latest paper builds. Kangarko is aware of this issue and is already working on fixing it. Keep an eye on the upcoming updates and the update logs, we'll let you know there once the bug is fixed.
![image](https://user-images.githubusercontent.com/53318613/110227304-1805fe80-7ef7-11eb-8a8c-5328d71be16e.png)

**Comment by kangarko** [comment]
Will actually get fixed soon!
