### ISSUE TITLE
1.16.5: Plugin turns disable

### ISSUE THREAD

**Issue by CoutovyLp** [kangarko/ChatControl#783]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hello. Everythinks work fine, I didn´t change anything and then it was Automatic restart. From that moment, the plugin just starting disabled.

Here is error.log
https://pastebin.com/wNSqGeLT

**Comment by CoutovyLp** [comment]
Still not fixed. I tried check all formats etc, but everything looks ok :/

**Comment by ElBananaa** [comment]
> Still not fixed. I tried check all formats etc, but everything looks ok :/

Hey! Please update to java 11. This is now the official minimum supported version for paper 1.16.5+. This update won't break anything with other plugins.

**Comment by CoutovyLp** [comment]
Oh ok. But Hosting doesn´t have in list Java 11.. There is only this:

https://ctrlv.cz/XKpe

And down it´s Java SE 8xx

**Comment by kangarko** [comment]
Your hosting does not have sufficient memory to run the combinations of plugins you have selected. You likely need more RAM or hardware.

Also remove your data.db and MySQL if you use this because apparently you had a very old version with a previous structure that is not upgradeable there (maybe from our private testing?).
