### ISSUE TITLE
1.16.5: auto join, per world permissions not assigning correctly

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#824]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi there,

I'm trying to achieve per world chat functionality, and have configured Discord SRV integration etc. In doing so however, I'm trying to auto assign permissions that will force the user into a given channel when joining a specified (without giving them the option to change the selected chat with commands)

Is there an easier way to achieve the desired per world channel functionality, cause it seems as though the autojoin of another world isn't overriding the previous autojoin.

Permissions image:
https://imgur.com/a/gnV0qK2

**Comment by ElBananaa** [comment]
Hey!
Actually the plugin doesn't automatically switch your actual channel based on a region.

**Comment by ghost** [comment]
Hi, I'm aware of that. I should have specified, I'm using luckperms to assign the neccesary permissions to auto assign channel access per world, however it is not working as intended so was wondering if there's an alternative method.

**Comment by TheIntolerant** [comment]
Just add the rules I have below, to your ``chat.rs``, ``plugins/ChatControlRed/rules/chat.rs`` Make sure to add it to the bottom of the file, so they don't prevent other rules from being executed in your chat file, since ``then deny`` is used.

**Notes for how this channel switch works**
*The channel switch will only happen when the user tries to talk in chat. If you would like the user to change chats on world change (instead of switching when chatting), you may need to look for another plugin that can run those console commands on world change*

*while this will make it so it automatically switches when a user talks, this may result in users missing messages from that specific channel, if they do not talk (or do not talk soon after joining that world).*

```yml
# Switches channel for user if not in child-spawn channel while in a spawn world
match (.*)
require world childspawn
ignore channel child-spawn
then console channel join child-spawn write {player}|channel sendas {player} child-spawn $0
then deny

# Switches channel for user if not in child-survival channel while in a survival world
match (.*)
require world childsurvival|childsurvival_nether|childsurvival_the_end
ignore channel child-survival
then console channel join child-survival write {player}|channel sendas {player} child-survival $0
then deny

# Switches channel for user if not in child-creative channel while in a plot world
match (.*)
require world childplot
ignore channel child-creative
then console channel join child-creative write {player}|channel sendas {player} child-creative $0
then deny
```

**EXTRA NOTES**
You may also want to go into your localization file and hide these messages by setting it to ``''``
I set ``Success: ''``, ``Leave_Reading: ''`` under ``channels`` > ``join`` in the localization file. To hide the message about the channels as shown below.

![84684384384384](https://user-images.githubusercontent.com/48093184/112156961-d9807b80-8c3a-11eb-8530-c696e6d82e0e.JPG)

**Comment by kangarko** [comment]
That is brilliant @gone-incognito, I've added this as an example to the default chat.rs file!
