### ISSUE TITLE
1.16.4: Removing chat messages

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/ChatControl#825]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

When removing message from chat with the [X] it removes the message. When removing another message it will bring the deleted message back.
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6183344/debug.zip)

Video:
https://ufile.io/297knle0

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: false
> BungeeCord: false
> 
> When removing message from chat with the [X] it removes the message. When removing another message it will bring the deleted message back.
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/6183344/debug.zip)
> 
> Video:
> https://ufile.io/297knle0

Hey!
Thanks for reporting the issue, however, I can't reproduce it under my own setup.
Please make sure your plugins and their dependencies are all up to date.
I also noticed you have a plugin named UltraStaffChat. Keep in mind that plugins like this one can cause issues with chatcontrol. Consider using chatcontrol channel system in order to create your own staffchat.
I also recommend you update your java version to java 11 since this is the new minimal supported version of java for paper 1.16+.
Finally, you should consider updating to paper 1.16.5. There's no protocol version change, so 1.16.4 & 1.16.5 players should be able to join your server. Also, even tho there's no changes in the protocol version, some plugins (especially the ones using NMS) may need to be updated, so once again, make sure to update these plugins if you chose to update to paper 1.16.5. (And don't forget to run a full backup before updating, just in case something goes wrong).

**Comment by Greazi-Times** [comment]
The reason that I did not update my server is that plugin that I am using are not 1.16.5 yet there for I need to wait.

The part about ultraStaffchatPro is that this a premium staff chat plugin and using it hasn't affect anything with chatcotrol red.

**Comment by ElBananaa** [comment]
> The reason that I did not update my server is that plugin that I am using are not 1.16.5 yet there for I need to wait.
> 
> The part about ultraStaffchatPro is that this a premium staff chat plugin and using it hasn't affect anything with chatcotrol red.

Well, once again, as I said, I can't reproduce this under my own setup (prod and test server), nor under a fresh install with paper 1.16.5. So I guess this is version related (Might be caused by the changes made to chc-red since paper integrated adventure).
If some of your plugins are still not updated, you should highly consider replacing them ^^

Also, at least make sure ProtocolLib is up-to-date (Download the latest dev build, and try with it). Same thing with java, consider updating to java 11, and try again.

**Comment by Greazi-Times** [comment]
I was planning on updating the server to 1.16.5 the problem with these plugins are that there is no other plugin out there that can do it.

Developing a own made version will take me more time than waiting for them to be updated.

I will see if I can update my server to 1.16.5 and see if it still happens. I will le you know if it fixed the problem.

**Comment by ElBananaa** [comment]
> I was planning on updating the server to 1.16.5 the problem with these plugins are that there is no other plugin out there that can do it.
> 
> Developing a own made version will take me more time than waiting for them to be updated.
> 
> I will see if I can update my server to 1.16.5 and see if it still happens. I will le you know if it fixed the problem.

Alright, thanks!
Once again, if updating to 1.16.5 is a real problem for you, at least try to update your java version and your ProtocolLib version. ^^

**Comment by Greazi-Times** [comment]
Oor I am using a vps and I am using pterodactyl as a panel. So I can just download the latest Java version??

If you don't know just say it and I will ask somewhere els.

**Comment by ElBananaa** [comment]
> Oor I am using a vps and I am using pterodactyl as a panel. So I can just download the latest Java version??
> 
> If you don't know just say it and I will ask somewhere els.

You might need to download it. Stop your servers, download it by using  `apt install openjdk-11-jdk` then `sudo update-alternatives --config java` and chose `java 11`.
Once this is done, start your servers

**Comment by ElBananaa** [comment]
Hey!
Getting back to you since, I just updated my server to the latest version of paper, and I could finally reproduce this issue.
I guess we'll both have to wait for Kangarko now ^^

**Comment by Spaex** [comment]
Same wanted to report the bug also. Same happend to me yesterday.

**Comment by Greazi-Times** [comment]
I think it happens after you change things in the config and than reload it but I am not sure

**Comment by ElBananaa** [comment]
> I think it happens after you change things in the config and than reload it but I am not sure

Not really, in my case, I tried after a reboot. without editing anything, and I had the issue ^^

**Comment by ghost** [comment]
Same issue here, i discovered this while having it setuped with bungeecord

**Comment by kangarko** [comment]
Investigating, looks like an issue with Adventure in PaperSpigot again, may take a few days to solve.

**Comment by ghost** [comment]
I have the same issue myself and have been meaning to report it

**Comment by kangarko** [comment]
Finally fixed guys, thanks for the patience!
