### ISSUE TITLE
Discord format chat

### ISSUE THREAD

**Issue by Z3dC0d3** [kangarko/ChatControl#832]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false
![Screenshot_1](https://user-images.githubusercontent.com/22939278/112463287-f790cd80-8d59-11eb-9411-d6e32ddea182.png)

How I can setup to show from discord without placeholder , on settings.yml I setup everything from wiki page , but I don't know how to fix that !

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> ![Screenshot_1](https://user-images.githubusercontent.com/22939278/112463287-f790cd80-8d59-11eb-9411-d6e32ddea182.png)
> 
> How I can setup to show from discord without placeholder , on settings.yml I setup everything from wiki page , but I don't know how to fix that !

Hey!
Please provide us your `/chc debug` output file, so we could take a look at what you've done.

**Comment by kangarko** [comment]
Using tags and luckperms and also many other variables is unsupported when sending a message on Discord to Minecraft because there's no Player instance in Spigot.

Use Format_Discord in your channel configuration in settings.yml and put another chat format there so that messages from Discord are formatted differently.

You'll find help and examples right in settings.yml in the comments.
