### ISSUE TITLE
ChatControlRed + ItemsAdder Emoji

### ISSUE THREAD

**Issue by Tylwen** [kangarko/ChatControl#853]
## 2024 Update: Please read [ItemsAdder official article on integration with ChatControl](https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/chatcontrol-red) first before opening a new ticket.

https://github.com/kangarko/ChatControl-Red/issues/830

Hello, it's me again.

The developer of ItemsAdder tells me to just add:
FontImageWrapper.replaceFontImages (player, message)
using a free maven package at https://itemsadder.plugin.ga/developers/java-api

Please add this functionality. I can no longer play the carrier pigeon with all the developers to make everything work as before.

**Comment by Tylwen** [comment]
Hello ?!

**Comment by ElBananaa** [comment]
> Hello ?!

Hey!
Please be patient, Kangarko will take a look at your request when he has some free time.

**Comment by kangarko** [comment]
I am quite busy this week so not sure when this gets added, however please try changing the formatter priority as shown here: https://github.com/kangarko/ChatControl-Red/wiki/Listener-Priorities

Chances are that the other plugin will change the variables before us when you change our priority, fixing this problem without me needing interfering.

**Comment by Tylwen** [comment]
I have already tried changing the priority of listener, but nothing helps.

**Comment by kangarko** [comment]
Thanks, not a priority right now but I will aim to add this within the next 7-12 days or so

**Comment by Tylwen** [comment]
Thank you, as long as it's fixed I'm happy ^^

**Comment by LoneDev6** [comment]
https://github.com/kangarko/ChatControl-Red/issues/830#issuecomment-806025674
> 
> 
> Hey!
> This is due to the fact that ItemsAdder is trying to send the emojis on the default chat system, which is overwritten by chatcontrol-red. You should probably ask the ItemsAdder dev to add support for ChatControl-red.



Maybe I'm just dumb but your API doesn't provide a way to replace the message in your `PlayerMessageEvent`, so I'd wait for your to integrate ItemsAdder directly.
Thanks

**Comment by kangarko** [comment]
@LoneDev6 thank you, I added the integration, will be available starting the next version

<img width="1138" alt="Screenshot 2021-04-13 at 09 07 49" src="https://user-images.githubusercontent.com/1918426/114511077-bba1a780-9c37-11eb-87a9-0ed68415ed18.png">

**Comment by LoneDev6** [comment]
> 
> 
> @LoneDev6 thank you, I added the integration, will be available starting the next version
> 
> <img alt="Screenshot 2021-04-13 at 09 07 49" width="1138" src="https://user-images.githubusercontent.com/1918426/114511077-bba1a780-9c37-11eb-87a9-0ed68415ed18.png">

Amazing, thanks for the efforts, I really appreciate that

**Comment by Tylwen** [comment]
Hello, doesn't that seem to be working? Is there a specific configuration for its proper functioning?
It doesn't seem to work on the channels

**Comment by LoneDev6** [comment]
Okay so basically the function `FontImageWrapper.replaceFontImages(player, message)` will also check if the player has permission to use the emojis.
In order to skip that check and directly replace any emoji the function needs to be called without passing any player: `FontImageWrapper.replaceFontImages(message)`

But I doubt it would be a good behaviour since permission checking is important, so I suspect your users don't have permission to use the single emoji (font_image) or to use emojis in chat.

For example:
`ia.user.image.chat` : to use emojis in chat
`ia.user.image.command` : to use emojis in commands
`ia.user.image.use.smile` : to use smile emoji 
`ia.user.image.use.*` : to use all emojis

More info here about permissions: 
https://itemsadder.plugin.ga/plugin-usage/permissions
https://itemsadder.plugin.ga/plugin-usage/permissions/example-permissions

**Comment by Tylwen** [comment]
![2021-04-13_22 40 02](https://user-images.githubusercontent.com/26263998/114618139-4ec6f580-9ca9-11eb-8f4a-1a3bb8ad854e.png)
However, I have the latest updates of the ChatControlRed and ItemsAdder plugins
And im op in this server
The problem is still the same, emojis don't work in channels. Whether I change the priority or not

**Comment by LoneDev6** [comment]
Maybe ItemsAdder is loading before ChatControl because the plugin.yml file of ChatControl doesn't include ItemsAdder in its softdepend @kangarko 
So `itemsAdderInstalled` returns always false

**Comment by Tylwen** [comment]
softdepend: [AuthMe, BanManager, BungeeChatAPI, CMI, DiscordSRV, Factions, Feudal, **ItemsAdder**, Essentials, LegacyFactions, Lands, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI, MythicMobs, mcMMO, Nashorn, Nicky, PlaceholderAPI, ProtocolLib, SimpleClans, Towny, TownyChat, Vault, WorldEdit]

Its good for that @LoneDev6

**Comment by LoneDev6** [comment]
@kangarko Found the issue:

![immagine](https://user-images.githubusercontent.com/27242001/115030446-62e83e00-9ec7-11eb-9cd9-e67aab420085.png)


![immagine](https://user-images.githubusercontent.com/27242001/115030456-667bc500-9ec7-11eb-85e0-0435dbb0f4d3.png)
It's ItemsAdde`r` not ItemsAdde`d`

**Comment by ElBananaa** [comment]
Hey guys!
Sorry for the delay, Kangarko isn't present for now, he'll probably be back near monday.

I already reported him the typo issue with ItemsAdder : 
![image](https://user-images.githubusercontent.com/53318613/115053201-27f20480-9edf-11eb-9b40-b704d70fac18.png)

**Comment by kangarko** [comment]
Oh sh*t what a stupid mistake! My fault, I forget to double-check. Just purchased your plugin LoneDev, will be testing this asap.

**Comment by kangarko** [comment]
Starting to get this work, added this for everyone using Foundation because it's pretty cool! https://github.com/kangarko/Foundation/commit/216568e624d33fd01191a9c0f86cb8bb46266e99

One thing I've noticed, it reverses the chat color back to white, can this be mitigated? Also happens when I explicitly type `&c red :bye: ahoj`

<img width="379" alt="Screenshot 2021-04-21 at 11 06 12" src="https://user-images.githubusercontent.com/1918426/115527718-9cd38e80-a291-11eb-8b12-241385dfa04b.png">

**Comment by LoneDev6** [comment]
It's okay @kangarko we all do mistakes :D 

To fix this I may have to introduce a new method that allows you to pass a color as parameter which will be added at the end of the emoji, but it would make things complicated I think.
Basically the reason why I set the text to white is because emoji would get the text color applied so I have to make sure it's white, the downside is that the next text will also become white.

If you prefer you can add me on Discord for faster communication and we may find a clean solution

**Comment by kangarko** [comment]
Thanks, I prefer to keep this over GitHub since we get tons of tickets/communication.

Is the only way to put images in the chat using : in front and : at the end of a word like `:bye:`?

**Comment by kangarko** [comment]
If yes we have an easy solution for that ;)

**Comment by kangarko** [comment]
<img width="540" alt="Screenshot 2021-04-21 at 11 28 55" src="https://user-images.githubusercontent.com/1918426/115531187-c7731680-a294-11eb-9d81-a2e4910c39eb.png">

<img width="508" alt="Screenshot 2021-04-21 at 11 29 07" src="https://user-images.githubusercontent.com/1918426/115531203-cd68f780-a294-11eb-9c34-ae11264214cb.png">

Works fine, we already use this for sound notify tagging players feature. A new release should appear tonight thanks for all the help and patience! If you'd like you can point ChatControl Red in your Overview page in the list of plugins using your APIs :)

**Comment by LoneDev6** [comment]
> Thanks, I prefer to keep this over GitHub since we get tons of tickets/communication.

I totally understand, I too get a lot of tickets to handle so it's okay.

> Is the only way to put images in the chat using : in front and : at the end of a word like `:bye:`?

Yes and no. ItemsAdder supports PlaceholderAPI and registers a placeholder `%img_NAME%`, but I doubt it will be used in chat, it's useful only on TAB menu, other plugins, signs, holograms etc..



> 
> 
> If yes we have an easy solution for that ;)

Very nice! Anyway instead of that you probably should use regex, I didn't try or benchmark it but using regex should be faster (you can benchmark it yourself using [Duration and Instant](https://stackoverflow.com/a/28274381/9084675) ).

> Works fine, we already use this for sound notify tagging players feature. A new release should appear tonight thanks for all the help and patience! If you'd like you can point ChatControl Red in your Overview page in the list of plugins using your APIs :)

No worries, I'm always happy to see people integrating my framework in their plugins.
Anyway I already added it [on my wiki ](https://itemsadder.plugin.ga/compatibility-with-other-plugins/compatible/chatcontrol-red)a week ago 😉

**Comment by ConnerEstes** [comment]
Sorry to bother, considering this thread is about 2 years old. I purchases chc red and i do currenlly have items adder, but i cant seem to get the emojis to show up at all when i enable the channels and the formatting. If anyone could help id appreciate it ! :)

**Comment by kangarko** [comment]
Have you read and followed this? Including the issue mentioned there:

https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/chatcontrol-red

**Comment by ConnerEstes** [comment]
I’ll have to try this! Thank you!

**Comment by ConnerEstes** [comment]
Now if I wanted it to be player rank specific, how would I do this/ what would the format look like? Considering I use luck perms for ranks and perms. Sorry for the multiple messages

**Comment by kangarko** [comment]
You can see at formats/chat.yml how we split different format parts according to player permissions. You can give each rank a unique permission in luckperms.

**Comment by ConnerEstes** [comment]
I figured it out, thank you so much!

**Comment by TomLewis** [comment]
> Have you read and followed this? Including the issue mentioned there:
> 
> https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/chatcontrol-red

Googled "chatcontrol red itemsadder", im so glad theres history, this is why peolpe making tickets inside discord sucks, you cant find thigns like this to resolve learning!

**Comment by kangarko** [comment]
Agreed, thank you!
