### ISSUE TITLE
[Improvement] Softmute

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#894]
This is a request in response to a feature breaking within another plugin (softmute via GriefPrevention) as a result of switching to CHC Red. 

I utilised softmute alot however since switching to CHC Red i've noticed that softmute doesn't mute players at all, others can still see the message. Since this relates to chat, I think it would be a simple and great addition to CHC Red.

**How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
Would give server owners the ability to softmute a player whereby the player's messages (including death, join/leave) are only visible to staff members (e.g. via permission node). This allows staff to mitigate situations without the need to hardmute players (e.g. softmuting conflicting parties and evaluate a situation).

**EDIT:**
This could also be turned into some type of channel e.g. whereby only softmuted players can see another softmuted players chat.

**Comment by TheIntolerant** [comment]
Just for extra clarification, should this be added...(In case the developer isn't familiar with GriefPrevention's softmute command), the /softmute command basically is like a standard mute, however, it works the same as the [``then deny silently``](https://github.com/kangarko/ChatControl-Red/wiki/rules#then-deny-silently) operator for chatcontrol rules. However, the softmute does not apply to private messaging etc, to trick the user into believing they 100% aren't muted. 

In other words, the soft muted user does not know they have been muted. I am 100% in support of this being added, while I will show how this can be done with chatcontrol rules, people who are new to chatcontrol may find it overwhelming to set this up.

---------------------------------------------------------
**Example of How To Create a Soft Mute Command, Using ChatControl Rules**

**How does the example I have provided work?**
Basically, you want to give everyone perms for ``chatcontrol.chatsoftmute.bypass``, now when you wish to softmute someone, you just need to negate that permission node for that specific user. You can do this by either making a ``/softmute`` command or simply using the commands of your permissions manager, if you are using LuckPerms than that command would look something like:
``/lp user <user> permission set chatcontrol.chatsoftmute.bypass false``
For Pex
``/pex user <user> add -chatcontrol.chatsoftmute.bypass``
etc.

**EXTRA NOTES:**
*The permissions I have used in the example here: ``chatcontrol.chatsoftmute.bypass``, ``chatcontrol.chatsoftmute.notify``, can be whatever you wish*

------------------------

**Step 1) Creating the base rule, to prevent other users from seeing the soft muted users message in chat**
In your ``chat.rs`` file in ``/ChatControl-Red/Rules`` you will want to add one of the following...

*Option 1 (works the same as GriefPrevention's softmute)*
```
match (.)*
ignore perm chatcontrol.chatsoftmute.bypass
then notify chatcontrol.chatsoftmute.notify &7[Muted] {player} &o{original_message}
then deny silently
dont verbose
```
*Option 2 (works the same but if you do not wish to see what the user said, just remove then notify)*
```
match (.)*
ignore perm chatcontrol.chatsoftmute.bypass
then deny silently
dont verbose
```

------------------------

**Step 2) Creating a softmute command** *(optional)*
(this will depend on the permissions plugin that you use, in this example, I will use LuckPerms)
As I cannot find an easy solution to check a player's permissions who may be offline using a toggleable command, I have provided a
``/softmute on`` and ``/softmute off`` solution instead.

In your ``command.rs`` file in ``/ChatControl-Red/Rules`` you will want to add one of the following...
```
# Telling user how to use /softmute, if used incorrectly
match ^\/softmute( on| off)?$
then warn &cUse: /softmute <on/off> <player_name>
then deny
dont verbose

match ^\/softmute on ([a-zA-Z0-9_]{3,16})
then warn &cSoft-muting $1
then console lp user $1 permission set chatcontrol.chatsoftmute.bypass false
then deny
dont verbose

match ^\/softmute off ([a-zA-Z0-9_]{3,16})
then warn &aRemoving soft-mute from $1
then console lp user $1 permission unset chatcontrol.chatsoftmute.bypass
then deny
dont verbose
```

------------------------

**Step 3) Hiding death, join/leave messages from everyone but staff**
This part I am not 100% sure about but I assume if you add
``require sender perm chatcontrol.chatsoftmute.bypass`` for all messages you wish to show as normal 

then have a special message for soft muted users that has the following
``ignore sender perm chatcontrol.chatsoftmute.bypass``
``then notify chat control.chatsoftmute.notify <message>``
``require self``



Note the message in ``then notify chatcontrol.chatsoftmute.notify <message>`` is for staff only, so the acatual death/join/leave message can be set to look like normal. 

That way you can set it to say something like.. ``then notify chatcontrol.chatsoftmute.notify &6The Soft muted {player} has died!`` but keep the message the soft muted player sees, as normal.

**Comment by kangarko** [comment]
This is epic! I've added this to our wiki @gone-incognito: https://github.com/kangarko/ChatControl-Red/wiki/Soft-Mute

**Comment by LogGits** [comment]
Ok i have come to the conclusing that @gone-incognito is too overpowered and must be nerfed... How dahek u think of this 😂

**Comment by LogGits** [comment]
@gone-incognito what would you recommend I do to have it function the same (so that other players who are softmuted also see the message) via:
```
/SoftMute | Partially mutes a player (he and others on soft mute will still get his messages).
```

**Comment by TheIntolerant** [comment]
@LogGits Okay, so this is where I need you to be as specific as humanly possible 😂

Are we talking about "chat messages" aka messages sent from a player in the normal chat

Or "private messages" aka messages sent to a specific player via /msg, /reply etc

**Comment by LogGits** [comment]
@gone-incognito chat messages (e.g. playerA and playerB are both softmuted and can see each-others messages)

**Comment by TheIntolerant** [comment]
That should be easy enough to do. To achieve that, I suggest that we not only do we negate the perm ``chatcontrol.chatsoftmute.bypass``, but also give a permission node to the users who are "soft muted", that way, we can use the ``then notify`` operator to allow soft muted players see the messages of each other.  Thankfully, you can use the same operator multiple times in a rule on ChatControlRed which wasn't possible in ChatControlPro!

------------------------------------------------

In order to allow, soft muted players see the chat messages of other soft muted players. You want to make the following changes to the rules, I have provided above.

------------------------------------------------

In your ``chat.rs`` file in ``/ChatControl-Red/Rules`` you will want to add one of the following options....

Option 1 (works the same as GriefPrevention's softmute)
````
match (.)*
ignore perm chatcontrol.chatsoftmute.bypass
then notify chatcontrol.chatsoftmute.notify &7[Muted] {player} &o{original_message}
then notify chatcontrol.chatsoftmute.muted <message or format>
then deny
dont verbose
````
Option 2 (works the same but if you do not wish to see what the user said)
````
match (.)*
ignore perm chatcontrol.chatsoftmute.bypass
then notify chatcontrol.chatsoftmute.muted <message or format>
then deny
dont verbose
````
**NOTE** the reason I left ``<message or format>``, in this is where you would want to set it to the chat formata of your specific server. Say you are using the format ``global-chat.yml`` in ``/ChatControl-Red/formats`` You would set this to
``then notify chatcontrol.chatsoftmute.muted global-chat`` etc, keep in mind, this format will remain the same regardless of what channel they speak in (unlike the previous examples I provided)

------------------------------------------------

In your ``command.rs`` file in ``/ChatControl-Red/Rules`` you will want to add one of the following...
```
# Telling user how to use /softmute, if used incorrectly
match ^\/softmute( on| off)?$
then warn &cUse: /softmute <on/off> <player_name>
then deny
dont verbose

match ^\/softmute on ([a-zA-Z0-9_]{3,16})
then warn &cSoft-muting $1
then console lp user $1 permission set chatcontrol.chatsoftmute.bypass false
then console lp user $1 permission set chatcontrol.chatsoftmute.muted true
then deny
dont verbose

match ^\/softmute off ([a-zA-Z0-9_]{3,16})
then warn &aRemoving soft-mute from $1
then console lp user $1 permission unset chatcontrol.chatsoftmute.bypass
then console lp user $1 permission unset chatcontrol.chatsoftmute.muted
then deny
dont verbose
```

------------------------------------------------

**Explanation**
For the ``/softmute off`` and ``/softmute on``, we are doing two things, negating the permission ``chatcontrol.chatsoftmute.bypass`` and adding the perm ``chatcontrol.chatsoftmute.muted`` to soft muted players, which will allow the soft muted players to see the messages of other soft muted players.

As for the ``match (.)*`` rules, basically, everything is the same except we add ``then notify chatcontrol.chatsoftmute.muted <message or format>`` which allows soft muted players to see the messages of other soft muted players and the other changes I have made is switching ``then deny silently`` to ``then deny``. So the person sending a message in chat does not see their own messages two times.

**Important Note**
I strongly advise you to negate the permission node ``chatcontrol.chatsoftmute.muted`` for staff who have ``chatcontrol.chatsoftmute.notify`` and OP users. To prevent issues such as them seeing double messages etc.
If you use luckperms all you need to do is
``/lp group <group_name> permission set chatcontrol.chatsoftmute.muted false`` etc.

------------------------------------------------

Hopefully that helps, I haven't actually tried any of this myself but I am 99% sure it should work fine, if you have any issues feel free to me know if I have made any errors :P

**Comment by LogGits** [comment]
Thanks a tonne for the explanation, will use that system 👍

**Comment by LogGits** [comment]
Not able to test this right now but is it possible to use this to notify players without the permission:
```
then notify !test.perm example text
```

**Comment by 10Meisterbaelle** [comment]
It would be great if this could be implemented into the actual /mute command as an option in the settings.yml or maybe as a flag in the /mute command (like -s for softmute), because this workaround with permissions doesn't really seem that great.

**Comment by kangarko** [comment]
We're now open source as my time is very reduced this year, contributions are welcome. Thank you for understanding.
