### ISSUE TITLE
Hello, but does that mean, That ChatControl Red is really slow and lags my Server?

### ISSUE THREAD

**Issue by socksprox** [kangarko/ChatControl#903]
Here are my Timings: https://timings.aikar.co/?id=a8e5f473363843a2bce71ed37637ac05
If its not ChatControl, does anyone know how to optimize?

Thanks in advance

**Comment by ElBananaa** [comment]
Hey!
First of all, you're not using Aikar's flags while you should, so try with them : https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/
In a second time, make sure all your plugins and your server software are up-to-date.
Finally, if you want to, you can enable async messages in chatcontrol's settings file.
```yaml
  Async:
  - 'join'
  - 'quit'
  - 'kick'
  - 'death'
  - 'timed'
```
While this can improve the plugin performances, it's important to know that this is experimental, and that I can break some variables or operators of the plugin. I recommend you give it a shot on a test server with the prod server configuration, and if it works fine, then you can deploy it on your prod server.

Anyways, I doubt your whole tps issue is (entirely) caused by ChatControl-Red. I'd say it's more a badly optimized/configured global setup, than an issue caused by a single plugin.

As a last tip, since it looks like you're running a survival server, consider preloading the map using plugins like Chunky, this will greatly help for performance. (Ofc, pregenerate the map with no players online, since it's a heavy task, it could cause a lot of lags, or even crashes in some cases, if players are connected.)

**Comment by socksprox** [comment]
Hello, thanks for your answer, i enabled async chat messages now. But i have another question: How do i enable Auto Broadcast for the whole server in chatcontrol red? I know how to do so in ChatControl Pro, but not in red

**Comment by TheIntolerant** [comment]
timed messages are what you are after, everything you need to know about these types of messages can be found in https://github.com/kangarko/ChatControl-Red/wiki/Messages

This is found via ``ChatControl-Red\messages\timed.rs``

To enable any of the types of messages:
**join messages, quit messages, kick messages, death messages and timed messages**

Just check ``Messages:`` in your settings file.

**Comment by ElBananaa** [comment]
Hey!
Thanks to @gone-incognito for answering! :)
May I close this issue @TaminoPalm?

**Comment by ElBananaa** [comment]
Hey!
Since you didn't answered to the issue, I'm considering this as potentially solved. I'm closing this issue. Feel free to comment in the issue mentionned above if you still experience performance issues.

**Comment by kangarko** [comment]
@TaminoPalm I can see high timings for /tell and /reply, which is normal if Toast notifications are enabled since we must save advancements to the disk on the main thread... check if Private_Messages.Toasts are on and try toggling them off

@ElBananaa just so you know <3
