### ISSUE TITLE
1.16.5: Chat Color doesn't persist through restarts.

### ISSUE THREAD

**Issue by myiume** [kangarko/ChatControl#915]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

It seems that the chat colors are not persistent. Players are complaining about their colors resetting back to default after a while. I believe it happens after the daily restart, though I am not 100% sure.

Is there persistence implemented for the player chat colors?

**Comment by kangarko** [comment]
Chat color is saved to mysql. Since you're using database, check whether this is being properly saved : 

<img width="979" alt="Screenshot 2021-04-21 at 13 49 56" src="https://user-images.githubusercontent.com/1918426/115549041-7a00a480-a2a8-11eb-8485-f8f162608b2c.png">

**Comment by Squeej** [comment]
I have this problem as well. Interestingly it doesn't happen to players with op

Edit: It does seem rather random on my end, testing on an alt showed that most of the time chat colors would reset when re-logging, but sometimes it wouldn't

Players on my server do have to connect to a lobby first before they join their preferred server and I suspected that had something to do with it since the lobby also has chc installed but players don't have chat color permissions there. Maybe chc resets chat colors when they join a server where they don't have said color permission?

So I gave chat color permissions to the default group in the lobby, and that worked for like a month. And then the problem came back :/ Hope this helps with the investigation

**Comment by kangarko** [comment]
Thanks for sharing this info, going to investigate asap

**Comment by kangarko** [comment]
@Squeej and @myiume set Show_Tips to true in settings.yml for all servers and let me know if theres:

`TIP Alert: Removing chat color due to lost permission` or `TIP Alert: Removing chat decoration due to lost permission` messages somewhere, that would mean we removed the color due to missing permission which Squeej pointed out might be the problem

**Comment by kangarko** [comment]
We're saving the files async, that was an experiment, going to remove that feature from the next version of ChatControl. There's gonna be a tiny performance drawback but it should ensure no such things happen in the future.
