### ISSUE TITLE
Suggestion: Re-add parrot and join spam flood

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#923]
**Description**.
What is Parrot? Basically where a user automatically repeats what another user said, much like a parrot. 😉 Which when used in conjunction with a large volume of bots, it can be a very effective way of spamming chat as it can be very challenging to locate who is controlling the bots since it is possible to get the bots to join the server from different IP addresses. 

-----------------------------------

**1. How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
Right now, any measures to prevent spam on ChatControlRed are done at a per-user scale. While this is great for preventing the annoying spammer that may come on from time to time, this does nothing to prevent large spam attacks,  and won't prevent someone from joining with a large number of bots and getting each account to repeat a specific message. Since it isn't a single user repeating the same message, the chat becomes easily overloaded with spam.

-----------------------------------

**2. What would happen if we won't implement this feature? How's your server being affected?**
People would be forced to find a different chat plugin (due to conflict issues that arise from having multiple chat plugins) or a different plugin that handles specific spam and prevents it. 

People may also be inclined to upgrade to ChatControlRed, as ChatControlPro offers this feature.

-----------------------------------

**Also adding "flood chat" for the same reason as mentioned above?**
It is also available via ChatControlPro, so here is part of the config to explain what I am referring to.
https://pastebin.com/J1hpV9Mx

Also just for reference, this is the part of the config for "Parrot" available via ChatControlPro.
https://pastebin.com/gLvYZdy2

**Comment by ElBananaa** [comment]
Hey!

I think this feature was removed due to a very low usage. At least, that's what Kangarko said in #562 ^^

**Comment by TheIntolerant** [comment]
Ahh, that explains why it wasn't added. Unfortunate I happened to be one of those people that actually used that feature. I actually managed to prevent most spam attacks from being successful with the combination of the parrot feature and cc rules. I'll just sit back and hope it gets added one day.

**Comment by ElBananaa** [comment]
> Ahh, that explains why it wasn't added. Unfortunate I happened to be one of those people that actually used that feature. I actually managed to prevent most spam attacks from being successful with the combination of the parrot feature and cc rules. I'll just sit back and hope it gets added one day.

Yeah, suggesting it isn't a bad idea anyways since this is almost 4 months old ^^

**Comment by kangarko** [comment]
Thank you! Yes I can re-add this either tomorrow or early next week :)

**Comment by kangarko** [comment]
I've re-added the join flood feature, works a bit more complex under the hood, you can debug this by setting Debug to [join-flood] in settings.yml.

Correct me if I'm wrong, parrot will work the same as join flood but essentially it just doesn't have a time threshold since joining... do you still need that feature also? Let me know below :)

**Comment by ElBananaa** [comment]
> I've re-added the join flood feature, works a bit more complex under the hood, you can debug this by setting Debug to [join-flood] in settings.yml.
> 
> Correct me if I'm wrong, parrot will work the same as join flood but essentially it just doesn't have a time threshold since joining... do you still need that feature also? Let me know below :)

Hey!
As information parrot should also prevent players to repeat other players' messages (based on a certain threshold or not).

**Comment by kangarko** [comment]
Yes! And that's what the join flood does also but it's only working until a time limit. If user needs the other feature I can add it as well.

**Comment by x1p** [comment]
I'm not sure how long the newly players are monitored for equal messages. I assume they have to start spamming within the Join_Threshold (default 5 seconds).

Example 1:
Bots join, keep silence for a couple of minutes, then start spamming. Usually they stay online for about 5 minutes.

Example 2:
Player turns on "Annoy" function (a.k.a. Parrot) which is a default function in hacked clients.

The Join_Flood function is not equal to parrot.
The Join_Flood function is only for bots and they have to start spamming within the threshold time. It allows chat until the "Min_Players" is reached. It's even triggered by simple greetings. So in order to work safely, one would have to choose safe values to only be triggered in case of bots. In order to block bots effectively, you would need a higher threshold (like 5-10 minutes). In order to minimize the chance to catch friendly groups, you should have a high enough Min_players.

The parrot function is multi functional, covers both examples and is more precise because it's only triggered by the same text within a very short time.

**Comment by kangarko** [comment]
I understand, okay will put this on a todo list to schedule adding next week.

**Comment by kangarko** [comment]
Added to next version!
