### ISSUE TITLE
Still can't make a new line

### ISSUE THREAD

**Issue by LXServers** [kangarko/ChatControl#93]
Enforce_New_Line didn't exist in the settings.yml and I am still unable to create a new line when warning players in the rules section.

**Comment by LXServers** [comment]
bump

**Comment by kangarko** [comment]
Oh, didn't noticed you are on free version, the function is only available in the pro ;). 
In general, most of the systems accept the \n operator everywhere, but on some configurations it just doesn't work. There's little I can do about it here, try using Notepad++ and saving the file in 'ANSI' or 'UTF-8 without BOM' encodings.

I may consider adding that feature to the free in my spare time later on.

**Comment by kangarko** [comment]
Can you post me the part of commands.txt with the section where the new line should work? I'll take a look at it.

**Comment by LXServers** [comment]
Here is my full config http://pastebin.com/ZJJQh6Dx The part where I would like to make a new line is on line 171, I am unable to try saving it as a different file type as you said to at the moment because I am quite busy. Sorry for the late reply.

**Comment by kangarko** [comment]
Fixed in the latest version. Set Enforce_New_Line to true in settings.yml

Please notice this is only a workaround, since it is not possible to make a complete fix due to the incompatibilities in different systems. You might need to add some empty color codes, or adjust them more in order to achieve the desired result.

**Comment by LXServers** [comment]
When you say latest version, will that be v5.3.0 or is there a development version that I am missing somewhere?

**Comment by LXServers** [comment]
I am using this version and I cannot find Enforce_New_Line

**Comment by kangarko** [comment]
A new (5.3.1) will be pushed within an hour :)

**Comment by LXServers** [comment]
I see, thanks.

**Comment by LXServers** [comment]
Hello, thanks for you support so far. However, I am still having issues in using it. I am using the new settings.yml with Enforce_New_Line set to true. I have converted to ANSI and UTF-8 but still not working. Do you have any other ways that I could do this?

**Comment by kangarko** [comment]
Hey, first off I am sorry for the delay. 

I just tested it, but it worked for me. Please ensure you've shut down the server before converting files, as they might be converted back due to a lock when only reloading. I tested using Notepad++ and having the encoding to `UTF-8 (without BOM)`. Are there any console errors? How is the message disorded?

**Comment by kangarko** [comment]
Closing, please remind me if the issue re-occures.
