### ISSUE TITLE
1.16.5: How to allow/disallow a permission group from spying on specified channels

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#942]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi there, I'm trying to disallow moderators from spying on specified channels, I can disable it for them manually however they're able to reactivate it with the spy menu & commands.

Thanks,
Jamie

**Comment by TheIntolerant** [comment]
This is currently not possible with ChatControlRed itself, you may be able to achieve this using plugins such as deluxemenus, in order to add a permisssion to each section of /spy. 

If you do not wish to set up your own custom GUI etc, the only other option you have is to disable spy mode for that channel. For example, say I do not want my Mods seeing my channel called "Admin" I would set ``Channels.List.Admin.Format_Spy`` to ``none``

So it looks like ``Format_Spy: none`` under ``Admin:``

**Comment by ghost** [comment]
Thank you :)

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hi there, I'm trying to disallow moderators from spying on specified channels, I can disable it for them manually however they're able to reactivate it with the spy menu & commands.
> 
> Thanks,
> Jamie

Hey!
Yes, as gone-incognito said, this isn't currently possible. However, this feature was requested a few months ago, but since the plugin was in a pretty early stage, Kangarko decided to postpone it. I'd suggest you make a new suggestion regarding this feature. Who knows, there's a chance that it finally gets added ^^

**Comment by kangarko** [comment]
Hey,

It is our philosophy that spying is sensitive enough that only people that can fully be trusted should have the privilege to do so. In such case there's no need splitting spying into multiple permissions layers. That would only add more complexity and uncovered bugs to our already a very complex codebase.

Thanks
Matej
