### ISSUE TITLE
Discord format

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#953]
Sorry for bad English
How to use the built-in format of Disocrdsrv
![dccccc](https://user-images.githubusercontent.com/75075197/117025475-8287bf00-ad2d-11eb-9d1a-8a81d17c419f.PNG)

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> Sorry for bad English
> How to use the built-in format of Disocrdsrv
> ![dccccc](https://user-images.githubusercontent.com/75075197/117025475-8287bf00-ad2d-11eb-9d1a-8a81d17c419f.PNG)
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hey!
To do so you must disable chatcontrol's DiscordSRV integration in the plugin config file.
```
  # Integration with DiscordSRV. 
  Discord:
    
    # Enable all integration with DiscordSRV?
    Enabled: false
```

**Comment by ghost** [comment]
But this way
discord will not send messages to minecraft

**Comment by ghost** [comment]
Or can new features be added?
Discord format can be set separately for each channel

**Comment by ghost** [comment]
Because I bought it for this feature...

**Comment by ghost** [comment]
![dcQQ](https://user-images.githubusercontent.com/75075197/117048904-16fe1b80-ad46-11eb-8636-71afd39d7353.PNG)

**Comment by ElBananaa** [comment]
> Or can new features be added?
> Discord format can be set separately for each channel

Of course you can ask for new features. But I'm not sure to understand what you're looking for.
Could you please explain further what you're trying to achieve?

**Comment by ghost** [comment]
example
I want to set Discord as a trading channel

Disocrd: [$] [Disocrd] Player: Test

Global-chat channel set Discord to

Discord: [!] [Disocrd] Player: Test

Set separately
Discord-prefix is currently used but like this
Will become like the picture above

**Comment by TheIntolerant** [comment]
I'm not 100% sure I understand either but just to provide some clarification regarding the [formats](https://github.com/kangarko/ChatControl-Red/wiki/Formats), the ``Format_Discord:`` used in ``Channels.List.<channel_name>`` is the format of messages sent from Minecraft to Discord. To Format Messages from Discord To Minecraft, that is controlled under ``Format:``

If you are still having issues, assuming you have already set up [discord](https://github.com/kangarko/ChatControl-Red/wiki/Discord) it might be worth sending your ``Channels.List`` in your settings file and the relevant format files.
For example:
```yml
  List: 
    admin: 
      Format: admin-chat
      Format_Console: '[A-chat {player}] {message}'
    global: 
      Format: global-chat
```
if I had these two channels but I was only needing help with ``global``, then I'd send the ``global-chat.yml`` file in ``/ChatControl-Red/Formats`` otherwise send both the ``global-chat.yml`` file and ``admin-chat.yml`` file if you need help with both.
