### ISSUE TITLE
1.16.5 | Spying menu auto enables when was configured for disabled

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl#975]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
ChatControlRed: 10.3.8

My staff members are disabling some stuff in /spy menu, but each time they rejoin the options get auto enabled again while they manually disabled these.
Why are these settings not being stored? Or am I missing something?

**Comment by TheIntolerant** [comment]
If any of your staff have the permission ``chatcontrol.spy.autoenable`` then each time they join because of that permission node, all the options in spy get auto-enabled. If they do not have the permission (remembering you need to negate the permission for OPs) then anything that they disable in ``/spy menu`` should be remembered by the plugin.

**Comment by AmazedMender16** [comment]
@gone-incognito thought so, ( without trying ) would it have it enabled by default anyway? Or would they then manually have to enable it?
Perfect: auto enable, but keep disabled overwrite

**Comment by TheIntolerant** [comment]
Without that permission node, they would have to manually enable/disable each section of ``/spy`` however it would remember if an option was disabled/enabled.

If they have the permission node, all options are enabled on join and then can be disabled but on rejoin, if they still have the permission ``chatcontrol.spy.autoenable`` all options that were disabled would be enabled again.

**Comment by AmazedMender16** [comment]
@kangarko can you comment on this? Possible solution/change?

**Comment by kangarko** [comment]
Thanks to gone-incognito for answering! We're not planning any changes at the moment.
