### ISSUE TITLE
1.16.5: How to listen to more than 1 channel simultaneously?

### ISSUE THREAD

**Issue by GeleVla** [kangarko/ChatControl#984]
How to listen to more than 1 channel simultaneously?

With what setting or permission do i do that?

**Comment by ElBananaa** [comment]
> How to listen to more than 1 channel simultaneously?
> 
> With what setting or permission do i do that?

Hey!
You can only have one channel at time in write mode. However, you can read as many channels as you want.
In order to join multiple channels in read mode, first of all, in the `settings.yml` file, make sure your `Max_Read_Channels:` is defined to the max number of channels a player can read at the same time.

Once this is done, in order to allow players to manually join a channel in read mode, give the them/give their group the permission `chatcontrol.channel.join.{channel}.{mode}`. Don't forget replace `{channel}` & `{mode}` with the channel name and the mode (So, as example, if I'll use `chatcontrol.channel.join.adminchat.read` for the adminchat.
If you want to automatically make a player/a group join a channel, in addition to the permission above, give them the permission `chatcontrol.channel.autojoin.{channel}.{mode}`.

Finally, if you don't want the player to leave the channel, deny them the permission `chatcontrol.channel.leave.{channel}`. Even if the player has the permission to automatically join a channel, if they leave it manually, they won't rejoin it automatically the next time.
You can find more informations about this on the wiki : https://github.com/kangarko/ChatControl-Red/wiki/Channels#auto-join
