### ISSUE TITLE
1.16.5. How to hide the chat?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#987]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

I want my players who just want to build on the creative server and not be distracted by chat to be able to hide it with some toggle command. Is there sth like that in chatcontrol or is there any way to implement it with rules?

**Comment by TheIntolerant** [comment]
Hey, you can hide change by simply leaving the channel via
/channel leave <channel_name>

How you decide to implement this is up to you but this can be done using rules.

If you are unsure of how to implement such rules, just give me a basic description of what you would like happen and any other relevant information such as world names, channel names etc and I'll be more than happy to help.

**Comment by kangarko** [comment]
Thanks for answering!

**Comment by nikitushu2** [comment]
Hi,

Using the [CommandAlias](https://www.spigotmc.org/resources/commandalias.44362/) plugin I managed to create /showchat and /hidechat commands based on `/ch join-` and `leave channel_name` chc's commands.

![Crop your images in seconds for free! — Mozilla Firefox 15_05_2021 0 19 15](https://user-images.githubusercontent.com/32280863/118333155-ef603d80-b513-11eb-8c6b-dd24c0d60844.png)

They work.

In commads.rs I made rules so that after enabling/disabling the channel, a message would appear:

![Crop your images in seconds for free! — Mozilla Firefox 15_05_2021 0 17 07](https://user-images.githubusercontent.com/32280863/118333230-0737c180-b514-11eb-83ca-09384d43ae18.png)

The problem is that the messages "Chat is on" and "Chat is off" do not appear. 

What to do?

**Comment by ElBananaa** [comment]
> Hi,
> 
> Using the [CommandAlias](https://www.spigotmc.org/resources/commandalias.44362/) plugin I managed to create /showchat and /hidechat commands based on `/ch join-` and `leave channel_name` chc's commands.
> 
> ![Crop your images in seconds for free! — Mozilla Firefox 15_05_2021 0 19 15](https://user-images.githubusercontent.com/32280863/118333155-ef603d80-b513-11eb-8c6b-dd24c0d60844.png)
> 
> They work.
> 
> In commads.rs I made rules so that after enabling/disabling the channel, a message would appear:
> 
> ![Crop your images in seconds for free! — Mozilla Firefox 15_05_2021 0 17 07](https://user-images.githubusercontent.com/32280863/118333230-0737c180-b514-11eb-83ca-09384d43ae18.png)
> 
> The problem is that the messages "Chat is on" and "Chat is off" do not appear.
> 
> What to do?

Hey!
It looks like the messages aren't sent either because the user left the channel before, or because the rule isn't detected. When you use `/showchat` or `/hidechat`, are the rules displayed in the logs/console?
Could you try to replace `then warn` with `then title` and see if it shows something?

Also, there's no need to use a plugin to create a custom command like this one, you could've done it using the rule system or bukkit system (which can be found in the `commands.yml` file in your server root directory)

**Comment by nikitushu2** [comment]
Rules do not appear in the console when commands are being executed.

Titles do not appear either (when changed to "then title ...").

**Comment by ElBananaa** [comment]
> Rules do not appear in the console when commands are being executed.
> 
> Titles do not appear either (when changed to "then title ...").

It looks like the rule is somehow wrong, if it would be correct, when using the command, it would show you some additional informations in the console (You need to have `Show_Tips` enabled in the settings file). 
Once you're sure it's enabled, try again, if nothing happens in the console, then try to use `match ^\/hidechat`, `match ^/hidechat$` or `match ^/hidechat`? instead.

**Comment by TheIntolerant** [comment]
I would almost guarantee that these commands aren't being registered by that plugin, I have personally experienced this issue before. I personally use a plugin to make custom commands since I am able to make more complex commands using conditions etc and have the command return a specific response based on those conditions. Anyway, If a command isn't registered, chatcontrol rules, even other features in chatcontrol such as anti-spam won't work. To fix this issue, you need to find a way to register the command. For me, the plugin I was using just required "register: true" but this will obviously depend on what plugin you are using etc.

However, as ElBananaa stated:
> Also, there's no need to use a plugin to create a custom command like this one, you could've done it using the rule system or bukkit system (which can be found in the commands.yml file in your server root directory)

Any commands created in the ``commands.yml`` file would work fine in chat control, in fact, you can use ``commands.yml`` to make the command registered and have chatcontrol override any type of alias you make in that file for ``/showchat`` etc

------------------------------------------------

**Example**
Once you have removed the commands from the CommandsAlias plugin, go into the ``commands.yml`` in the root directory for your server and add something like
```
command-block-overrides: []
ignore-vanilla-permissions: false
aliases:
  hidechat:
  - say the hidechat command is not working check if chatcontrol is working
  showchat:
  - say the showchat command is not working check if chatcontrol is working
```
The only important thing to note with ``commands.yml`` the command under the alias, must be a real command for the command to be registered. This is why I used the command ``/say`` since that is a vanilla command, as stated above, this command will get overwritten by chatcontrol, so it doesn't technically matter what the command is, just as long as it is a real command like /say.

than inside the ``command.rs`` file in ``/plugins/ChatControl-Red/Rules`` add the following

```
# This rule makes the user join all channels
match ^(\/showchat)
dont verbose
then command channel join global read|channel join local write
then warn "#bbbbbbChat is on"
then deny

# This rule makes the user leave all channels
match ^(\/hidechat)
dont verbose
then command channel leave global|channel leave local
then warn "#bbbbbbChat is off"
then deny
```

------------------------------------------------

**TIP**
99% of the time if you are making custom commands via a plugin, the easiest way to tell if the command is registered is if it works with tab-completion.

**Comment by nikitushu2** [comment]
Thanks for your detailed answers.
No tips are shown. None of the "match .." options worked.

The server does not say anything nor chc reacts.
